### ISSUE TITLE
DSU Fabric Non-Serialized Batches

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#100]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the user Interface for DSU fabric for the Add Batch Screen:
- The ability to create a Batch that is non-serialized.
- If no serial numbers are loaded (refer to #97) then this is a non-serialized batch.
- If no serial numbers are loaded then the serial number check (refer to #93) is by default disabled.

**Acceptance criteria's:**
**positive tests**
- create a batch and do not load any serial numbers.
- create a Datamatrix or other barcode (refer to #101 ) without a serial number and with correct GTIN, Batch and Exp Date details, when scanned this should provide the ePI.

**negative tests / error path testing**
- create a batch and do not load any serial numbers.
- create a Datamatrix or other barcode (refer to #101 ) with a Serial Number, GTIN, Batch and Exp Date details, when scanned this should cause an message to be displayed to the end user.

**Process scenario:**
For some markets we do not serialize products. So the pack of medicine may have a Datamatrix code with just the GTIN, Batch and Expiration Date or it may have a different barcode (Japan for example) with just the GTIN, Batch and Expiration Date.

**Additional information:**
Consider the ability to be able to edit the batch (refer to #99) and add serial numbers after the batch has been released. So this essentially turns the non-serialized batch into a serialized batch, this might be necessary to correct an error. In this case consideration needs to be given Serial number enable/ disable (refer to #93).

**Comment by nhrishi** [comment]
@maherpa2 - one clarification in the negative tests. Since the user has created a batch with no serial numbers, the serial number check would be disabled by default, and then the serial number check wouldn't happen irrespective of serial number exists or not on the product and no error message would be displayed. Are we saying the serial number check should be enabled explicitly in this case (the check based in story #90)?

**Comment by rite2bala** [comment]
[ePI Wireframes - Product and Batch_v0.4.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6100225/ePI.Wireframes.-.Product.and.Batch_v0.4.pdf)


The Wireframes for the product and batch screens are uploaded here.

The add product and edit product  screens follow similar layouts. 
Similarly - the edit batch and add batch screens have a similar layout

**Comment by maherpa2** [comment]
@nhrishi 
Your point 1: If it is a non-serialized batch then there should not be a serial number in the Datamatrix code. If your point is that if scanned Datamatrix code has a serial number then what should happen - this is a good point. If this is a non-serialized batch then the system should give a warning if it sees that AI21 (Serial Number) is part of the scanned Data. However this could be implemented as a future enhancement if it is not already covered.

Your point 2: We would not perform a serial number check for a non-serialized batch.
