### ISSUE TITLE
CSS issues in LPWA

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#1018]
1. info icon appearing too fast
2.  popups should be vertically centered
2. scan button is partially visible sometimes  
![image](https://user-images.githubusercontent.com/1595518/199722217-e6927fb4-bfbe-44df-beac-a7d482213ccf.png)

**Comment by adiganga2002** [comment]
1) terms and conditions like popups should be 100% height
2) leaflet page has 2 scrolls
3)  Realign error like popups header and center on viewport height
4) scan again button adjust size by content and have a max width
5)check scan window on mobile (is deformed )
