### ISSUE TITLE
DSU Fabric Adverse Event Reporting Enable/ Disable

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#102]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the DSU Fabric Manage Product Screen:
- The ability to enable/ disable the Adverse Event reporting.

![image](https://user-images.githubusercontent.com/58995303/109110277-18eca280-7737-11eb-8fdc-4c5f08a7b737.png)

![image](https://user-images.githubusercontent.com/58995303/109110413-5ea96b00-7737-11eb-8260-4d0efa09e0e0.png)

**Acceptance criteria's:**
**positive tests**
- Enable the Adverse Event Reporting and the icon is shown on the App when the Batch associated to this product is scanned
- Disable the Adverse Event Reporting and the icon is not shown on the App when the Batch associated to this product is scanned

**negative tests / error path testing**
N/A

**Process scenario:**
N/A

**Additional information:**
- This is just about enabling/ disabling the visualization of the Adverse event reporting icon on the App. A separate user story will be created for the details behind the Adverse event reporting and how to manage the different endpoints etc.
- Adverse Event Reporting would be used by the patient to report any issues they may have while taking the medicine. It would not be for reporting technical issue with the App for example.

**Comment by rite2bala** [comment]
@salboaie is there any reason why this is in impediment board?

cc @nhrishi
