### ISSUE TITLE
LPWA is unable to load previously added leaflet 

### ISSUE THREAD

**Issue by sumanxp** [PharmaLedger-IMI/epi-workspace#1023]
Reported Issue: "Not Recognized" message is showing up on LPWA when user tried to scan 2D data matrix corresponding to a Product which was previously added. (a week before the release of 1.6.0 version).

The LPWA screen showing up message
  
![Screenshot_20221108-131056_Chrome](https://user-images.githubusercontent.com/25173348/200507920-c59825ad-a363-4192-a96c-22d7a684aee0.jpg)

2D Data Matrix of Sample Product H

![2D-DataMatrix-ProductH](https://user-images.githubusercontent.com/25173348/200508547-973f426b-9d3a-4165-b6c9-57fb5d4b6cf3.png)

Screenshot of Batch in EW corresponding to the Product H
<img width="960" alt="EW-Batch-Product-H" src="https://user-images.githubusercontent.com/25173348/200509867-2a8cd1df-e19c-4b78-bc44-106f61be5593.png">

**Comment by asaccool** [comment]
I was able to scan the code that you provided.

![image](https://user-images.githubusercontent.com/2776528/200510973-7de8e80a-7690-436e-9492-28ed4a4d12d4.png)

How quick did you got the error message? Did you experienced any network issue?
