### ISSUE TITLE
Demiurge Wallet does not close pop up message after DID creation

### ISSUE THREAD

**Issue by sumanxp** [PharmaLedger-IMI/epi-workspace#1028]
Demiurge Wallet does not close pop up message after clicking on close button, nothing happening while hitting the 'X' button.

ePI Version: 1.5.4 and 1.6.0

![DW-pop-up-close-issue](https://user-images.githubusercontent.com/25173348/200807825-f87d6dc4-2b19-48e1-bc0d-1f3fffd24db2.png)

**Comment by adiganga2002** [comment]
This issue was fixed with 1.6.0 release
