### ISSUE TITLE
Demiurge Wallet: Audit Trail is not showing entry for First Admin User registration/ Login for very first time 

### ISSUE THREAD

**Issue by sumanxp** [PharmaLedger-IMI/epi-workspace#1029]
Audit Trail is not showing entry for First Admin User registration/ Login for very first time
The screenshot given below is showing Audit trail of the First Admin user when logged in second time.

ePI Version: 1.5.4
![DW-firstUser-audit-issue](https://user-images.githubusercontent.com/25173348/200809266-81b64fc4-7b13-4f6b-bdb0-e9c97616209c.png)

**Comment by skutner** [comment]
Fixed in 1.6.0 #964
