### ISSUE TITLE
DSU Fabric Authentication Enable/ Disable

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#103]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the DSU Fabric Manage Product Screen:
- The ability to enable/ disable the Authentication features.

![image](https://user-images.githubusercontent.com/58995303/109110952-5e5d9f80-7738-11eb-95bf-454222092be1.png)

![image](https://user-images.githubusercontent.com/58995303/109111011-746b6000-7738-11eb-8ee6-3ad15fff5de9.png)

**Acceptance criteria's:**
**positive tests**
- Enable the Authentication and the icon is shown on the App when the Batch associated to this product is scanned
- Disable the Authentication and the icon is not shown on the App when the Batch associated to this product is scanned

**negative tests / error path testing**
N/A

**Process scenario:**
N/A

**Additional information:**
This is just about enabling/ disabling the visualization of the Authentication icons on the App. A separate user story will be created for the details behind the Authentication and how this would be enabled.

**Comment by salboaie** [comment]
Obsolete, new interface, a solution will be provided with the new AC integration
