### ISSUE TITLE
Demiurge Wallet: Error/ warning/ information Messages appear at the top right corner of the screen can be considered to stay more longer 

### ISSUE THREAD

**Issue by sumanxp** [PharmaLedger-IMI/epi-workspace#1031]
Error/ warning/ information Messages appear while adding wrong DID in group at the top right corner of the screen can be considered to stay little longer so that user can get enough time to read

 
<img width="478" alt="DW-adduser-error-message-time" src="https://user-images.githubusercontent.com/25173348/200810415-195db83b-49a4-4ecf-a1d5-4e1fa238d1b8.png">

**Comment by salboaie** [comment]
Try to put 30 seconds
