### ISSUE TITLE
DSU Fabric/ App SmPC

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#104]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the DSU Fabric Manage Product Screen and App:
- If no SmPC is loaded then then the App should not show the SmPC.

![image](https://user-images.githubusercontent.com/58995303/109111448-37539d80-7739-11eb-8a79-e5ac63bb5fee.png)

- As a general design rule, if something is not available then the icons associated with it should not be visible to the end user.

**Acceptance criteria's:**
**positive tests**
- Create a product and upload an Leaflet and an SmPC. Create a batch for the product. Scan the barcode and the leaflet and SmPC icons are shown and the leaflet and SmPC can be accessed.
- Create a product and upload an Leaflet, do not upload an SmPC. Create a batch for the product. Scan the barcode and only the  the leaflet icon is shown and the leaflet can be accessed i.e. there is no SmPC shown.

**negative tests / error path testing**
N/A

**Process scenario:**
N/A

**Additional information:**
- This is just about enabling/ disabling the visualization of the Adverse event reporting icon on the App. A separate user story will be created for the details behind the Adverse event reporting and how to manage the different endpoints etc.
- Adverse Event Reporting would be used by the patient to report any issues they may have while taking the medicine. It would not be for reporting technical issue with the App for example.

**Comment by andrejstas** [comment]
Two pull requests have been created:

https://github.com/PharmaLedger-IMI/epi-theme/pull/2
https://github.com/PharmaLedger-IMI/leaflet-ssapp/pull/4

**Comment by rite2bala** [comment]
Tested. The SMPC doesnt show when the SMPC is not uploaded. 

Works fine. Moving to UAT.
