### ISSUE TITLE
Business Audit trail wrong for batch creation

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#1046]
When I create a new batch, I get following details for the newly created batch in the audit trail: 
=> it seems that system believes I have "changed" a batch, but instead I have created a new batch!

{
    "username": "ssteiner",
    "reason": "Created batch",
    "itemCode": "ST001",
    "diffs": {
        "gtin": {
            "oldValue": "07613421039424",
            "newValue": "07612111234521"
        },
        "expiry": {
            "oldValue": "221029",
            "newValue": "231231"
        },
        "expiryForDisplay": {
            "oldValue": 1667001600000,
            "newValue": 1703980800000
        },
        "incorrectDateCheck": {
            "oldValue": true,
            "newValue": false
        },
        "productName": {
            "oldValue": "Exjade",
            "newValue": "Algifor"
        },
        "productDescription": {
            "oldValue": "Exjade",
            "newValue": "Algifor 500mg"
        }

**Comment by steinso2** [comment]
@salboaie I just go to batch -> "add batch" and create the batch. All fine, but when I look into the audit trail -> xml file, I see that the batch was "copied"

**Comment by steinso2** [comment]
@adiganga2002 , why is this ticket closed? 
The batch ST002 and ST003 I created to demo you that I get this wrong audit trail. 
Is this wrong audit trail now solved? Can I retest?

**Comment by adiganga2002** [comment]
@steinso2 it-s same for all 3 batches ST001, ST002 and ST003. This batches id are already used with other products.
