### ISSUE TITLE
DSU Fabric Product Settings

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#105]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the DSU Fabric Manage Product Screen:
- Include the functionality to allow the manufacturer to determine under what conditions they may want to show an ePI to the patient.

![image](https://user-images.githubusercontent.com/58995303/109111910-0b84e780-773a-11eb-8910-c67b904cba0c.png)

- This needs to be considered in conjunction with #93. The following flow diagram as well as the associated truth table  is available at #93
![image](https://user-images.githubusercontent.com/58995303/109112227-8e0da700-773a-11eb-905b-63ffd2a46079.png)

**Acceptance criteria's:**
**positive tests**
- Create scenarios as per the truth table in #93 in conjunction with the setting as per 9 above.

**negative tests / error path testing**
N/A

**Process scenario:**
N/A

**Additional information:**
- This is to give manufacturers the ability to determine, based on their Regulatory/ Legal position, whether or not to display an ePI based on the different scenarios.

**Comment by rite2bala** [comment]
[ePI Wireframes - Product and Batch_v0.4.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6100225/ePI.Wireframes.-.Product.and.Batch_v0.4.pdf)


The Wireframes for the product and batch screens are uploaded here.

The add product and edit product  screens follow similar layouts. 
Similarly - the edit batch and add batch screens have a similar layout

**Comment by salboaie** [comment]
@adiganga2002 check if if anything missing and fix/close this item
