### ISSUE TITLE
MAHs firewalls API Authorization token in BDNS

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#1060]
Some MAHs will put an API Authorization token in BDNS (authToken) for their domains.
If an authToken exists for a domain, the client should put a header (to be defined) for each request in order for the firewalls to recognize the request and let it pass

**Comment by merck-dl** [comment]
Do I understand that this is related to getLeaflet API ?

**Comment by salboaie** [comment]
> 
Should be for all requests...

**Comment by salboaie** [comment]
Decision: in BDNS when URLs are defined there will posibility to put a simple string (like https://www.pla.health) or an object like
{
url:"https://www.pla.health",
headers:{
  key:"value"
  }
}

**Comment by mpmerck** [comment]
We have just debug this issue with Cosmin, there are two issues present:
- SmartUrl option check
- the call for http://localhost:8080/leaflets/epi?leaflet_type=leaflet&lang=en&gtin=75809712281004&expiry=28%20-%20Jul%20-%202023&batch=TSTJAN was missing the custom header from BDNS configuration

**Comment by asaccool** [comment]
@mpmerck  a new issue was created for this available at https://github.com/PharmaLedger-IMI/epi-workspace/issues/1166
