### ISSUE TITLE
JSON upload for batch and product accepts values for greyed out fields 

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#1072]
1. I created JSON and set flags to true, even they are grayed out and **shouldn't be maintainable** (because the functions are deactivated)
2. result is: fields were accepted and changed, see result in UI 
![image](https://user-images.githubusercontent.com/78138966/205328129-162d2234-14fb-4e56-b8b4-0baaef2668c9.png)

**Comment by salboaie** [comment]
@steinso2 is this an important fix for MVP1? it will  require new validation code for something that should not happen by accident...

**Comment by steinso2** [comment]
Even if we only consider the field which is part of the scope of MVP1: "enable expired expiration date", it shouldn't be changeable using json. 
We can control it procedural but it has to be clear to all, because I was surprised that it is changeable by json.

In functional requirement we stated; 
Only fields used in MVP1 are allowed to be used in json file (procedural control in user manual).
**If flags/fields in json has different value than defined in the rules for MVP1, it shall fail from processing and shown in “failed import logs” with the relevant error message**

Lets see what the others think
