### ISSUE TITLE
Audit Trail for failed uploaded product and batch shows wrong command

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#1080]
Step: 
1. create json for a complete new product and keep one mandatory field empty
2. upload json and get error message
Result: the command shows that "editing" the product fails. But it should show: CREATION of a new product fails. 
Same in the Audit log:
e.g. 2113111111140 **Edited product - fail**

Command and Audit log has to differentiate if a product was failed to be CREATED vs failed to be UPDATED/EDITED

**Comment by steinso2** [comment]
@salboaie lets discuss in the audit trail meeting on Wednesday. The rules for the audit trail are quite strict and James needs to decide.

**Comment by salboaie** [comment]
@adiganga2002 decision: put as reason : "Fail - See details"
