### ISSUE TITLE
Demiurge Wallet: Screen does not enable first user to select DID Type though the message has indication

### ISSUE THREAD

**Issue by sumanxp** [PharmaLedger-IMI/epi-workspace#1084]
Version: 1.6.1-patch2
Display Message: You do not have a DID, so we will create one.
Choose the DID type and press Create identity button.

Observation: Screen does not enable first user to select DID Type though the message has indication. Hence there is a mismatch  between display message and implementation.

![image](https://user-images.githubusercontent.com/25173348/205851612-a45538f9-67ac-4b6e-ba7e-57d465450a0b.png)

**Comment by salboaie** [comment]
@adiganga2002 remove second line of text
