### ISSUE TITLE
ePI Demiurge Wallet Freeze / Crash when member is added/removed/add/removed in Same Group.

### ISSUE THREAD

**Issue by RakeshL-JnJ** [PharmaLedger-IMI/epi-workspace#1089]
1. Demiurge Wallet Admin has logged-in.
2. Go to Groups. Select ePI Admin/Write/Read Group 
3. Copy existing member DID.
4. Delete member by clicking Delete.
5. Add same member by pasting same member DID.
6. Delete member.
Now Demiurge Wallet Freeze and console shows error. Refer below screens.
7. Repeat step 4-5 and 6.
![Group-Member-Add-Delete-Add-Delete-Error](https://user-images.githubusercontent.com/82216409/206025621-ac82d803-db06-4f93-9f4d-51ec5a3fd2ac.JPG)
![Group-Demiurge-Admin-Member-Add-Delete-Add-Error](https://user-images.githubusercontent.com/82216409/206025629-9f4462ce-b06a-4d87-b9d0-b45c270fee90.JPG)

**Comment by skutner** [comment]
Resolved as part of #872
