### ISSUE TITLE
XML Converter

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#109]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
This is placeholder for the converter (word/ PDF -> XML) :

**Acceptance criteria's:**
**positive tests**

**negative tests / error path testing**

**Process scenario:**

**Additional information:**

**Comment by maherpa2** [comment]
@steinso2 @nhrishi we need to start to look at this user story

**Comment by nhrishi** [comment]
> @steinso2 @nhrishi we need to start to look at this user story

@steinso2 Do we have any sample pdf/word documents for leaflets. Thanks.

**Comment by rite2bala** [comment]
@nhrishi : Will this be a priority for MVP1 end of Dec 2021?

**Comment by maherpa2** [comment]
@rite2bala @nhrishi : This needs to be resolved, however I see it potentially as a service/ solution outside of the Enterprise Wallet. Ideally we would not need to convert from word to XML but in reality this functionality will be needed.
So yes  this needs to be done for MVP1 (end of 2021), but exactly where it will be done is to be decided.
