### ISSUE TITLE
App Scan Datamatrix with NHRN's

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#110]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the App and decoding in order to be able to scan additional Datamatrix codes which contain NHRN (National Healthcare Reimbursement Numbers:
- The ability to scan and decode a Datamatrix code which has NHRN's included:
![image](https://user-images.githubusercontent.com/58995303/109259604-d55c6c00-77fc-11eb-9f5a-3f0ebce1539f.png)
- The rules for decoding and finding the Anchor could be:
![image](https://user-images.githubusercontent.com/58995303/109260627-c7a7e600-77fe-11eb-81f4-1957a153ff04.png)
- The Datamatrix code could have up to 6 AI (Application Identifiers) included depending on the target market:
AI01 (GTIN)
AI21 (Serial Number)
AI10 (Batch Number)
AI17 (Expiry Date)
AI71x (NHRN - see table above)

**Acceptance criteria's:**
**positive tests**
- Scan the following barcodes and the Datamatrix code should be decoded and the ePI shown.
- Datamatrix code using <GS> and encoded in the order 01+21+10+17+710+714
![image](https://user-images.githubusercontent.com/58995303/109259958-89f68d80-77fd-11eb-992a-fa08dcc1fca5.png)
- Datamatrix code using FNC1 and encoded in the order 01+21+10+17+710+714
![image](https://user-images.githubusercontent.com/58995303/109260009-a692c580-77fd-11eb-931d-71b662426a77.png)
- Datamatrix code using FNC1 and encoded in the order 01+21+711+713+10+17
![image](https://user-images.githubusercontent.com/58995303/109260118-d772fa80-77fd-11eb-88f8-24eb5f175108.png)

**negative tests / error path testing**
- N/A

**Process scenario:**
- N/A

**Additional information:**
The App scan and decodes the barcodes and the ePI is shown.

**Comment by maherpa2** [comment]
This was tested and works as expected.

**Comment by suhailmax3888-crypto** [comment]
![Image](https://github.com/user-attachments/assets/505d4547-27e2-4d72-9373-7d3183a260bf)
