### ISSUE TITLE
App Scan non-Serialized Datamatrix Code

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#111]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the App and decoding in order to be able to scan and get the ePI for a non serialized Datamatrix code:
- The ability to scan and decode a GS1 Datamatrix code without an serial number
- Some markets do not have serialization but have a Datamatrix code with the GTIN, Batch and Expiry Date encoded.
![image](https://user-images.githubusercontent.com/58995303/109261723-8e707580-7800-11eb-905b-fbe331bab9b4.png)

- The Datamatrix has the following Application Identifiers:
AI01 (GTIN)
AI10 (Batch Number)
AI17 (Expiry Date)
- The rules for decoding could be:
![image](https://user-images.githubusercontent.com/58995303/109260991-72b89f80-77ff-11eb-9921-d93a7fbc3429.png)

**Acceptance criteria's:**
**positive tests**
- create a non-serialized batch. (refer to #100)
- create a GS1 Datamatrix with a correct GTIN, Batch and Exp Date details, when scanned this should provide the ePI.
- Code with GS used as the separator
![image](https://user-images.githubusercontent.com/58995303/109261772-a6e09000-7800-11eb-8428-1f5e534713f4.png)
- Code with FNC1 used as the separator
![image](https://user-images.githubusercontent.com/58995303/109261813-be1f7d80-7800-11eb-9f31-636494317b81.png)

**negative tests / error path testing**
- create a non-serialized batch. 
- create a GS1 Datamatrix with a correct GTIN, incorrect Batch and Exp Date details, when scanned this should not provide the ePI (refer to **ADD REFERENCE**)

**Process scenario:**
- The attached document gives an overview of the different barcodes that are commonly used. This is for information purposes only.
[Barcodes and Resolver v0.4.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6040776/Barcodes.and.Resolver.v0.4.pdf)

**Additional information:**
If a Datamatrix code with correct GTIN, Batch and Exp Date details is scanned with the current version then the following happens:
- on the Web App(using Edge):
![image](https://user-images.githubusercontent.com/58995303/109262354-ae546900-7801-11eb-8742-465a641928ce.png)

![image](https://user-images.githubusercontent.com/58995303/109262397-c2986600-7801-11eb-9b59-09651e320abe.png)

- on an IOS
![image](https://user-images.githubusercontent.com/58995303/109262928-a5b06280-7802-11eb-9298-b7447e2d2d34.png)
- It also seem to cause the App to crash but I could not re-create this. I am not reporting this as a bug because the system was only designed to ready serialized Datamatrix codes.

**Comment by mppub** [comment]
tested with for Scandit scanner library: everything works as expected
