### ISSUE TITLE
App Scan EAN-13 Code

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#112]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the App and decoding in order to be able to get the ePI when scanning an EAN-13 Code:
- A number of products on the market today are not serialized and have an EAN-13 code
![image](https://user-images.githubusercontent.com/58995303/109265070-3ccae980-7806-11eb-85f9-dae47f643951.png)

- The rules for decoding could be:
![image](https://user-images.githubusercontent.com/58995303/109265216-769bf000-7806-11eb-9627-d46d319d2709.png)

**Acceptance criteria's:**
**positive tests**
- create a non-serialized batch. (refer to #100)
- create an EAN-13 code with a correct information (GTIN-13). When scanned this should provide the ePI.

**negative tests / error path testing**
- create an EAN-13 code with a correct information (GTIN-13). When scanned this should provide the ePI.

**Process scenario:**
- Using the EAN-13 code does not provide the ability to any batch check, expiry date check etc. The reason for including it is that it would allow adoption of the solution as the EAN-13 is used across many products.
- The attached document gives an overview of the different barcodes that are commonly used. This is for information purposes only.
[Barcodes and Resolver v0.4.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6040776/Barcodes.and.Resolver.v0.4.pdf)

**Additional information:**
As a general rule, in order to create the GTN from an EAN-13 (GTIN-13) a leading 0 is added. So in the example above the EAN-13 is 7680669420017 so to convert to a GTIN-14 a leading 0 is added hence we get 07680669420017 as the GTIN-14.

**Comment by andrejstas** [comment]
Current open-source solution Xzing (https://github.com/zxing/zxing) is capable of scanning this barcode.

**Comment by mppub** [comment]
PR: https://github.com/PharmaLedger-IMI/leaflet-ssapp/pull/6/files
