### ISSUE TITLE
App Scan Serialized GS1-128 Code

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#113]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the App and decoding in order to be able to scan a GS1-128 1D code:
- The ability to scan and decode a 1D Code that has :
AI01 (GTIN)
AI21 (Serial Number)
AI10 (Batch Number)
AI17 (Expiry Date)

- The rules for decoding and finding the Anchor could be:
![image](https://user-images.githubusercontent.com/58995303/109267029-39852d00-7809-11eb-9702-90fec1e5e48a.png)

- Some sample codes:
![image](https://user-images.githubusercontent.com/58995303/109267238-8832c700-7809-11eb-9760-671dbe88ff76.png)

**Acceptance criteria's:**
**positive tests**
- Create a serialized Batch. 
- Encode the the correct GTIN, Serial Number, Batch Number and Lot.
- Scan the Code and the ePI should be shown.
- This is no different than when testing a Serialized Datamatrix code

**negative tests / error path testing**
- Create 1D codes with an incorrect Batch, Exp Date etc. Same negative tests as when testing a Datamatrix code.

**Process scenario:**
- N/A

**Additional information:**
The fact that the code is a 1D code or a Datamatrix code should not matter to the end user. Create a 1D code and a Datamatrix code with the same information and the end result must be the same i.e. the ePI is shown or the serial number etc. check passes/ fails.

**Comment by UnHynek** [comment]
- Not important at the moment
- Not used by the end users
- Used in logistics on pallets etc, not on drug box.

**Comment by andrejstas** [comment]
Current open-source solution Xzing (https://github.com/zxing/zxing) is **NOT** capable of scanning this code.

**Comment by mppub** [comment]
Code to print: https://barcode.tec-it.com/en/Code128?data=(01)05290931025615(10)VM3306(17)260831

**Comment by mppub** [comment]
Testing node: in theory the ZXing library is able to scan GS1-128 and uploading an image works, the issues comes with the length of the code - in order to put the gtin batch and expiry date the code is quite long and the camera of the opensource does not catch it.

Scandit should work.

**Comment by rite2bala** [comment]
Yet to test - Dependency on Scandit
