### ISSUE TITLE
Enterprise Wallet goes into infinite loop / Freeze when export empty audit csv 

### ISSUE THREAD

**Issue by RakeshL-JnJ** [PharmaLedger-IMI/epi-workspace#1136]
ePI version: 2023.0.1
Steps:
1. Create new Enterprise Wallet user.
2. Go to Audit. ( It should be empty)
3. click on export as CSV. 
4. It shows dialogue and remains there only. Refer below screen shot:
![ew_Audit_ExportCSV_norecord](https://user-images.githubusercontent.com/82216409/208964529-e863d04e-c5e5-4cfc-af71-fb668406db90.PNG)

**Comment by adiganga2002** [comment]
search/export ui container will be hidden for no data
