### ISSUE TITLE
App Scan non-Serialized GS1-128 Code

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#114]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the App and decoding in order to be able to scan a GS1-128 1D code:
- The ability to scan and decode a 1D Code that has :
AI01 (GTIN)
- The ability to scan and decode a 1D Code that has :
AI01 (GTIN)
AI17 (Expiry Date)
AI10 (Batch Number)

- The rules for decoding and finding the Anchor could be (Barcode only has AI01):
![image](https://user-images.githubusercontent.com/58995303/109268368-4440c180-780b-11eb-8208-bb7142d0f735.png)
- The rules for decoding and finding the Anchor could be (Barcode has AI01, AI17, AI10):
![image](https://user-images.githubusercontent.com/58995303/109268737-cc26cb80-780b-11eb-98e2-20bc58f6c180.png)

- Some sample codes (Barcode only has AI01):
![image](https://user-images.githubusercontent.com/58995303/109267998-b7960380-780a-11eb-9f5f-534618cfb08b.png)

**Acceptance criteria's:**
**positive tests**
- Create a non-serialized Batch (refer to #100). 
- Encode the the correct GTIN in the GS1-128 code.
- Scan the Code and the ePI should be shown but no batch number or expiration date would be shown.

- Create a GS1-128 code that has GTIN, Batch, Exp encoded. 
- Scan the code and the ePI should be shown along with the Batch Number and Expiration Date.

**negative tests / error path testing**
- Create GS1-128 code with an incorrect GTIN and the ePI should not be shown.
- Create a GS1-128 code that has GTIN, Batch, Exp encoded. The Exp date is incorrect. The system should detect this.

**Process scenario:**
- Using the GS1-128 code with only a GTIN does not provide the ability to any batch check, expiry date check etc. 

**Additional information:**
N/A.

**Comment by andrejstas** [comment]
Current open-source solution Xzing (https://github.com/zxing/zxing) is capable of scanning this barcode.
