### ISSUE TITLE
Fix CORS issue in APIHUB

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#1143]
Refactor responseHeader middleware to set headers for specific paths

**Comment by asaccool** [comment]
check the list of allowed headers to include some needed headers like epiprotocolversion and others

**Comment by jaravan1** [comment]
related with https://github.com/PharmaLedger-IMI/epi-workspace/issues/1107

**Comment by salboaie** [comment]
Solution:
each component that inserts require custom headers will have a way to register them so the CORS component is capable to get a correct answer without additional configurations
