### ISSUE TITLE
App and DSU Supported Characters

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#115]
**PL user story:**

**Description:** 
The App and the DSU need to be able to manage the following characters as per the GS1 General Specification.
![image](https://user-images.githubusercontent.com/58995303/109269545-eb722880-780c-11eb-8275-b2d2ea5223c7.png)
![image](https://user-images.githubusercontent.com/58995303/109269561-f3ca6380-780c-11eb-830b-efc7a0618fe0.png)

- Sample Codes
![image](https://user-images.githubusercontent.com/58995303/109271572-ff6b5980-780f-11eb-9ee4-3acfcd9928f4.png)

**Acceptance criteria's:**
**positive tests**
- Create a batch and serial numbers with special characters.
- Scan the Datamatrix code and get the ePI.

**negative tests / error path testing**
- N/A

**Process scenario:**
- N/A

**Additional information:**
Refer to the GS1 General Specification for addition details.

**Comment by andrejstas** [comment]
- It is possible to create a product with product code like **!%*=&"?-+<.!** and create a batch with a standard  batch number (e.g. TK1213). 🟢 

- t is possible to create a product with a standard product code (07612797343838 ) and create a batch with batch ID like **!%*=&"?-+<.!**. 🟢

However, when trying to **create a 2D Data Matrix** for any of these two products, there's an error. 🔴 

`Uncaught SyntaxError: Unexpected token ? in JSON at position 75
    at JSON.parse (<anonymous>)
    at batchesController.js:45
    at HTMLElement.r (:8080/webcardinal/components/webcardinal-core/p-8219f559.js:1)`

<img width="2032" alt="Screenshot 2021-04-08 at 12 14 15" src="https://user-images.githubusercontent.com/676786/114010879-e15c3480-9864-11eb-9879-eee32b864de0.png">

**Comment by maherpa2** [comment]
@andrejstas The Product Code (GTIN) is always numeric. As a general rule all batch numbers are alphanumeric/ numeric, so A-Z and/or 0-9. Most companies would not use a Batch Number with special characters as it would be difficult for the patient to read. However serial numbers could be using these special characters (most companies only use a-z, A-Z and 0-9). The Russian Code does contain/ could contain these special characters.

The following barcode has : 
GTIN = 07612797343838
Batch = !%*=&"?-+<.!   
Serial Number = 43023992515022
Expiry Date = 240623
This would most likely not be a realistic barcode that a company would produce, but in theory it is perfectly fine.
![image](https://user-images.githubusercontent.com/58995303/114023780-9564bc00-9873-11eb-94e2-e278ff0e2c95.png)

This Code is probably more realistic:
GTIN = 07612797343838
Batch = ABC112 
Serial Number = ';'%::*,<!=+)))+%
Expiry Date = 240623
![image](https://user-images.githubusercontent.com/58995303/114025665-a8788b80-9875-11eb-830a-9c6f8d4560ff.png)
