### ISSUE TITLE
GS1 Digital Link Integration

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#117]
**PL user story:** 

**Description:** 
- Integration the GS1 Digital Link into the Resolver.
- If the GTIN+Batch / GTIN Anchor cannot be resolved then the solution should use the GS1 Digital Link.
- **Details of the GS1 endpoint to be provided by GS1.**
- Flow would be as follows:
![image](https://user-images.githubusercontent.com/58995303/109544901-64e96f80-7ac8-11eb-9f3e-0c027c18fedf.png)

**Acceptance criteria's:**
**positive tests**
- Create a Product using the DSU Fabric and an associated batch.
- Scan the barcode and the leaflet is provided from the Brick storage
- Create a barcode with a GTIN and batch that has no associated anchor on the ePI Blockchain.
- Ensure this GTIN is maintained on the GS1 end point look up table.
- Scan the barcode and the solution should be directed to the Digital Link for resolution.

**negative tests / error path testing**
N/A

**Process scenario:**
- In order to make it easier for adoption and still allow patients/ end users to use one app then integration to GS1 Digital Link would allow easier adoption across the eco system.

**Additional information:**
This user story needs to be built out further in alignment with GS1.

**Comment by UnHynek** [comment]
Low priority before release 1.
The idea is to create the connection and test if the library works and we can use it (so it can be used as a backup plan).
