### ISSUE TITLE
Batch no rejects special characters such as "-"

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#1178]
I don't know if this becomes an issue but creating a batch e.g. S001-02 is rejected by the EW

Investigation needed if any company has such characters. 
The Batch field was specified as alphanumeric 20 and should allow:
000000001
12345
ABC-001
abcdef
abcdef-10
....

**Business decision needed** if this needs to be fixed or not

**Comment by salboaie** [comment]
1. Is this for MVP1? 
2. We will stop using this repository, issue should be created in Jira
