### ISSUE TITLE
Error expected when leaflet XML is incorrect

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#1181]
I tested this scenario using 
<document **hello**="pharmaledger-1.0">
instead of: 
<document **type**="pharmaledger-1.0">

No error message was given, after scanning barcode the product description was shown with a blank screen instead of leaflet or error message.

In MVP1 we can test all used product leaflets to avoid such situation but later?!?
Either we validate the XML when uploading or during saving or we get an error message on mobile screen.

**Comment by salboaie** [comment]
1. Is this for MVP1? 
2. We will stop using this repository, issued should be created in Jira
