### ISSUE TITLE
App Decoding Enhancement

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#122]
**PL user story:** 

**Description:** 
- I am using an iPhone 8 software version 14.4
- The App does not detect nor decode the following barcodes which are laser etched. However using the same phone and using the GI 4.0 App or the SCANDIT App then the codes are read,. So it is not an issue with the camera on the iPhone.

- ![IMG_0059](https://user-images.githubusercontent.com/58995303/110209579-9ded5f80-7e8d-11eb-85c0-89f61dc8810d.jpg)

- ![IMG_0060](https://user-images.githubusercontent.com/58995303/110209581-9fb72300-7e8d-11eb-9cac-1f4d963934af.jpg)

- ![IMG_0061](https://user-images.githubusercontent.com/58995303/110209586-a0e85000-7e8d-11eb-8937-38cf008af0c5.jpg)

- ![IMG_0062](https://user-images.githubusercontent.com/58995303/110209590-a2b21380-7e8d-11eb-9028-28999edc9255.jpg)

- ![IMG_0057](https://user-images.githubusercontent.com/58995303/110209593-a47bd700-7e8d-11eb-90e1-72506cc9c555.jpg)

- ![IMG_0058](https://user-images.githubusercontent.com/58995303/110209597-a6de3100-7e8d-11eb-8bb1-ee0615dcde21.jpg)

- The Datamatrix codes are approx. 10mm x 10mm and are properly encoded.

**Acceptance criteria's:**
**positive tests**
- Able to scan and decode the attached Datamatrix codes in less than 1 second.

**negative tests / error path testing**
N/A

**Process scenario:**
- The ability to read barcodes printed with different technologies is required.

**Additional information:**
Suggest to reach out to the SCANDIT and use their SDK as it can also read the composite code (refer to #101) in less than 1 second, same with the barcodes attached here.
@nhrishi @UnHynek @salboaie @steinso2

**Comment by andrejstas** [comment]
Current open-source solution Xzing (https://github.com/zxing/zxing) is **NOT** capable of scanning this code.
