### ISSUE TITLE
App Scan Code 128 C Barcode (China EDMC Code)

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#123]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the App and decoding in order to be able to scan a  Code 128 bar code:
- The ability to scan and decode a Code 128C 1D Code that has the China EDMC encoded. This is a 20 digits long code that only contains numeric digits.
![image](https://user-images.githubusercontent.com/58995303/110211808-9b443780-7e98-11eb-84ca-3b006576b323.png)

- EDMC = Electronic Drug Monitoring Code

- The rules for decoding and finding the Anchor could be:
Take the first 7 digits of the code in order to find the Anchor. The first 7 digits are the Product Code which identifies the company.

- Some sample codes:
- ![IMG_0065](https://user-images.githubusercontent.com/58995303/110211995-8d42e680-7e99-11eb-9515-90e451a2d647.jpg)

- ![IMG_0066](https://user-images.githubusercontent.com/58995303/110212349-3d651f00-7e9b-11eb-986e-daaa108a612f.jpg)

**Acceptance criteria's:**
**positive tests**
- Create a serialized Batch. 
- Encode the EDMC number in the Code 128 C code
- Scan the 128 C barcode in order to find the anchor and display the ePI.

**negative tests / error path testing**
- Create a serialized Batch. 
- Encode an incorrect EDMC number in the Code 128 C code (incorrect = unknown Product Code)
- Scan the 128 C barcode and a message should be displayed to the patent.

**Process scenario:**
- N/A

**Additional information:**
For serialization China is using the Code 128 C barcode and the 20 digit EDMC code is encoded. The ability to decode this and provide an ePI and all the Anti counterfeit checks will be of additional value. T**his also implies an update on the DSU Fabric in order to be able to manage this code as it is not GTIN based (refer to #124)**.

**Comment by andrejstas** [comment]
Current open-source solution Xzing (https://github.com/zxing/zxing) is capable of scanning this barcode.

**Comment by andrejstas** [comment]
Current open-source solution Xzing (https://github.com/zxing/zxing) is capable of scanning this barcode.
