### ISSUE TITLE
GSK Bug: Analyse and fix what the wallet get  corrupted in that case

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#125]

**Comment by salboaie** [comment]
Details in the email

**Comment by skutner** [comment]
When a new installation is made, the brick storage is deleted, but the anchoring service is not changed. As a result, the anchors for previously created ProductDSUs remain in the anchoring service and when trying to create a product with the same GTIN that was already used the anchoring service throws an error (even though the list of products in dsu-fabric-ssapp appears empty).

**Comment by rite2bala** [comment]
Issue is closed. Product code was scanned after the data was deleted.
