### ISSUE TITLE
Technical error message to app user

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#127]
When the leaflet is not available for the given product, the mobile app displays the technical error to the user. Attached screenshot.

<img width="1360" alt="Screenshot 2021-03-08 at 2 34 17 PM" src="https://user-images.githubusercontent.com/16893108/110299193-64e2f580-801b-11eb-8e3f-40c3e52cf80b.png">

**Comment by maherpa2** [comment]
@nhrishi just a question to the tech team: would it be technically possible to detect this issue when uploading the leaflet/ SmPC and to inform the user at that point. Detecting it after scanning the code is a bit late, right? Similar to #128 - don't allow the system to create use something that is incorrect.

**Comment by nhrishi** [comment]
> @nhrishi just a question to the tech team: would it be technically possible to detect this issue when uploading the leaflet/ SmPC and to inform the user at that point. Detecting it after scanning the code is a bit late, right? Similar to #128 - don't allow the system to create use something that is incorrect.

**Comment by nhrishi** [comment]
> @nhrishi just a question to the tech team: would it be technically possible to detect this issue when uploading the leaflet/ SmPC and to inform the user at that point. Detecting it after scanning the code is a bit late, right? Similar to #128 - don't allow the system to create use something that is incorrect.

Yes I agree, we can discuss this in our Wed's meeting.

**Comment by rite2bala** [comment]
When the leaflet is missing - The icon doesn't appear anymore - hence closing the issue

**Comment by salboaie** [comment]
Not relevant anymore, still keeping for QA feedback
