### ISSUE TITLE
DSU Fabric GTIN Check

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#128]
**PL user story:** 

**Description:** 
Update the DSU Fabric to include a check to ensure the check Digit of the entered GTIN is correct. This Should be done when creating the product.
- It is to be determined when this check is performed. If it is done when the user presses Save product then all the other data entered should remain in place i.e. picture of the product, leaflet/ SmPc etc. and the GTIN corrected.

- The System will allow barcodes to be produced even though the check digit is incorrect. When the person scans the Datamatrix code then they get an message stating it is not readable.
![image](https://user-images.githubusercontent.com/58995303/110597432-d7b9b100-8180-11eb-8398-b1d5111fac38.png)

![image](https://user-images.githubusercontent.com/58995303/110597461-e0aa8280-8180-11eb-90bc-615971e8430a.png)

**Acceptance criteria's:**
**positive tests**
- Create a GTIN with an incorrect check Digit. The system will detect this and indicate the issue to the user.

**negative tests / error path testing**
- N/A

**Process scenario:**
- N/A

**Additional information:**
N/A.
@UnHynek your colleague Clement had this issue hence why the request is being raised.

**Comment by rite2bala** [comment]
The GTIN can be 8, 12, 13,14 digits long. Currently the mobile app is only able to scan the 14 digit GTIN 

https://www.gtin.info/ -- The website gives the various GTIN format available in the market currently. 
We have to allow the app to scan the other lengths also. 

For details of the check digit calculation please refer to the below link :
https://www.gs1.org/services/how-calculate-check-digit-manually

**Comment by rite2bala** [comment]
@skutner , @salboaie,  @asaccool : need your comments about the implementation of this feature item.
