### ISSUE TITLE
DSU Fabric design update

### ISSUE THREAD

**Issue by adiganga2002** [PharmaLedger-IMI/epi-workspace#134]
Update DSU fabric design (see attachment)
![image](https://user-images.githubusercontent.com/38322305/111596582-fdc10000-87d5-11eb-9811-8acf6507128b.png)
![image](https://user-images.githubusercontent.com/38322305/111596648-0c0f1c00-87d6-11eb-8a72-7476c1805fc9.png)
![image](https://user-images.githubusercontent.com/38322305/111596725-2517cd00-87d6-11eb-8801-63910a27fd5a.png)

**Comment by salboaie** [comment]
Also migrate to the new version of cardinal

**Comment by adiganga2002** [comment]
Hi @rite2bala, can you give more information about Patient Specific Information Leaflet and Healthcare practitioner information fields? Are this just simple text inputs or somehow related to uploaded leaflet/smpc?

**Comment by rite2bala** [comment]
Hello @adiganga2002  These are simple text fields used to provide alternate names for the corresponding icons on the mobile app. Default values will be "Patient Information" and "SmPC". 

At the moment these are not related to the leaflet /SmPC.
