### ISSUE TITLE
Bugs for #90 - DSU Fabric Serial Number & Exp Date Checks Enable/ Disable

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#135]
User Story #90 
1. Manage Product screen, the radio buttons do not work properly - cannot choose yes in both  expiry date check 

2. Edit Batch screen - check boxes are checked by default even if the feature was disabled at the product level 

 Noted that the  serial numbers  entered previously are not visible (agreed that it will be the case   - we will not be able to view it )

**Comment by steinso2** [comment]
3. batch screen: even the SN check on the batch level was deactivated, the Serial number is still checked on mobile.
4. batch screen: not a QR code is scanned, so please change the text:
![image](https://user-images.githubusercontent.com/78138966/111636928-3920f600-87f9-11eb-8ff8-045581316320.png)
Please differentiate QR code from datamatrix code. Its really not the same. 
5. There is no good way to leave the batch detail screen when nothing was changed
