### ISSUE TITLE
#89 DSU Fabric - Batch Creation add Product Description

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#136]
AI 21 is included in the code when no serial numbers are entered. 

The difference in the code currently generated and the code expected can be noted by scanning the code from the story on the URL:

https://gs1.github.io/interpretGS1scan/camera.html

**Comment by rite2bala** [comment]
2. The batch creation doesn't happen if the version of the leaflet is not explicitly clicked

**Comment by skutner** [comment]
Fixed
