### ISSUE TITLE
#100 App Scan non-Serialized Datamatrix Code

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#138]
Extra error message on mobile app screen when serial  number is left blank.

**Comment by adiganga2002** [comment]
Hi @rite2bala, can you please attach a print screen with this Extra error message and steps to reproduce ?

**Comment by maherpa2** [comment]
@adiganga2002 @rite2bala when producing a non-serialized batch then the Datamatrix code would have GTIN (AI01), Batch (AI10)Number, Expiry Date (AI17). The code **would not** have the serial Number (AI21). A code that I saw had AI21 and it had a value of 0. This is incorrect as AI21 should not be in the code at all. If clarification is needed then please reach out to me.

**Comment by rite2bala** [comment]
Hello @adiganga2002 

Please ignore the issue regarding extra error message for now. I am unable to reproduce the error. 

As per the comments mentioned in the  https://github.com/PharmaLedger-IMI/epi-workspace/issues/111 . There are three data matrices in the description. All three of the data matrices, do not have AI21 Serial number. 

I created a sample code using the app on epiqa and scanned using gs1 data matrix scanner  
![image](https://user-images.githubusercontent.com/44022980/111954713-86a9a580-8b0e-11eb-8063-9f17270acdc9.png)

Result:
Raw output:
<GS>0108977671235739210<GS>10ZK2191<GS>17210324
Interpretation:
GS1 identifiers
01	GTIN		08977671235739
10	BATCH/LOT		ZK2191
**21	SERIAL		0**
17	USE BY OR EXPIRY		2021-03-24

Equivalent identifiers
Human-readable AI syntax	(01)08977671235739(17)210324(10)ZK2191(21)0
Native AI syntax	01089776712357391721032410ZK2191210
GS1 Digital Link URI	https://id.gs1.org/01/08977671235739/10/ZK2191/21/0?17=210324


The Serial Number must not be a part of the code.

**Comment by rite2bala** [comment]
Just noticed that Patrick has also posted similar screenshot on the story #111 

https://user-images.githubusercontent.com/58995303/109262928-a5b06280-7802-11eb-9298-b7447e2d2d34.png

"It also seem to cause the App to crash but I could not re-create this. I am not reporting this as a bug because the system was only designed to ready serialized Datamatrix codes.

**Comment by rite2bala** [comment]
![image](https://user-images.githubusercontent.com/44022980/112958450-1af3b800-9160-11eb-9d96-236a05e6b0c4.png)


Hello @adiganga2002 @skutner 
I was able to reproduce the error by scanning the above datamatrix code. 
This was an old code created prior to the deployment.

The error appears differently in iOS and in Android . 

Could you please check?

cc: @nhrishi

**Comment by nhrishi** [comment]
I tested this today again for the below code in eqiqa environment. I got the same error for the new product and batch.

https://barcode.tec-it.com/en/DataMatrix?data=(01)28888388884889(17)210430(10)KB9261

<img width="1680" alt="Screenshot 2021-04-16 at 3 55 15 PM" src="https://user-images.githubusercontent.com/16893108/115011741-a1342c00-9ecc-11eb-99db-0b3d35acf97b.png">

**Comment by maherpa2** [comment]
@nhrishi that Datamatrix code you gave the link to is not encoded correctly.

**Comment by rite2bala** [comment]
I created a similar code as Hrishikesh and observed that I do not receive the error:
https://barcode.tec-it.com/en/DataMatrix?data=(01)23332255466678(17)210430(10)RL0137

**Comment by skutner** [comment]
Hi @nhrishi @rite2bala . Is this still a bug or we can close this issue?

**Comment by mppub** [comment]
Just tested for the Scandit library, it works as expected for all above mentioned codes(the ones in comments included)

**Comment by mppub** [comment]
@rite2bala this issue shall be resolved soon - can we close it already? if there are any more problems with it please create a new bug from it and lets tackle it separately thank you

**Comment by rite2bala** [comment]
Current understanding: A non-serialized batch is one where valid serial numbers are not uploaded. It is not any explicit setting to indicate batch is non-serialized.

Case 1
1.	Since we are testing a non-serialized batch. We created a batch where serial number check was disabled. 
![image](https://user-images.githubusercontent.com/44022980/117416992-8be47780-af37-11eb-95cf-77d099381be6.png)

2.	We created a 2d matrix without serial number i.e. without (21) tag:
https://barcode.tec-it.com/en/DataMatrix?data=(01)09812376129473(17)240524(10)RV5163

3.	When the above code is scanned – an error appears on the mobile app and ePI is not displayed.


Case 2
1.	For a non-serialised batch – We create a 2d matrix with test serial number (any number after 21 tag) 
https://barcode.tec-it.com/en/DataMatrix?data=(01)09812376129473(17)240524(10)RV5163(21)1231

2.	It works fine - because the serial number check is disabled and we are supplying an invalid serial number.

Observation:
The current scanner is unable to interpret data matrix without 21 tag.

**Comment by rite2bala** [comment]
@mppub  This issue will have to remain in QA testing as it is not resolved yet. 
Please let me know if you are able to reproduce the error or you see any discrepancy in my approach. 

Thank you.

**Comment by rite2bala** [comment]
hi @mppub We were able to test only now because we got a stable interface without critical errors. 
This error would have to remain in QA stack until fixed. 

Please do let me know if you were able to reproduce the error or need any additional explanation or would like to correct my testing approach.

Thank you.

**Comment by rite2bala** [comment]
1. Create a non serialised batch
2. Scan the data matrix -
**Result:** Data matrix doesn't contain serial number
	 
3. Add valid serial number to the same batch
4. View data matrix 
**Result:** Data matrix contains the updated serial number
	 
5. Update the batch and remove all updated serial numbers
6. Scan data matrix generated from the tool -
**Result:**  Data matrix code generated by the enterprise wallet still contains serial number (Bug)? 
  When the above code (with the serial number) is scanned , the serial number check fails (and that is the expected behaviour)
	 
7. Scan the code generated on step 2. 
	**Result**: Serial number error still shows up (Bug!)
	
	**Expected output at step 7-** 
	When valid serial numbers are cleared, and a data matrix without serial numbers are scanned - it must not show
