### ISSUE TITLE
XML read Error

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#141]
We have a few XML that are not being read correctly by the interpreter. 

These XML were prepared/received as a part of the Singapore  trials.

Please let us know if this is an issue with the XML or with the Interpreter.

Please please refer to attachment containing the individual XMLs
[Problematic leaflet.zip](https://github.com/PharmaLedger-IMI/epi-workspace/files/6169675/Problematic.leaflet.zip)

**Comment by rite2bala** [comment]
Hi team, 

We have been able to investigate further and note that the issue is being caused by some special characters in the file 

We used notepad ++ to remove all unwanted blanks and spaces -- and then used VS Code to reformat the document and save it. 

Currently we have two visibly same documents - one works , while the other doesnt 

Please refer to the attachment for the same. 

[LeafletIssue.zip](https://github.com/PharmaLedger-IMI/epi-workspace/files/6171508/LeafletIssue.zip)

The leaflet that works fine is uploaded to the  "Patient Information" section and the file that doesnt work fine is uploaded to "SmPC" Section  in the below product code in UAT environment:

![image](https://user-images.githubusercontent.com/44022980/111790746-892ab600-88e8-11eb-83fe-480db0da7a3d.png)

May I request that there be a hotfix in the XML interpreter to make it immune to file formatting errors?

Thank you.

**Comment by asaccool** [comment]
My research regarding this bug is showing that there is a small issue into our form data parser not into the XML interpreter.
To confirm this idea check the network tab available in dev console and take a look at the content read from dsu when trying to display the leaflet. You should find that the content of the leaflet is partial and thus why the display process fails.

Currently trying to find a good fix for the form data parser to take notice that some lines from the files can contain \r and \n in different configurations.

**Comment by maherpa2** [comment]
@asaccool @rite2bala do we have a solution and a timeline for the deployment of the solution ?

**Comment by asaccool** [comment]
@maherpa2 @rite2bala i have made and pushed a new form data parser to prevent situations like this. It will be available for testing in one or two days when a new freeze version will be published.

**Comment by asaccool** [comment]
@maherpa2 i done tests with the attachment from Bala's email.  I have done tests with different file types and seems that we have now a stronger implementation. Also once the fix will be available i trust Bala will test it properly.

**Comment by rite2bala** [comment]
@asaccool Thank you!

**Comment by rite2bala** [comment]
Tested with different XML formats. Error doesn't recur.
