### ISSUE TITLE
Password miss match error message missing

### ISSUE THREAD

**Issue by UnHynek** [PharmaLedger-IMI/epi-workspace#142]
**Reproduction steps**
1) Click on button "Enterprise wallet"
2) Click on button "New Account"
3) Write miss matching password to "Confirm your password" field

<img width="1545" alt="Screenshot 2021-03-19 at 11 17 06" src="https://user-images.githubusercontent.com/6213340/111765840-22d07400-88a5-11eb-9f02-541c9e5ba89b.png">

**Outcome**
Nothing happened, I would expect error message informing that the passwords not matching.

It is no a critical feature, but in terms of adoption it is nice to have.

**Comment by rite2bala** [comment]
The error message appears highlighted in red. Moving to UAT.
