### ISSUE TITLE
Failing to create product

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#146]
**Description**
After details of the product is entered and "Save Product" is clicked upon, following screen is displayed. 
<img width="1185" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/77785937/112291271-3fe3b900-8c90-11eb-96a0-5dea39d617a6.png">

**Acceptance Criteria**
When "Save Product" is clicked
1. Notify user that product has been created successfully
2. System creates a Datamatrix code with the GTIN, serial number, batch number & an expiry date. 

**Environment**
Google Chrome (latest) on Macbook

**Prerequisites**
Logged into the system
**Reproduction steps**
1. Click on "Add Product" and Enter the product details
2. Click on "Add ePI" and upload the xml file downloaded from the [dailymed](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9333c79b-d487-4538-a9f0-71b91a02b287) website
3. Click on "save product"

**Comment by rite2bala** [comment]
This issue occurs when the GTIN is already used (/anchored). Please use a new & valid GTIN. 
https://www.gs1.org/services/check-digit-calculator

**Comment by nhrishi** [comment]
@amanuel95  @UnHynek  Is this still an issue

**Comment by rite2bala** [comment]
Moving to UAT
