### ISSUE TITLE
Skins: User view & Full view

### ISSUE THREAD

**Issue by UnHynek** [PharmaLedger-IMI/epi-workspace#148]
-- draft -- 

**Story**: There is a need to make simplified screen view. Considering potential patients the app should display minimum informations and minimize confusion.

**Task**: 

1) 
- Combine the 3 "authentication" checks into one icon "Authentication Status". 
- If all are okay, make it green with a tick.
- If any item is not okay, make it either amber or red and display appropriate message depending on what items fails.

<img width="556" alt="Screenshot 2021-03-24 at 15 58 01" src="https://user-images.githubusercontent.com/6213340/112332218-d7113680-8cb9-11eb-92b8-2235c75a3318.png">

**Comment by maherpa2** [comment]
@UnHynek as discussed yesterday, does the following help clarify?

![image](https://user-images.githubusercontent.com/58995303/112421904-49bcf900-8d30-11eb-9f3b-f771fe0a47e7.png)

- Whether we simply have a Green/ Red check mark without any text or if we include "Authentication Status" or "Verification Status" etc. is something that can be discussed. Perhaps a Red or Green check mark may suffice but this really needs to be assessed by UX experts and taking into consideration different countries/ regions.

- To be discussed if we should remove the details as to why the Symbol is Green or Red i.e. do we really want to/ need to show the Serial Number, Product Status (name needs to change) and Package Verification icons. If the check mark is Red then the patient could (if they so wished) get more information as to why it is red. An alternative would be to just press the check mark if it was red and then have a reason why the check mark is red. The tech team need to assess the effort required for the different possibilities. All of this needs to be considered as part of the UX over haul, which will be a different activity.

![image](https://user-images.githubusercontent.com/58995303/112422026-8688f000-8d30-11eb-965a-b39fd87931d0.png)

- The following 2 screen shots show the Happy Path:

![image](https://user-images.githubusercontent.com/58995303/112422266-e2537900-8d30-11eb-9b31-1751fb914451.png)

![image](https://user-images.githubusercontent.com/58995303/112422301-f0a19500-8d30-11eb-9500-ac2891c954c4.png)


- The following 2 screen shots show the Un-happy Path:

![image](https://user-images.githubusercontent.com/58995303/112422416-23e42400-8d31-11eb-94b2-74ec6a9e1168.png)

![image](https://user-images.githubusercontent.com/58995303/112422434-2cd4f580-8d31-11eb-8acd-ebd7e413bbff.png)


- The way the "Add to Cabinet" button is shown is far from ideal. Consideration should be given to having some way of enabling/ disabling this or at least aligning it with the icons that are on the screen.  When everything is enabled then it does not look that bad. As stated previously, all of this needs to be considered as part of the UX over haul, which will be a different activity.


- The following shows the Happy Path when everything is enabled, in this case the icons would not be greyed out:

![image](https://user-images.githubusercontent.com/58995303/112422719-9bb24e80-8d31-11eb-9350-da4561e14d57.png)

- The attached excel file has the different combinations as to which symbol should be displayed. This needs to be reviewed by the Tech team to ensure the combination are correct.

![image](https://user-images.githubusercontent.com/58995303/112423294-a15c6400-8d32-11eb-9e04-059de220c88d.png)

[Serial Number Exp Date Check Proposal v0.4.xlsx](https://github.com/PharmaLedger-IMI/epi-workspace/files/6202226/Serial.Number.Exp.Date.Check.Proposal.v0.4.xlsx)

@steinso2 @nhrishi @rite2bala @andrejstas @salboaie @thursbyk for your information and input.
