### ISSUE TITLE
Bug: Mobile app display changes

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#151]
**Description**
It is observed that when the app encounters a situation where the product information need not be displayed, then the mobile app displays  only one icon titled "Add to cabinet."

![image](https://user-images.githubusercontent.com/44022980/112451341-6599bc80-8d7b-11eb-9db1-6d382acabd8c.png)

From the UX perspective, there can be more things that can be done to help the patient in this situation.

**Acceptance Criteria**
 New UX

The layout we had earlier , had additional icons for report , add to cabinet, verify package. These have been removed now.
Was it a part of plan to remove?
![image](https://user-images.githubusercontent.com/44022980/112432045-4d6b7280-8d66-11eb-8d54-b4ddbfa0d2e6.png)

**Environment**
Google Chrome (latest) on Macbook

**Prerequisites**
Logged into the system
**Reproduction steps**
A product is uploaded with the following settings:
1. Product settings:
![image](https://user-images.githubusercontent.com/44022980/112431268-498b2080-8d65-11eb-80a8-e7da68c2d55c.png)
2. Batch Settings:
![image](https://user-images.githubusercontent.com/44022980/112450783-c1b01100-8d7a-11eb-995a-b0e6d3360568.png)

The following data matrix code is generated:
![image](https://user-images.githubusercontent.com/44022980/112450835-cffe2d00-8d7a-11eb-9627-aa0284bc7ec4.png)

**Comment by skutner** [comment]
Hi @rite2bala . In development we tried to met the requirements presented in the attached image and this is the reason that we have changed the client application. This image is from https://github.com/PharmaLedger-IMI/epi-workspace/files/6028518/App.and.DSU.Fabric.Feedback.v0.2.pdf
Nevertheless, we have found a bug in the client application regarding the Enable AntiCounterfeiting and Enable Report Adverse events flags, that has been fixed. 
![Screenshot from 2021-03-25 15-08-57](https://user-images.githubusercontent.com/35995331/112499001-badfc900-8d8f-11eb-91fc-49f74b818dee.png)

**Comment by rite2bala** [comment]
App works as expected after the settings are made to apply by default. 

Moving to UAT.
