### ISSUE TITLE
App has to be restarted when the product and batch are updated in the meantime.

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#156]
**Description**
When the details of the product/batch are to be edited and PWA is open in the browser, the app doesn't pull the latest data/configs on the next product scan. It continues to show the data/behaves based on the older product/batch settings and works accordingly.

Acceptance Criteria
If the user changes any data/config on the product/batch, the PWA/native mobile app doesn't need to be restarted and it should pull and show the latest data/behave based on the latest config without the need for a restart.

Prerequisites and Reproduction steps

1. Setup a new product and batch in the Enterprise wallet.
2. Scan the 2D matrix for the given product, PWA/native mobile app should display the details
3. Change the product/batch setting and update the Enterprise wallet without closing PWA/native mobile app
4. Scan the 2D matrix for the same product again, the changes wouldn't reflect on the apps.

**Comment by rite2bala** [comment]
The changes reflect almost immediately except for the non serialized batches case where the bloom filter is malfunctioning. 

We tested over 20 use cases today and all worked positively. 
However, the app fails to work when we use the ePI mobile app and ePI enterprise wallet app in two tabs of the same device.  The service workers interfere between each other. Often, this leads to log out of the Enterprise wallet app.
However, this is to be tackled in different ticket. 

The issue mentioned in this ticket is resolved. 

cc: @nhrishi  to decide if it can move to UAT.
