### ISSUE TITLE
PWA doesn't show the reason code properly for the decommissioned serial number chek

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#163]
Description - When a product/batch with decommissioned serial number is scanned. The PWA does show that the serial number is decommissioned but doesn't show the reason code correctly.

<img width="413" alt="Screenshot 2021-04-15 at 9 28 25 PM" src="https://user-images.githubusercontent.com/16893108/114900870-e5beb980-9e31-11eb-9650-af363e39b7c7.png">

Acceptance Criteria
The reason code on the decommissioned serial number should be displayed correctly.

Prerequisites and Reproduction steps

1. Setup a new product and batch in the Enterprise wallet.
2. Update the batch with decommissioned serial number with specific reason code, enable the serial number verification.
2. Scan the 2D matrix for a decommissioned serial number, the PWA does show decommissioned serial number but doesn't show reason code.

**Comment by rite2bala** [comment]
We select the reason code and scan the appropriate decommissioned serial number. The correct reason code is visible on the mobile app. 
Moving to UAT.
