### ISSUE TITLE
eLeaflet update on the existing product doesn't work

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#165]
Description
When a user wants to upload a new version of eLeaflet, the enterprise wallet is throwing an error "Failed to execute Command".
Here are screenshots -
<img width="1680" alt="Screenshot 2021-04-16 at 10 58 41 AM" src="https://user-images.githubusercontent.com/16893108/114976278-5651ee80-9ea3-11eb-8481-d335567c0729.png">
<img width="1680" alt="Screenshot 2021-04-16 at 10 58 48 AM" src="https://user-images.githubusercontent.com/16893108/114976287-581bb200-9ea3-11eb-902c-b39bd4cfd322.png">

Acceptance Criteria
User should be able to upload new versions of eLeaflet on the product 

Steps for reproducing the issue- 
1. Select an existing product with the initial version of eLeaflet
2. Edit the product
3. Delete the current version of Leaflet (using cross sign)
4. Click on Add ePI, select new files
5. Hit the Update product button.

**Comment by rite2bala** [comment]
Its not just the e-leaflet update - Whenever we try to update the product "Display ePI when" flags also it fails to update.

**Comment by rite2bala** [comment]
This issue is resolved in the QA environment. We could move this to UAT.
