### ISSUE TITLE
Product update doesn't work

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#169]
Description
When I try to update any editable attribute on the product, the product update is failing (in fact, it tries to create a new product). I also tested this for adding ePI for German lang and got the similar issue.

Step 1-
<img width="1680" alt="Screenshot 2021-04-16 at 2 49 16 PM" src="https://user-images.githubusercontent.com/16893108/115004171-26ffa980-9ec4-11eb-8953-42b3c9001c08.png">

Step 2-
<img width="1680" alt="Screenshot 2021-04-16 at 2 49 21 PM" src="https://user-images.githubusercontent.com/16893108/115004179-2b2bc700-9ec4-11eb-99a2-e3a1b6dce418.png">

Step 3-
<img width="1680" alt="Screenshot 2021-04-16 at 2 49 25 PM" src="https://user-images.githubusercontent.com/16893108/115004196-2ebf4e00-9ec4-11eb-89c8-d4ac65f2d3c0.png">

Acceptance Criteria-
The product should be successfully updated when any of the editable fields is modified.

**Comment by rite2bala** [comment]
![image](https://user-images.githubusercontent.com/44022980/115010733-6251a680-9ecb-11eb-92aa-a1212d06331a.png)

I was able to create a product and make changes to it until version 15 .. 

After version 15 - the update product  fails with the same error as described by Hrishikesh.

Then, I created another new product and tried to update the details of the new product - and faced the same error

**Comment by rite2bala** [comment]
This issue is resolved in the QA environment. We could move this to UAT.
