### ISSUE TITLE
PL[3.1.2]  Prepare pdf with test barcodes for test users

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#17]
Prepare pdf file with test barcodes for test users

AC:

PDF file with 6 barcodes as per [[https://share.merck.com/display/CCTS/Carton+artworks+for+testing]
Nice graphical style for good marketing and representation

For every product backlog item:
Rule                                                      Description
-Task description                               - add at least short description about the task
-acceptance criteria                          - clear description (bullet points) what is output of the task (output of team refinement)
-team engagement                            - one person/pair/team (list names in case of more than 1 person)
-task reviewed by at least 1 person   - acceptance criteria passing

**Comment by UnHynek** [comment]
Irrelevant
