### ISSUE TITLE
Batch expiry date change doesn't reflect on the PWA

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#173]
Description - 
If I update the expiry date on the batch backward or future, the expiry date is updated in the enterprise wallet but doesn't reflect on the PWA when the product is scanned. It continues to display the original set date.

1. Original date on the batch
<img width="1680" alt="Screenshot 2021-04-21 at 7 54 47 PM" src="https://user-images.githubusercontent.com/16893108/115571461-a46c5500-a2dc-11eb-8790-3a12235b606a.png">
2. Scanned the product, it displays correctly.
<img width="1680" alt="Screenshot 2021-04-21 at 7 54 50 PM" src="https://user-images.githubusercontent.com/16893108/115571481-a9310900-a2dc-11eb-80d9-def4a6bf6061.png">
3. Updated expiry date to historical date (past date)
<img width="1680" alt="Screenshot 2021-04-21 at 7 55 25 PM" src="https://user-images.githubusercontent.com/16893108/115571493-ac2bf980-a2dc-11eb-8843-436faefc8b70.png">
4. PWA still shows original date and doesn't perform the expiry invalid check.
<img width="1680" alt="Screenshot 2021-04-21 at 7 56 20 PM" src="https://user-images.githubusercontent.com/16893108/115571504-afbf8080-a2dc-11eb-8fa7-d04cee4d8131.png">

**Comment by asaccool** [comment]
The QR code generated and accessible in the Batch page are generated only once. The QR codes is created based on the initial expiration date, first serial number marked as valid, batch number and product gtin.
