### ISSUE TITLE
The batch message and Recall messages are not displayed correctly when the batch is updated multiple times.

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#178]
Description -
If a user updates the batch message or a recall message multiple times on the batch, the messages are not displayed correctly. In some cases, it doesn't show the updated message. 

Replication steps -
1. Create a new batch with batch message
2. Update the batch with recall flag and message
3. Update the batch and remove the batch message
4. Update the batch and add a new batch message
5. Update the batch and undo recall batch
6. Update the batch and remove the batch message.

**Comment by rite2bala** [comment]
Yet to test this functionality with this depth. Will test and update.
