### ISSUE TITLE
App Scanning of non-Serialized Codes

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#186]
When scanning a non-serialized barcode a warning is shown saying that the code cannot be read but then it manages to show the correct details. This is just a message that is shown for a few seconds, see the attached.

https://user-images.githubusercontent.com/58995303/117417766-faffa300-af1a-11eb-8fe8-40487b8474c9.MOV

**Update**: This only occurs if the barcode does not have AI21 encoded:
![image](https://user-images.githubusercontent.com/58995303/117421382-c857a980-af1e-11eb-8a5a-7d88a02a2b60.png)

If the same data is included in the Datamatrix and a serial number is added to the Datamatrix then the message is not shown on the screen.
![image](https://user-images.githubusercontent.com/58995303/117421571-efae7680-af1e-11eb-9987-eeaf966fe065.png)

I am not using the Scandit SDK integration when doing this testing. 
I am testing using Edge on my PC.

@rite2bala @mppub @nhrishi

**Comment by adiganga2002** [comment]
can not reproduce.
