### ISSUE TITLE
Multiple Serial number updates failed for valid serial numbers.

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#187]
Description

If a user tried to update the serial numbers multiple times by using reset serial numbers, the app does read and displays the right serial numbers but the serial number verification is displayed as recalled.

Here is an example - In this example, 0000000... is a valid serial number but the serial number verification is displaying it as Recalled. The batch is also not recalled status now (i had updated it to recalled earlier).
<img width="1680" alt="Screenshot 2021-05-10 at 12 14 41 PM" src="https://user-images.githubusercontent.com/16893108/117617851-bda14c80-b18a-11eb-9b07-7c33ab444927.png">

**Comment by skutner** [comment]
Hello @nhrishi . We were unable to replicate this bug following the above instructions. Could you please add a more detailed list of the steps you took to identify this problem, in case we are missing something. Thank you

**Comment by adiganga2002** [comment]
Can not be reproduced.
