### ISSUE TITLE
When a batch is expired or invalid expiry date, the product status is always displayed verified if the serial number is either recalled or decommissioned

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#188]
Description -

If the user scans the product with the batch is expired or 2D matrix has an invalid date, the app shows "Product status" as Verified even in case the serial number is recalled or decommissioned. In the case of the valid or invalid serial number, product status is displayed correctly (Product expired or invalid expiry date ).

Below screenshot for reference -

<img width="1680" alt="Screenshot 2021-05-10 at 12 35 10 PM" src="https://user-images.githubusercontent.com/16893108/117619504-fb06d980-b18c-11eb-9aec-899f28400e5a.png">
<img width="1680" alt="Screenshot 2021-05-10 at 12 35 40 PM" src="https://user-images.githubusercontent.com/16893108/117619512-fd693380-b18c-11eb-9c40-be23c5732813.png">

**Comment by rite2bala** [comment]
Tested - Works fine 

Product status shows expired
![image](https://user-images.githubusercontent.com/44022980/124548426-5383eb80-de4b-11eb-9031-4fa6ffaa0d42.png)
Today's date 6th July 2021
