### ISSUE TITLE
PL [3.1.4] Deployment in Kubernetes

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#19]
The solution is deployed using Kubernetes cluster. While technically it’s a very good solution, it’s not supported in Merck environment. I am currently not aware of any easy way how to get that into production – or even dev env – in Merck. There could be a way how to host Kubernetes cluster on GIO managed servers, but that will be very expensive and very painful. Other option will be to work with Cloud team and ITRMS to enable Kubernetes cluster in AWS in some form – which will be also equally difficult.

**Comment by UnHynek** [comment]
Irrelevant

**Comment by UnHynek** [comment]
Irrelevant
