### ISSUE TITLE
Scandit integration: camera is on after leaving the scanning page

### ISSUE THREAD

**Issue by mppub** [PharmaLedger-IMI/epi-workspace#190]
# Result
Camera is turned off after leaving the scanning page - this applies for the scandit version

**Comment by mppub** [comment]
partially fixed in: https://github.com/PharmaLedger-IMI/leaflet-ssapp/pull/10/files 

we need to catch "onpageleave" event in order to dispose of the camera fully, with use history api this should be possible if used everywhere in the app

**Comment by mppub** [comment]
fixed in: https://github.com/PharmaLedger-IMI/leaflet-ssapp/pull/10/files

**Comment by rite2bala** [comment]
https://user-images.githubusercontent.com/44022980/130793049-57a8e095-2dc8-4d81-bcfa-e60dd500cb7e.mp4

Hi 

This seems to recur in the current release. 

In the above video you will see that I am using the scandit camera to scan - the green light on the top of the screen remains even after I have navigated to the other pages.

Request your assistance in fixing this issue. 

Attached is a video from today in QA

cc: @skutner

**Comment by rite2bala** [comment]
Hi, 

I have observed this issue on safari browser in the normal Zxing camera also.

Below image for reference: 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/44022980/141282369-cbf94b6e-3dab-4438-9e0c-90753572e4ac.png">

**Comment by denypatrascu** [comment]
Fixed since: https://github.com/PharmaLedger-IMI/leaflet-ssapp/commit/55470f211de3f3b2a32792a4671cc666f55303ef
