### ISSUE TITLE
batch-specific version numbers are not correctly updated

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#191]
Description -
The version number is not displayed correctly for product updates. I updated the product only once with a batch-specific leaflet, but the batch screen displays 2 batch-specific versions in the list.

Replication steps -
1. Create a new product with ePI and SMPC (without batch-specific version)
2. Create a batch and use the latest leaflet version, the app would display the right ePI information.
3. Update the product and replicate the leaflet with another leaflet information (delete the ePI for English and add another one) and mark it as batch-specific ePI (by clicking batch-specific check box)
4. Now add a new batch, you would see 2 batch-specific versions in the drop down. Here is the screenshot - 
<img width="1680" alt="Screenshot 2021-05-10 at 4 01 25 PM" src="https://user-images.githubusercontent.com/16893108/117647114-319f1d00-b1aa-11eb-8ddf-a5dc28bc0ca0.png">

Acceptance criteria -
Ideally, there should be only 2 versions - 1) latest 2) one batch-specific.

**Comment by adiganga2002** [comment]
to be fixed after version management update

**Comment by salboaie** [comment]
It should be closed as there will not be any connection between batches and the version number of the product

**Comment by rite2bala** [comment]
Closing this issue as the batch versioning concept is changed completely.
