### ISSUE TITLE
Critical: Latest vs batch specific ePI leaflet versions

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#194]
**Description:**
When a batch specific version of ePI is uploaded, it over-writes the latest version of the leaflet. 

**Steps to reproduce:**

1.     Create a new product with ePI of Cosentyx_v1 and SMPC (not  batch-specific ePI version)
2.     Create a batch B1 for the above product and use the latest "leaflet" version
**Result:** The app would display the right ePI information.

3.     Update the product and replace the leaflet with another leaflet information Cosentyx_v2 (delete the ePI for English and add another one) and mark the new version as batch-specific ePI (by clicking batch-specific checkbox)

(Now product has two ePI Versions -  latest version and a batch-specific version.)

5.     Create a batch B2 with a batch-specific version leaflet.
6.     Scan the batch B1 with latest eleaflet version 
- Result: Bug ! App displays the batch specific version of the leaflet
– Expected Output – App should display Cosentyx_v1 which was the actual latest 

7.     Scan the batch B2  with batch-specific eleaflet version –
Result - batch displays the correct batch specific leaflet
 Expected Output – App should display Cosentyx_v2 
 
And then next steps –
Update the product with latest eLeaflet Cosentyx_v3 (unchecked on the batch-specific checkbox).
Create a new batch B3  with a latest leaflet version.
Scan this new batch B3 with latest eleaflet version – Expected Output – App should display Cosentyx_v3
Scan this new batch B1 with latest eleaflet version – Expected Output – App should display Cosentyx_v3

**Comment by rite2bala** [comment]
https://github.com/PharmaLedger-IMI/epi-workspace/issues/85

The positive and negative tests mentioned in the above issue are not met.

**Comment by adiganga2002** [comment]
version handling will be changed (@steinso2 )

**Comment by rite2bala** [comment]
Version handling will be changed - hence there is no need to test this at the moment

**Comment by adiganga2002** [comment]
Version handling was changed.
