### ISSUE TITLE
Create a shared library for creating DSUs inside DSU-Fabric (UI) and DSU-Fabric-Integration

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#200]

**Comment by salboaie** [comment]
[OneDrive_1_5-26-2021.zip](https://github.com/PharmaLedger-IMI/epi-workspace/files/6547992/OneDrive_1_5-26-2021.zip)

**Comment by adiganga2002** [comment]
To be clarified:
1 ) Fields present in UI view and missing form provided message examples :
         a) for batch: 
                                - decommissionReason
                                - recallSerials (for all types of serial numbers)
         b) for product: 
                                   - version
                                   - description
                                   - manufName
                                   - batchSpecificVersion
2) Fields missing from UI and present in messages:
         a) for batch:
                                - packagingSiteName
                                - flagEnableACFBatchCheck
                                - acfBatchCheckURL
         b) for product: 
                                - markets (array)
                                - inventedName
                                - internalMaterialCode
                                - strength
 To discuss: 
    Expiry date format ( in message now is - "expiryDate" : "221200", "expiryDate" : "220601", "expiryDate" : "231001")
    Serial numbers format (in message each serial is with quotation mark "snValid":[ "9049444522221", "QI88v00001", "00360000066000234"])
  Photo for product - how manage

**Comment by steinso2** [comment]
@salboaie Patrick and me answered your questions. Please see all starting with "=>"
The version / batch specific leaflet topic will be discussed next week and we will provide feedback to you after.
