### ISSUE TITLE
DRA1-UCA-EP04-US06 Inbound Data Capabilities

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#22]
**As a Manufacturer** 

**I want to** have the capability to handle additional information without impacting system performance or detracting from the user experience. For example display a recall message, display Anti-counterfeit check, displaying of different language files   

**So That** potential future requirements can be easily built on top 

**User Story Rationale/ Examples:**

The rationale behind this user story is for the designers/ developers to consider, as much as reasonably possible, future proofing the design of the solution and not just considering ePI as the end goal. We want to reduce/ minimize future costs when deploying additional use cases

**Comment by amanuel95** [comment]
**User Story Rationale/ Examples:** 

The rationale behind this user story is for the designers/ developers to consider, as much as reasonably possible, future proofing the design of the solution and not just considering ePI as the end goal. We want to reduce/ minimize future costs when deploying additional use cases

**Comment by amanuel95** [comment]
**User Story Rationale/ Examples:** 

The rationale behind this user story is for the designers/ developers to consider, as much as reasonably possible, future proofing the design of the solution and not just considering ePI as the end goal. We want to reduce/ minimize future costs when deploying additional use cases

**Comment by UnHynek** [comment]
1.	Question: Languages of ePI: what is content standard format to be used?
3.	Question: Recall: what is the process to trigger the message? Where does the message come from?
4.	Blocker: 
a.	app language: No
b.	content language: Yes
c.	recall message: Yes

**Comment by maherpa2** [comment]
It is clear that the ePI needs to be in all the current languages used across the Globe. PharmaLedger will not change this. There is no standard for the format right now. we should continue using the spl structure. Is there a technical issue in displaying French or Chinese for example, if it was in the spl format/ structure?

The trigger for the recall process will depend on the backend integration. It cannot be seen as a standalone function.

**Comment by nhrishi** [comment]
Action items -
- Use the right encoding on the SPL (XML) for different languages and test it [@maherpa2 ]
