### ISSUE TITLE
Schema & Default values  in message mapping

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#225]

**Comment by salboaie** [comment]
How do we treat missing fields (default values) when a DSU for product or batch is created. Some default values should be added.

**Comment by salboaie** [comment]
- check schema, convert values
- add default values for mandatory fields

**Comment by adiganga2002** [comment]
Batch validation Schema: 
{
  "type": "object",
  "properties":
    {
      "messageType": {"type": "string"},
      "messageTypeVersion": {"type": "number"},
      "senderId": {"type": "string", "defaultValue": "Test sender"},
      "receiverId": {"type": "string", "defaultValue": "Test receiver"},
      "messageId": {"type": "string"},
      "messageDateTime": {"type": "string"},
      "batch": {
        "type": "object",
        "properties": {
          "productCode": {"type": "string", "required": true},
          "batch": {"type": "string", "required": true},
          "expiryDate": {"type": "string", "required": true, regex: /^[\d+]{6}$/},
          "packagingSiteName": {"type": "string"},
          "epiLeafletVersion": {"type": "number"},
          "flagEnableEXPVerification": {"type": "boolean"},
          "flagEnableExpiredEXPCheck": {"type": "boolean"},
          "batchMessage": {"type": "string"},
          "flagEnableBatchRecallMessage": {"type": "boolean"},
          "recallMessage": {"type": "string"},
          "flagEnableACFBatchCheck": {"type": "boolean"},
          "acfBatchCheckURL": {"type": "string"},
          "flagEnableSNVerification": {"type": "boolean"},
          "snValidReset": {"type": "boolean"},
          "snValid": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
}

**Comment by adiganga2002** [comment]
Product schema: 
{
  "type": "object",
  "properties":
    {
      "messageType": {"type": "string"},
      "messageTypeVersion": {"type": "number"},
      "senderId": {"type": "string"},
      "receiverId": {"type": "string"},
      "messageId": {"type": "string"},
      "messageDateTime": {"type": "string"},
      "product": {
        "type": "object",
        "properties": {
          "productCode": {"type": "string", "required": true},
          "internalMaterialCode": {"type": "string", "required": true},
          "inventedName": {"type": "string", "required": true},
          "nameMedicinalProduct": {"type": "string", "required": true},
          "strength": {"type": "string", "required": false},
          "flagEnableAdverseEventReporting": {"type": "boolean"},
          "adverseEventReportingURL": {"type": "string"},
          "flagEnableACFProductCheck": {"type": "boolean"},
          "acfProductCheckURL": {"type": "string"},
          "flagDisplayEPI_BatchRecalled": {"type": "boolean"},
          "flagDisplayEPI_SNRecalled": {"type": "boolean"},
          "flagDisplayEPI_SNDecommissioned": {"type": "boolean"},
          "flagDisplayEPI_SNUnknown": {"type": "boolean", "required": true},
          "flagDisplayEPI_EXPIncorrect": {"type": "boolean"},
          "flagDisplayEPI_BatchExpired": {"type": "boolean"},
          "patientSpecificLeaflet": {"type": "string"},
          "healthcarePractitionerInfo": {"type": "string"},
          "markets": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "marketId": {"type": "string", "required": true},
                "nationalCode": {"type": "string", "required": true},
                "mahName": {"type": "string"},
                "legalEntityName": {"type": "string"},
              }
            }
          }
        }
      }
    }
}
