### ISSUE TITLE
iOS Simulator & Physical Device build

### ISSUE THREAD

**Issue by mppub** [PharmaLedger-IMI/epi-workspace#230]
# Motivation
There is a crash of the iOS simulator build after last commits + physical device was not working even before, this is preventing  the further integration of Scandit library

# Reproduction steps
tbd @fp-prg-mdc 

# Results
1. iOS simulator build is working
2. build into physical iPhone device is working

# Tech description
--please-put-logs-screens-etc--

**Comment by asaccool** [comment]
Hi Michael (@mppub), please document the steps done from the cloning of the epi-workspace and until the build of the mobile app.

**Comment by mppub** [comment]
@fp-prg-mdc guys could you please include the reproduction steps? thank you

**Comment by asaccool** [comment]
The app needs camera access, ios simulator does not provide access to one. That’s why a real device should be used for the development.

I did some tests and there was a small problem that i fixed regarding the error thrown at the run time o a device connected to the xcode.

Please check a fresh clone if the bug that you identified is still there.

**Comment by dns45** [comment]
Issue was fixed. Thanks @asaccool for resolving it!
