### ISSUE TITLE
DRA1-UCA-EP04-US02 Document Display

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#25]
**As a Manufacturer**  

I want to have a solution that can display various document types without the need to proofread each possible document type displayed.  

**So That** the Patient or HCP has the best user experience

**User Story Rationale/ Examples:**
This user story is specific to the displaying of the ePI / document. Unfortunately from an ePI perspective there is no single standard structured format that is used across the EU or the World. There are many initiatives working on this with various degrees of success and an implementation base. Therefore the device will need to be able to display different formats for example PDF’s, various XML based structured files, various JSON based structured files etc.
The release of the source file for all the various formats displayed should be sufficient to guarantee correctness for all possible displays by a GxP Validated transformation process.
 
A key component of this User story is that, regardless of the format of the ePI that it has to be displayed correct on each device that is used. If the Patient wishes to save it as print it out as a PDF then the PDF must be correct. The concern is that the original file is not displayed correctly or it is incorrect when printed.
 
**Topics to be Addressed/ Discussed:**
An investigation into what ePI’s are available today in various countries and sample files will need to be carried out

**Comment by amanuel95** [comment]
This user story is specific to the displaying of the ePI / document. Unfortunately from an ePI perspective there is no single standard structured format that is used across the EU or the World. There are many initiatives working on this with various degrees of success and an implementation base. Therefore the device will need to be able to display different formats for example PDF’s, various XML based structured files, various JSON based structured files etc. 

The release of the source file for all the various formats displayed should be sufficient to guarantee correctness for all possible displays by a GxP Validated transformation process. 

A key component of this User story is that, regardless of the format of the ePI that it has to be dispalyed correct on each device that is used. If the Patient wishes to save it as print it out as a PDF then the PDF must be correct. The concern is that the original file is not displayed correctly or it is incorrect when printed. 

**Topics to be Addressed/ Discussed:** 

An investigation into what ePI’s are available today in various countries and sample files will need to be carried out

**Comment by UnHynek** [comment]
Do we have an alignment on standard format to be used?

**Comment by maherpa2** [comment]
There is no standard format. we should focus on spl for the moment. As others come along then we can review and implement as necessary. We should not concern ourselves with PDF at the moment.
However if the ability to print the ePI is provided (which is needed) then we need to design it in a way that the leaflet is printed out in a patient friendly format with everything formatted correctly i.e. just printing an XML file will not be acceptable, so the following would not be acceptable as a printout for obvious reasons:
![image](https://user-images.githubusercontent.com/58995303/108166048-e4a03300-70f3-11eb-977e-223190600f3b.png)

**Comment by nhrishi** [comment]
Action items-
- Technical team needs to add a download and print option for users.
- Use SPL format for eLeaflet
- Create a separate user story for the convertor [@maherpa2 ]
