### ISSUE TITLE
DRA1-UCA-EP04-US01  Decoding

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#26]
**As a Manufacturer**  
I want to have a solution that can Decode the barcodes that may appear on the market   

**So That** the solution can be used across multiple markets with different barcodes

**User Story Rationale/ Examples:**
This user story is specific to the actual scanning and decoding of the barcode. There are many different barcodes in use across the supply chain. As examples in the EU with serialization a GS1 encoded Datamatrix is used, in Japan a DataBar Composite Symbology (the GS1 Composite Symbology is a combination of a linear barcode component and a special 2D Composite Component (CC) symbol printed on top. The linear component encodes the item’s primary identification (GTIN). The adjacent 2D Composite Component (CC) encodes supplementary data, such as a batch number and expiration date.). The rationale behind this user story is that, regardless of the barcode used, the application should be able to decode the data.
In the case of a Russia serialized Datamatrix the batch number and expiration date are not included so consideration needs to be given on how to potentially get a batch specific ePI for this pack.
The ability to scan QR’s codes is for potential future use cases.
The thought behind specifying the module width would be to perhaps give a message to the user if their device did not have a camera with a minimum resolution in order to read certain barcodes.
 
For MVP 1 the scope will be a GS1 encoded Datamatrix code with the following data encoded:
·         GTIN
·         Serial Number
·         Batch Number
·         Expiry Date

**Comment by amanuel95** [comment]
This user story is specific to the actual scanning and decoding of the barcode. There are many different barcodes in use across the supply chain. As examples in the EU with serialization a GS1 encoded Datamatrix is used, in Japan a DataBar Composite Symbology (the GS1 Composite Symbology is a combination of a linear barcode component and a special 2D Composite Component (CC) symbol printed on top. The linear component encodes the item’s primary identification (GTIN). The adjacent 2D Composite Component (CC) encodes supplementary data, such as a batch number and expiration date.). The rationale behind this user story is that, regardless of the barcode used, the application should be able to decode the data.  

In the case of a Russia serialized Datamatrix the batch number and expiration date are not included so consideration needs to be given on how to potentially get a batch specific ePI for this pack. 

The ability to scan QR’s codes is for potential future use cases. 

The thought behind specifying the module width would be to perhaps give a message to the user if their device did not have a camera with a minimum resolution in order to read certain barcodes. 

For MVP 1 the scope will be a GS1 encoded Datmatrix code with the following data encoded: 

GTIN 
Serial Number 
Batch Number 
Expiry Date

**Comment by maherpa2** [comment]
@UnHynek @nhrishi : please provide an overview of which barcode types can be scanned and decoded?

**Comment by nhrishi** [comment]
![image](https://user-images.githubusercontent.com/16893108/108314183-7d5fad00-71df-11eb-8165-23f08fb44606.png
√

**Comment by nhrishi** [comment]
Below barcode types should be supported. Please see the attached document for more details. Also attached image for Japan code (example for no. 13).
[Barcodes and Resolver v0.3 (2).pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6000682/Barcodes.and.Resolver.v0.3.2.pdf)
![JapanCode](https://user-images.githubusercontent.com/16893108/108315071-e8f64a00-71e0-11eb-8297-829c743c04f2.jpg)



1. Code with AI01+AI21+AI17+AI10 with <GS> and <FNC> separator
2. Code with AI21+AI17+AI10+AI01 with <GS> and <FNC> separator
3. Code with AI21+AI17+AI10+AI01 with <GS> and <FNC> separator
4. Code with AI21+AI01+AI17+AI10 with <GS> and <FNC> separator
5. Code with AI21+AI01+AI17+AI10+AI714 
6. Code with AI21+AI01+AI17+AI10+AI714+AI712 
7. Russian Code with AI01+AI21+AI91+AI92 
8. Russian Code with AI01+AI21+AI91+AI92 
9. Russian Code with AI01+AI21+AI91+AI92 
10. EAN-13
11. GS1-128
12. C128
13. GS1 Composite code - the combination of PDF417 and a GS1 1D (EAN/UPC/GS1-128/DataBar) (e.g. Japan code)

@maherpa2  Could you please review once and confirm. Thanks.
