### ISSUE TITLE
Product version fixes

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#264]
- version -> Product versions  (each edit increase the version automatically)
- we do not keep anymore versions folders for leaflets in the product DSU
-  add version for batches (edit versions)
- no links between batches and product versions
- batch specific leaflets  possible by uploading them in the batch 
- put in audit log versions and reason *what fields changed)

**Comment by steinso2** [comment]
@salboaie  here the presentation showing the version for product and batches
[Changes to product & batch.pptx](https://github.com/PharmaLedger-IMI/epi-workspace/files/6701534/Changes.to.product.batch.pptx)
