### ISSUE TITLE
DRA1-UCA-EP03-US05 resolution of NTIN after divestment

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#27]
**As a Patient or HA**  
I want to have a solution that can resolve to the correct owner when the NTIN does not change as part of a divestment  

So That the responsible manufacturer can supply the most appropriate electronic leaflet
 
**User Story Rationale/ Examples:**
This user story relates to the resolution of the NTIN when a divestment takes place. The NTIN’s in Europe, Germany for example, do not change with a divestment. 
In some regions of the world the NTIN does change so this could be treated as a pseudo GTIN from a resolution process perspective.
 
See attachment A1 and A2 for additional information/ concepts.
 
**Topics to be Addressed/ Discussed:**
The draft process flow needs to be reviewed and updated as necessary.

**Acceptance Criteria:**
Simulate a change in the NTIN owner and ensure the resolver resolves to the correct locations

**Comment by amanuel95** [comment]
https://issues.merck.com/secure/attachment/386085/A1%20Divestment%20Scenarios%20Flow%20Chart%20v0.2.pdf
https://issues.merck.com/secure/attachment/386086/A2%20GTIN%20%20NTIN%20Resolver%20Concept%20v0.1.pdf

**Comment by UnHynek** [comment]
More clarification will be useful:
Ken/Patrick? to create clear rules of divestment scenarios and what is expected from the platform.
Ken/Patrick? to add clear acceptance criteria for each scenario.
