### ISSUE TITLE
GRID/Table reusable component should be use in audit/batch and product tables

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#271]
- should be reusable and core in  webcardinal
- close relation and optimised to be used together  with an openDSU DB  (pagination + filters)
- fast loading 
- configurable number of rows
- infinite scroll 
- field filters (regular expression for strings, perfect match - no other conditions)
- optional/configurable renders when needed
- optional/configurable edit in place

**Comment by denypatrascu** [comment]
Examples for using this component: 
1. [webcardinal-app-tester - webc-datatable - Customization](https://webcardinal.github.io/webcardinal-app-tester/tests/manual/webc-datatable/6)
2. [webcardinal-app-tester - webc-datatable - Slots](https://webcardinal.github.io/webcardinal-app-tester/tests/manual/webc-datatable/4)
3. [webcardinal-app-tester - webc-datatable - Translations](https://webcardinal.github.io/webcardinal-app-tester/tests/manual/webc-datatable/3)

More example: https://webcardinal.github.io/webcardinal-app-tester
