### ISSUE TITLE
DRA1-UCA-EP03-US04  Resolution after Divestment

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#28]
**As a Patient or HA**  
I want to have a solution that can resolve to the correct owner when the GTIN does not change as part of a divestment  

**So That** the responsible manufacturer can supply the most appropriate electronic leaflet 
 
**User Story Rationale/ Examples:**
This user story relates to the resolution of the GTIN when a divestment takes place. It may be possible that the same GTIN will be used, perhaps for a short period of time by the MAH that has acquired the product. See attachment A1 and A2 for additional information/ concepts.
 
**Topics to be Addressed/ Discussed:**
The draft process flow needs to be reviewed and updated as necessary.

**Acceptance Test**
Simulate a change in the GTIN owner and ensure the resolver resolves to the correct locations. 

**Sub Tasks**
1. #76

**Comment by amanuel95** [comment]
https://issues.merck.com/secure/attachment/386073/A1%20Divestment%20Scenarios%20Flow%20Chart%20v0.2.pdf
https://issues.merck.com/secure/attachment/386074/A2%20GTIN%20%20NTIN%20Resolver%20Concept%20v0.1.pdf

**Comment by UnHynek** [comment]
After discussion with team we may need more information: 
Ken/Patrick? to create clear rules of divestment scenarios and what is expected from the platform.
Discuss clear acceptance criteria for each scenario.

**Comment by nhrishi** [comment]
Here are rules and different scenarios for divestment. @maherpa2 @steinso2 and I can do a walkthrough if required.
[DivestmentScenarios_v0.5.xlsx](https://github.com/PharmaLedger-IMI/epi-workspace/files/5979525/DivestmentScenarios_v0.5.xlsx)
