### ISSUE TITLE
Import Log issues

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#287]
The audit log works fine, however, the  import log shows the messages from audit log too. 

the import log  must show only messages  from import  only.

**Comment by rite2bala** [comment]
Audit log  and Import log are same.

<img width="1792" alt="Screenshot 2021-07-09 at 5 57 05 PM" src="https://user-images.githubusercontent.com/44022980/125077976-657dbc80-e0df-11eb-9863-f23896d29fce.png">


<img width="1792" alt="Screenshot 2021-07-09 at 5 56 20 PM" src="https://user-images.githubusercontent.com/44022980/125077984-69114380-e0df-11eb-8eec-d91109139aab.png">

**Comment by adiganga2002** [comment]
@rite2bala Hi, the purpose of including all messages in import page logs is to offer possibility to download and edit messages for other similar  imports, as we use same mapping engine both for external import as for manual ui interacting. We can remove the ui interacting messages.

**Comment by rite2bala** [comment]
Hi
Thank you
Please remove the UI interacting messages on the Import log and restrict the import log only to import related notifications.

**Comment by adiganga2002** [comment]
This is not in scope.
