### ISSUE TITLE
DRA1-UCA-EP03-US03 Suspect GTIN resolution 

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#29]
**As a MAH**  
I want to have a solution that can resolve even if the serial number or batch number etc. is incorrect  

**So That** suspect falsified products can be reported and subsequently investigated

**User Story Rationale/ Examples:**
This user story relates to the resolution of the GTIN/ NTN. It is important that the GTIN/ NTIN resolver uses the GTIN/ NTIN as the main resolution Key in order to resolve to the responsible MAH. The rationale behind this request is that in the event of a falsified pack using a valid GTIN/NTIN (i.e. GTIN/ NTIN is registered to a MAH) then the MAH is notified that there is a Potential Suspect Falsification in the market and subsequent investigation activities can take place as per internal MAH procedures. Typically for most markets the Datamatrix code will contain the GTIN/ NTIN, Serial Number, Batch and Expiry date. However for some markets additional or different data may be encoded, for example some countries require the NHRN to be encoded while for Russia the Datamatrix does not contain the Batch or Expiry date. Instead it has GTIN, Serial Number, Crypto Key, Crypto Code.
 
This requirement is not contradicting the need to be able to provide batch specific ePI’s for example.
 
For the purpose of MVP 1, the scope will be on a Datamatrix code which has the following encoded:

GTIN
Serial Number
Batch Number
Expiry Date
 
**Acceptance Tests**
Create a falsified pack, incorrect Batch, Serial Number etc. and the GTIN Resolver should still resolve correctly. A message should be provided to the end user to indicate that the Batch Number, Serial Number or Expiry date is incorrect.

We need to agree
- if we will check in this MVP the batch / SN in backend system or not
- in MVP1 NVS, we display the GTIN leaflet for an unknown batch. User gets information that only product specific leaflet can be displayed (in future state: the batch needs to be checked in backend system, to ensure the pack is not falsified)
- same discussion for SN

**Comment by UnHynek** [comment]
1.	Question: Should app display the leaflet if the serial number or Exp date is "incorrect"?
2.	Dependency: Integration with internals ATTP
