### ISSUE TITLE
Market Management

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#290]
Fields in market tab are mandatory today they need to be optional

Fields need to be editable

**Comment by rite2bala** [comment]
![image](https://user-images.githubusercontent.com/44022980/125082339-be038880-e0e4-11eb-8c59-54ce06c49755.png)

**Comment by Mastaleru** [comment]
The validation on market fields could be simplified now
https://github.com/PharmaLedger-IMI/dsu-fabric-ssapp/commit/a58b53277585c734f90ba7c861fd398183c0238a#commitcomment-53530858
