### ISSUE TITLE
Autofocus issue?

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#301]
Here is a case reported by a key user from Singapore:
 https://www.dropbox.com/s/3x70n3p55401t42/Video%2023-7-21%2C%2010%2030%2008%20AM.mp4?dl=0

The user is using an iPhone 12 native camera setup and believes that the issue is with the app scanning the code slowly as it fails to focus. 

May I please request you to share your thoughts on what could be the possible issue? Do we have a minimum size of the data matrix code that can be scanned?

**Comment by rite2bala** [comment]
Tagging all team mates who worked on product scanner setup for your expert comments 
@mppub @vladbalmos @fp-prg-mdc @skutner

cc @nhrishi

**Comment by mppub** [comment]
I was just looking at the video - the scanner uses the native camera which handles the focus, also in other hand: we do not control and shall not control the focus.

This is clearly an issue of the pack and the scanning - it is obvious that the phone is trying to focus the computer behind/the hands and then it fails to refocus when you get the phone closer. The only way how to fix this is probably to print the code bigger/put it into larger area in the pack(not on the sides that are very narrow.).

We could try to figure out the minimal code size / background / margins - is there some more guidelines about camera focus @fp-prg-mdc ?

**Comment by mppub** [comment]
So my thoughts just got confirmed by @fp-prg-mdc - basically if the autofocus of the native camera does not work, then we can not and should not do nothing.

otherwise we can try to print it bigger with bigger margins - no silver bullet here though.

anyway I would retry with camera starting pointing at something as close as the code it should work then

**Comment by rite2bala** [comment]
Hi @denypatrascu , 
Could you please comment about the implementation of this?

Were you able to identify the right camera for scanning?

**Comment by salboaie** [comment]
we fixed a bug regarding this already, we will prioritize other improvements in scanning for January next year
