### ISSUE TITLE
GTIN verification within the enterprise wallet

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#306]
The GTIN stands for Global Trade Identification Number.  It is also called as "Product Code". 

This number is unique to the product and has certain standards that have been designed by the GS1 to adhere to. 

The right most digit of the GTIN (in the units place) is called the check digit and it is derived by following a calculation.

Here is a guide to calculate the check digit:
https://www.gs1.org/services/how-calculate-check-digit-manually

This calculation needs to be used as a field level validation in the enterprise wallet to identify the right check digit and compare with the one entered by the user. 

Product creation must not be allowed if the check digits of the number entered by the user doesn't match with the calculated value.

**Comment by rite2bala** [comment]
#128 also refers to this

**Comment by adiganga2002** [comment]
Closing this as it's covered by #128
