### ISSUE TITLE
Critical: Product Information is optional but shows icon

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#308]
Hello team 

In the story: https://github.com/PharmaLedger-IMI/epi-workspace/issues/198, the product information was made an optional item during the upload.

However, it is observed that whenever product information is not uploaded, the Product information icon is displayed on the mobile app. 

There is no date under the product information there. 

The below code from ePI UAT environment is associated with a product that has only SMPC, but when you scan it, in leaflet-ssapp both Product Information and SMPC buttons appear. However, if you click on Product Information you are redirected to an error page which is not expected .. 
![image](https://user-images.githubusercontent.com/44022980/127150540-bcdd6bab-bd29-4411-ab56-7ed549b98bdc.png)

Expected outcome:
Whenever there is no Product Information - the user must not see the icon only to see the error.

**Comment by steinso2** [comment]
@rite2bala  
I have a comment on your _"Expected outcome:
Whenever there is no Product Information - the user must not see the icon **only to see the error**."_

- I do suggest **_not_ to show an error**. If a MAH decided not to upload a leaflet-fine. Just don't show a Icon. 
- Mid-term this could be a relevant use case e.g. we have the anti-counterfeiting use case providing an icon to check the verification features, which not necessarily means we have for all products a  leaflet available.

**Comment by rite2bala** [comment]
Hi @steinso2 ,

I meant the same :)

**The user must not see the icon** -
because when the user sees he icon and touches **he only gets an error message**
