### ISSUE TITLE
Choose the right camera in PWAs, Android and iOS

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#321]
Currently we try to choose a back camera, but Samsung Galaxy S21 (and probably other new phones) have telephoto/ wide angle lens. 

Solution: we should switch between cameras until we find a "normal / macro lens" one.

**Comment by rite2bala** [comment]
https://user-images.githubusercontent.com/44022980/128816531-115e0ee0-cde4-4779-9ddd-97d503be20e9.mp4


Here is the video  using a Samsung Galaxy M31

You would observe that the camera opens in telescopic view having a large field of view. 
inspite of holding the camera about 15 cm away from the laptop, the entire laptop is seen

When the change camera option is clicked, it opens the front camera .. and then after pressing it multiple times, the actual normal/ macro camera is turned on , and the code is visible very clearly before getting scanned. 

In my opinion, if we can identify this camera and choose in configuration, it would solve the issue.
