### ISSUE TITLE
DRA1-UCA-EP02-US06 eContent Maintenance and Ownership over Life Cycle

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#33]
**As a MAH** 

I want to always have clear ownership of the structured eContent, and be able to transfer it to another MAH in case of divestment 

**So That** the Patient always gets the ‘right’ and ‘latest’eContent from the me, because I am liable and accountable for it unless I divest it.  If I divest a product to a different MAH, I want to transfer the structured eContent to them, because the new MAH will be  responsible to give the ‘right’ and ‘latest’ eContent.  The onus is on both parties to provide this In the case of acquisition of a product from another MAH, I am responsible to give the ‘right’ and ‘latest’ eContent.    

**User Story Rationale/ Examples:**
Rationale:   The MAH is responsible and liable for a product that it places on the market, including  the provision of correct contents for product inserts.
  
Consider the digital eLeaflet as an integral part of the product… a digital shadow of the physical product where the 2 are tied together.
 ** 
It follows that a transfer of marketing authorization of a product infers a transfer in ownership of the digital shadow and the eContent Asset.
 ** 
Parking Lot item:  Internal Pharma co Quality Release Processes will need to change from verifying the paper insert is correct, to verifying that the eContent is correct prior to releasing product to the market so a digital leaflet is always available. 

**Acceptance Tests**
eContent can be transferred from one MAH to another and retrieved by a Patient using the new and old GTIN. 
All batch-specific eContent is transferred and provides the correct eLeaflet for batches prior to transfer. 

1- Scan GTIN-A/Batch-1 and get Company A resolved (see attachment scenario 1.a.)
         -> Company A shown on landing page and content for that GTIN/Batch, maintained by Company A shown 
2-Transfer GTIN-A to Company B
3-After GTIN-A was transferred to Company B, update leaflet
4-Create new Batch-2 for GTIN-A
5-Scan GTIN-A/Batch-1 and still get Company A resolved (see attachment scenario 2.a.)
6-Scan GTIN-A/Batch-2 and get Company B resolved (see attachment scenario 5.b.)
7-After GTIN-A was transferred to Company B, Company-A tries to update leaflet, but this is not possible

Open for MVP: 
- shall we add scenarios where all existing batches will be transferred to company B as part of divestment?
- shall we include scenarios where the leaflet shows new owner, but batch, SN etc is still checked by original owner? (see attachment scenario 3.a.)
-

**Comment by UnHynek** [comment]
More clarification will be useful: 
Ken/Patrick? to create clear rules of divestment scenarios and what is expected from the platform.
Ken/Patrick? to add clear acceptance criteria for each scenario.

**Comment by maherpa2** [comment]
The divestment scenarios have been drafted. To be shared with the Tech team. 
@nhrishi please upload and share information.

**Comment by nhrishi** [comment]
Please see attached divestment scenarios drafted for EPI.
[DivestmentScenarios_v0.5.xlsx](https://github.com/PharmaLedger-IMI/epi-workspace/files/5993741/DivestmentScenarios_v0.5.xlsx)

**Comment by nhrishi** [comment]
Next Actions decided -
1. Schedule a workshop to finalize all the scenarios [Patrick] - <add date>
2. Identity obvious scenarios and create user stories [Sonja] - <add date>

@maherpa2  @steinso2
