### ISSUE TITLE
DRA1-UCA-EP02-US03 User gets only Trusted and Secure eContent

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#34]
**As a Health Authority** 

**I want to** trust that the Patient only gets secure eContent which has been created by the Manufacturer / MAH and duly approved by the HA for dissemination 

**So That** the Patient gets what is needed under the regulations for the safe use of the product, and NOT promotional materials which are not permitted
 
**User Story Rationale/ Examples:**
It is perceived that eContent could be mis-used to promote Manufacturers products or services, either intentionally/unintentionally.  HA’s need to be assured that this cannot happen.
For example, a Patient must not get an eLeaflet which contains advertisements of products, only the statutory required labelling is allowed.

Secure means that the eContent is controlled (owned by Manufacturer), accurate (with correct ‘batch specific’ and ‘non-batch-specific’ data / information), up-to-date (approved eContent only, no drafts) and not corrupted from the approved eContent (unauthorized changes/fraud)

**Acceptance Tests**
·         Note: Happy path:  Scan a 2D code for different manufacturers and batches.  Ensure that the secure eContent is provided
·         Note: Non-happy path:  Scan a 2D code for different manufacturers and batches without secure eContent.  Provide warning message and instructions to patient about what to do

**Comment by UnHynek** [comment]
1.	Question: Should it be excluded from MVP2a until Epic 1 is defined?
2.	Question: What is the expected process in app?
3.	Action: Ken/Patrick to define clear acceptance criteria.
4.	Idea: Add new use case to sign the content by another identity and verify signature. Include in MVP2a.
5.	Idea:  Juraj to define simplified HA signing process and present to Ken/Patrick.

**Comment by maherpa2** [comment]
This has nothing to do with the App.
The process should be that only approved ePI's are allowed to be loaded into the DSU. The App only displays what has been put in the DSU.
Currently we can load anything into the DSU as this is just under development. But for the future only approved (to be defined what this actually means) ePI's should be allowed to be loaded into the DSU's. It may be the situation for some countries/ regions that there may not be an actual digital HA approval process in place so approval would come from the MAH.

**Comment by nhrishi** [comment]
Content is approved outside.
Action items -
- Enterprise API should be looked at
