### ISSUE TITLE
Introduce 3 User Roles in the ePI solution

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#356]
The ePI solution will have 3 roles: ePI Administration, ePI Write, ePI Read 

- The administrator of the Demiurge tool  will create 3 groups
  - ePI Administration Group: will share with other wallets the Enclave of the MAH Demiurge tool
  - ePI Write: will contain MAH employees (DIDs of their wallets) with write access to the data from MAH Enclave
  - ePI  Read Group : will contain MAH employees (DIDs of their wallets) with read access to the data from MAH Enclave

The groups are predefined for the ePI Demiurge using the mapping engine :
- when the DID of the Demiurge wallet is created there will be two options - initiate a new company "ePI Demiurge Wallet" that is initializing the right groups for ePI or "Join as administrator" that will put the new wallet in waiting for an acceptance message for other Demiurge wallet (together with access to keys and Enclaves)

**Comment by steinso2** [comment]
@salboaie 
I spoke about that also with Patrick and Amit. Outcome: 

**As a long term solution**  (just to provide an outlook) we should be able to differentiate in the wallet between DSU's e.g. If we have in our existing Novartis wallet the product and batch (=ePI) and in future also the Anti-counterfeiting DSU (where we store all the necessary steps to check a feature on the pack for a given product / batch), we should be able to differentiate  

1. who could maintain (read/write/delete) the product and batches and 
2. who is allowed to update ACF data
Maybe even who is allowed to update the product data and who is allowed to update the batch data. 

Just as an outlook to help you defining the right strategy.
