### ISSUE TITLE
DRA1-UCA-EP02-US01 Provide ‘right’ and appropriate ‘latest’ eContent for the Product in the pack throughout the Product Life Cycle

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#36]
**As a Patient/HCP** 

I want to access the ‘right’ and ‘latest’ product information for the medicine in my pack 

So That I can be certain I can take my medicine safely and my medicine is ‘available for use’ when new indications are approved 

User Story Rationale/ Examples:
 ** 
See attachment A3 for example scenarios
 ** 
Example #1:  ‘Batch-Specific’ Content: 
I have allergies, so I need to check my medicine does not contain ingredients which would cause me harm.  Over a product life cycle, the product ingredients can change, for instance, if a manufacturer changes a lactose excipient for cornstarch.  Both versions of the product could be on the market at the same time. If I am allergic to lactose, I need to know if lactose is in the product.  Therefore, I need to get ‘batch-specific’ information about ingredients used in the medicine that I would be consuming.
 
Example #2:  ‘Non-Batch-Specific’ Content: 

I am a HCP wanting to treat a patient for brain cancer with this product.  The product was on the market for lung cancer for a year but only just got approved by the HA for brain cancer yesterday.  I want to give my patient access the product.  Therefore, I need to get the ‘latest’ Product GTIN Information so I can safely prescribe it. I need to get the ‘non-specific-batch’ information for this product. 

**Acceptance Tests**
·         Note: Categorize eContent as ‘batch specific’ or ‘non-batch-specific’.  Simulate the broad range of typical product updates (see table in appendix) .
·         Note: For ‘batch specific’ information, display batch specific ‘right’ information.
·         Note: ‘non-batch specific’ applies to the product GTIN regardless of batch, like safety updates or new indications.  Display ‘latest’ information

**Comment by UnHynek** [comment]
Action: Ken/Patrick - Business analysis of the latest vs right needs to be clarified with the team.

**Comment by maherpa2** [comment]
We need to be able to update the ePI/ SmPC that has been put n the DSU and have this either assigned to all batches or a specific batch.
In probably >95% of the cases the latest ePI is the correct one to give to the patient. So one concept could be that if the ePI is not assigned at the batch level then it uses the ePI at the product level. If the ePI is assigned at the batch level then it would use that ePI. 
However in both situations the fundamental problem still remains: How do we update the ePI and have it assigned to all batches that are already on the market and how cold we update a specific ePI?
From a technical perspective, this is not about latest vs right, it is about the ability to update and assign the ePI.

**Comment by nhrishi** [comment]
Next action item -
- Simplify the requirements for the technical team  [@maherpa2 ] - [19 Feb 2021]
- Tech team should come back if Architecture changes required. [@salboaie ]  [TBA]
