### ISSUE TITLE
Product master: add new flag and URL for "Report for Product investigation"

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#361]
**New requirement for the product master screen:** 
Similar to the existing flag "Enable Adverse Events Reporting", we need another flag to allow the patient to provide information for a "product investigation". This is not necessarily the same URL than we have for the adverse event reporting, and might involve also other teams in Pharma companies. 

![image](https://user-images.githubusercontent.com/78138966/131529404-84956244-7fcd-4d65-a9fc-eb23881443bf.png)

From a user perspective, on the mobile screen we can show only one button:
REPORTING 
(and when clicking we could show)
     
1. Contact PharmaLedger to report an App issue 
2. Contact Pharmaceutical Company to start product investigation
3. Contact Pharmaceutical Company to report adverse events

Because showing different buttons per area is maybe to crowded for the app home screen.

**Comment by steinso2** [comment]
@maherpa2 I like to discuss this tomorrow with you, I will explain more in detail and we can close or refine the ticket.

**Comment by rite2bala** [comment]
@steinso2  - require your inputs on this ticket. If it can be prioritised for development.

**Comment by rite2bala** [comment]
@skutner , @salboaie,  @asaccool : need your comments about the implementation of this feature item.

**Comment by salboaie** [comment]
Will go for the next releases @adiganga2002

**Comment by nhrishi** [comment]
Adverse event reporting is not in the MVP1 scope.
