### ISSUE TITLE
PL [3.1.23] Parse PDF file to text, transform to mobile friendly PDF or model

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#38]
Parse PDF file to text, transform to mobile friendly PDF or model.

SPIKE ? Figure out how to do this with eLeaflet to get mobile friendly leaflet format into mobile app

**LEARNINGS:**

Without AI, It's not possible transform leaflet PDFs and achieve the same UX as with paper leaflet. There are two possible solutions:

use some structured data format instead of PDF (or maybe PDF accessibility tags could be helpful)
create mobile friendly PDFs editorially
 There is no library for Vapor for parsing PDFs.

For every product backlog item:

| rule | description| status |
| --------------- | --------------- | --------------- |
| Task description| add at least short description about the task| ✅|
| Acceptance criteria |clear description (bullet points) what is output of the task (output of team refinement) | ✅ |
| team engagement | one person/pair/team (list names in case of more than 1 person) | 1+ |
|task reviewed by at least 1 peer| acceptance criteria passing| X|

| ruler | description | status |
| --------------- | --------------- | --------------- |
| branch created | - branch with correct type (feature/bugfix/...) - branch name contains JIRA reference | X |
| tests | - tested manually - unit tests implemented if applicable (team agreement) - integration/E2E tests for finished feature if applicable (team agreement) | X - - |
| sdlc | if the task covers acceptance criteria from requirement add test case(s) to SIT documentation -technical documentation updated (DCS) if applicable (team agreement | - - |
| coding standards | static analysis (linter, sonarQ) passing | X|
| development practices | commits contain reasonable message - logging enhanced - monitoring updated - analytics added/updated | X - - - |
|pull request| - 2 approvals required - build passing - PR contains description (+ screenshot or gif if applicable) - PR always rebased on master - delete remote branch after merge|X X X X X|

**Comment by UnHynek** [comment]
Irrelevant
