### ISSUE TITLE
PL [3.1.24] Camera not focusing after first scan - Android

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#39]
Camera is not focusing after user returns to scanner screen.

How to reproduce:

Open the app
Scan valid barcode from the closest distance possible ( e.g.1-2 cm), the camera should focus normaly and keep the picture sharp, after scan you are advanced to product screen
When on Product screen go back
Position the phone much further than in step 1 (e.g. 10-20cm)
Notice the camera is stuck on fixed focus from the previous scan
Video attached.

This happens on Samsung S8+ on Android 9 (OneUI 1.0)

JS packages updates which may have causes this (yarn lock and package json attached):

react-native-camera 3.22.0
react-native 0.62.0

**Comment by UnHynek** [comment]
Irrelevant
