### ISSUE TITLE
PL [3.1.25] Improve Android build/signing process

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#40]
-set path and name for output APK file (to have it on more convenient place)
-use keychain or env to store keystore file and passwords for android build
-bundle assets to release build properly (seems like currently assets may not be linked at all)
 
helpful links:

https://pilloxa.gitlab.io/posts/safer-passwords-in-gradle/

https://medium.com/@ywongcode/building-multiple-versions-of-a-react-native-app-4361252ddde5

https://medium.com/@master13sust/generate-a-signed-apk-from-react-native-project-fe1ed627186e

(http://facebook.github.io/react-native/docs/signed-apk-android.html)

**Comment by UnHynek** [comment]
Irrelevant
