### ISSUE TITLE
On invalid serial number error does not shows scanned data

### ISSUE THREAD

**Issue by adiganga2002** [PharmaLedger-IMI/epi-workspace#418]

**Comment by adiganga2002** [comment]
![image](https://user-images.githubusercontent.com/38322305/139692243-fca0a66c-8c60-458a-82fa-724a8bfa9cbb.png)

**Comment by rite2bala** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/44022980/142865944-3d7246cb-3fed-45ba-aa6e-9503ad75b4bd.png">


We face a similar issue when validation settings fails 

We are unable to see any details about the product which was scanned..
