### ISSUE TITLE
Leaflet language upload is only possible in DE and EN, needs to be expanded to major languages

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#421]

**Comment by rite2bala** [comment]
[list-official-languages-country_en.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/7494577/list-official-languages-country_en.pdf)


attaching list of official EU languages

**Comment by salboaie** [comment]
@adiganga2002  Add all major European Languages (countries)
