### ISSUE TITLE
Import Logs needs a filter, otherwise we can't handle real volume of product and batch data

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#422]
Import logs for product and batches needs a filter
by default: show only the last 10 products or batches

User can change filter to select based on 
product / batch (item code)

in a later stage we can define more options. 

If we don't use such filters, the wallet gets slow and the import testing a nightmare.

**Comment by salboaie** [comment]
Planed for end of November/ Beginning of December
