### ISSUE TITLE
PL [3.1.28] Update React Native and project dependencies

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#43]
AC:

React Native updated to the latest version (0.62.0)
TypeScript updated to the latest version (3.8.3)
All other project dependencies updated to the latest version
iOS dev/prod mobile app still works
Android dev/prod mobile app still works
 
References

RN upgrade helper https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.0
Flipper RN docs https://github.com/facebook/flipper/blob/4297b3061f14ceca4d184aa3eebd0731b5bf20f5/docs/getting-started.md#setup-your-react-native-app
RN upgrade helper (Xcode update) https://github.com/react-native-community/upgrade-helper/issues/191
Xcode undefined symbol issue https://github.com/react-native-community/upgrade-support/issues/25

For every product backlog item:
| rule | description| status |
| --------------- | --------------- | --------------- |
| Task description| add at least short description about the task| ✅|
| Acceptance criteria |clear description (bullet points) what is output of the task (output of team refinement) | ✅ |
| team engagement | one person/pair/team (list names in case of more than 1 person) | 1+ |
|task reviewed by at least 1 peer| acceptance criteria passing| X|

| ruler | description | status |
| --------------- | --------------- | --------------- |
| branch created | - branch with correct type (feature/bugfix/...) - branch name contains JIRA reference | X |
| tests | - tested manually - unit tests implemented if applicable (team agreement) - integration/E2E tests for finished feature if applicable (team agreement) | X - - |
| sdlc | if the task covers acceptance criteria from requirement add test case(s) to SIT documentation -technical documentation updated (DCS) if applicable (team agreement | - - |
| coding standards | static analysis (linter, sonarQ) passing | X|
| development practices | commits contain reasonable message - logging enhanced - monitoring updated - analytics added/updated | X - - - |
|pull request| - 2 approvals required - build passing - PR contains description (+ screenshot or gif if applicable) - PR always rebased on master - delete remote branch after merge|X X X X X|

**Comment by UnHynek** [comment]
Irrelevant

**Comment by UnHynek** [comment]
Irrelevant
