### ISSUE TITLE
Recalled batch does not show the leaflet after setting change

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#434]
Steps to recreate the issue:
1. Create a product 
2. Create a batch 
3. Scan the 2d matrix
Observe that product is recalled and the does not show the leaflet

4. update product settings to show the leaflet even when  product is recalled

5. Scan the data matrix again 
- 
Observe that the Leaflet does not show  in this case inspite of updating  the product status 

Does this mean that the product setting is status is still being fetched from first scan ?

In order to test this - I opened another session of leaflet wallet in another browser -
I was able to scan and get the expected response.

**Comment by rite2bala** [comment]
[Screen Recording 2021-11-11 at 2.48.28 PM.mov.zip](https://github.com/PharmaLedger-IMI/epi-workspace/files/7519241/Screen.Recording.2021-11-11.at.2.48.28.PM.mov.zip)


on the left side of the screen - it is the session of leaflet wallet opened before updating the settings on product 

on the right side of the screen - it is the session of leaflet wallet opened after updating the settings on the product.

**Comment by rite2bala** [comment]
Continuation to the same issue:

When a expired batch is scanned - the mobile wallet shows the correct output that the batch has exprired

when the expiry date of the  same batch is modified to a new date - and we use the same mobile wallet session - it still shows that the batch is expired and displays the old expiry date in the "details" button

**Comment by adiganga2002** [comment]
This could be related to refresh period (can be changed in settings, default is 3600 sec)
