### ISSUE TITLE
Home Screen - menu does not close on clicking home

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#435]
In the new UI - There is a general confusion on why the history screen is the home page .. because of this confusion, the users tend to click on the "Home" button from the menu on the top left corner of screen.. 

When they click on the Home  the menu does not close .. 
this causes confusion and makes the user feel that the app is stuck. 

Steps to reconstruct:
1. Open the leaflet wallet
2. Scan a product 
3. Go back to home page  -- now it has history items with list of products 
4. Now open the menu and click on the "Home"
Now its observed that the menu does not close and gives an impression that the app is stuck

Could you configure the settings tab to close the menu when the same page is clicked?

Please let me know if the description is not clear.
Thank you

**Comment by denypatrascu** [comment]
This issue was fixed.

Commit: https://github.com/PharmaLedger-IMI/leaflet-ssapp/commit/aa8dfeed12164550c7b5f35ca6155d43c6d59b51
