### ISSUE TITLE
PL [3.1.30] CI: Jenkins integration with Webex Teams

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#45]
Send messages from Jenkins pipeline to Webex Teams space which will inform developers about below mentioned things.

AC:

Webex Teams "Bazinga Bot" user 
Webex Teams "Bazinga PRs / builds" space 
Jenkins pipeline sending these types of notifications:
pull request created 
send notification only when build of PR was successful
build of PR failed
inform only author of PR
reason of failure, PR link, Jenkins log link
build of develop / master failed 
successful build of develop / master branch 

For every product backlog item:
| rule | description| status |
| --------------- | --------------- | --------------- |
| Task description| add at least short description about the task| ✅|
| Acceptance criteria |clear description (bullet points) what is output of the task (output of team refinement) | ✅ |
| team engagement | one person/pair/team (list names in case of more than 1 person) | 1+ |
|task reviewed by at least 1 peer| acceptance criteria passing| X|

| ruler | description | status |
| --------------- | --------------- | --------------- |
| branch created | - branch with correct type (feature/bugfix/...) - branch name contains JIRA reference | X |
| tests | - tested manually - unit tests implemented if applicable (team agreement) - integration/E2E tests for finished feature if applicable (team agreement) | X - - |
| sdlc | if the task covers acceptance criteria from requirement add test case(s) to SIT documentation -technical documentation updated (DCS) if applicable (team agreement | - - |
| coding standards | static analysis (linter, sonarQ) passing | X|
| development practices | commits contain reasonable message - logging enhanced - monitoring updated - analytics added/updated | X - - - |
|pull request| - 2 approvals required - build passing - PR contains description (+ screenshot or gif if applicable) - PR always rebased on master - delete remote branch after merge|X X X X X|

**Comment by UnHynek** [comment]
Irrelevant
