### ISSUE TITLE
Native App does not work on the ePI QA

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#450]
It is observed that the native apps released on 12th Nov do not work with the  ePI QA environment. 

The app is designed to switch between the networks. 

It was discussed with the dev team and we identified that this issue is due to missing configuration in the ePI QA:

More specifically , this is an issue in the configuration on the ePI QA BDNS. 
https://epiqa.westeurope.cloudapp.azure.com/external-volume/config/bdns.hosts

After further discussion with the team, it was identified that  in order to make the new changes , there would be an impact on the users of the ePI QA environment:

**Impacts would be - not limited to:**
1. Down time for refresh and restarting the Kubernetes cluster  -- Demos will not be able to take place during this time 

2. Deletion of existing user data - 
Post re-configuration, the Users will not be able to retrieve existing accounts and data. 
Users will have to re-create the entire test data. 

**Decision:** -- last update 18th Nov 2021
1. Since we have a few demos scheduled for the week - we will be performing the refresh early next week tentatively

2. Need alignment with the team to consider demo schedules so that demos are not impacted.

**Comment by kpratihast** [comment]
Native app needs configuration change and new release to be made available once fixed. @asaccool - Please add more details related to what needs to be changed.

**Comment by asaccool** [comment]
The last mobile build was done in middle of nov. The current epiqa configuration was done in december. This configs needs in sunc in order to be able to scan products from mobile native app. 
current tests failed because the mobile app doesn’t know information about the vault.qa.nvs domain which was decided and configured in defember.

**Comment by salboaie** [comment]
Actually there is a mistake in the configuration in the epiqa:  https://epiqa.westeurope.cloudapp.azure.com/dsu-fabric-wallet/loader/environment.js
Correct values are:  
 "epiDomain":  "epiqa",   "epiSubdomain":  "epiqa.nvs"
