### ISSUE TITLE
Read only user is able to make changes

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#453]
Environment: Novartis ePI QA

Steps to recreate the issue:

1. Create a user account on Enterprise wallet
2. Add the user to Demiurge account on the ePI Read Group
3. The enterprise wallet account refreshes and displays the enterprise wallet home page 
4. go to products page 
5. make a change on any one of the existing products  and save 

the save is successful and the product is really updated. 

Could you please check how read only user is able to make changes?

Please contact me for more information like account details which I used to test it

**Comment by adiganga2002** [comment]
Read only group was removed for the moment.
