### ISSUE TITLE
Urgent issue: unable to set values in ePI PWA

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#454]
Hi, 
Requesting your assistance on an urgent item. 
We downloaded the PWA for iPhone and tried to setup the scanning parameters like network and scandit key. 
It is observed that the field does not save. 

Steps to reconstruct the issue:

1. Delete all old version of the app on iPhone 
2. Open the ePI QA website incognito
3. Install the new ePI mobile wallet app
4. Open the ePI mobile app - PWA from Home Screen 
5. Try to go to settings tab and edit the network setup 
change it from epi to epiqa

it is observed here that the save button  does not change to "edit"  showing that the configuration is saved. 

6. exit from the settings menu and re-open the settings 
it is observed that the network setup continues to show epi

7. Same issue for scandit setup key field as well 

iPhone model : iPhone 8
iOS: 15

Could you please resolve this issue at the earliest as it effects upcoming demos

**Comment by adiganga2002** [comment]
Checked with @rite2bala, could not be reproduced. Will keep watching it.
