### ISSUE TITLE
Web App: Scandit camera does not open second time 

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#455]
HI , 

We are facing an issue with accessing the scandit camera on the webapp 

Steps to recreate the error 
1. Open Mobile Wallet app 
2. open the settings and add the scandit key in the relevant textbox
3. Return back to home  screen 
4. click on scan 
5. Scandit camera opens up 
6. Scan a data matrix 

7. go back and click on "scan"  to open the camera a second time 
you would see that the camera is stuck at this

<img width="534" alt="image" src="https://user-images.githubusercontent.com/44022980/142848611-3dba6eba-9449-45bd-a6c9-e2e01e219f1a.png">

the camera is turned on but image is not displayed. 

when any data matrix code is put in front of the camera - it works 

but without showing the image stream 

I have tried this on MacBook Pro and in phone in the Web app.

Facing same issue. 

Please check and fix at earliest.

**Comment by denypatrascu** [comment]
Fixed since: https://github.com/PharmaLedger-IMI/leaflet-ssapp/commit/55470f211de3f3b2a32792a4671cc666f55303ef
