### ISSUE TITLE
DRA1-UCA-EP03-US02 Scalability

### ISSUE THREAD

**Issue by amanuel95** [PharmaLedger-IMI/epi-workspace#46]
**As a Manufacturer**
 
**I want to** have a solution that is scalable
 
**So That** all manufacturers can use the platform

 
**User Story Rationale/ Examples:**
This user story relates to the resolution of the GTIN/ NTN. It is important that the GTIN/ NTIN resolver resolves quickly (see User Story 3.3.1) regardless of the number manufacturers connected to the system or the number of barcode scans taking place etc. The solution must support an increasing number of users without detracting from the performance.
The following should be considered as part of the overall design but for MVP 1 it would not be relevant:
·         Administrative scalability: The ability for an increasing number of organizations or users to access a system
·         Functional scalability: The ability to enhance the system by adding new functionality without disrupting existing activities
·         Geographic scalability: The ability to maintain effectiveness during expansion from a local area to a larger region
·         Load scalability: The ability for a distributed system to expand and contract to accommodate heavier or lighter loads, including, the ease with which a system or component can be modified, added, or removed, to accommodate changing loads
·         Generation scalability: The ability of a system to scale by adopting new generations of components
·         Heterogeneous scalability: The ability to adopt components from different vendors
 
The dimensions of interaction traffic over the system involve:
•    The ability to receive/link to content from suppliers in the order of magnitude of 1000s/10,000s (# suppliers, #products)
•    Consumers of content will relate to user traffic in  the scale of 100,000s (# patients actively accessing content over a global footprint)
•    The sun will never go down on this system. Needs to be 24/7
 
An analogy at the time of writing these requirements is Amazon.com, Youtube.com. Top 5% of websites in the globe. Note: this is the requirement at a point in time when the system is fully deployed globally.

**Comment by mppub** [comment]
We have thoroughly review this story in our internal planning and come up with those actions to take - each of them can be thought as a separate epic - to be further split into more granular tasks(user stories).

- Separation of Api-sever & Brick storage (crucial for further advance in scaling and development in general). Issue:  #63 
- Set up Shared Environments:  Test network& Production network (crucial for development and testing of scaling)
- Blockchain node & Privatesky node modularization 
- Set up logging / monitoring / analytics over the network
- Smart contracts review (in terms of scalability)
- Create Testing strategy for scalability → apps, backend(blockchain, dsu, storage...), frontend,...
