### ISSUE TITLE
Implement 3 options for the wallet login (existing, PIN based, no PIN)

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#463]

**Comment by salboaie** [comment]
- middleware in APIHub named  "secrets", persisting secrets for SSO logedin users
- endpoints 

- GET /getSecret/userId/appName/
- PUT /putSecret//userId/appName/

For login mode "pin" and "ssodirect" WalletDB is created using a random secret (256 bits) associated with currently logged userId  and for the current wallet type (appName)

**Comment by adiganga2002** [comment]
new modes are: sso-direct and sso-pin
