### ISSUE TITLE
When either Leaflet or SMPC is uploaded at the time of product / batch creation - the mobile wallet does not show any details about the type of the document - it just opens the document directly

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#487]
As compared to the case when both Leaflet & SMPC are uploaded, there's a drop-down at the top in the mobile wallet, which enables user to select type of document to view.

Patients would be curious to know what is the type (Leaflet / SMPC) of the document they are currently viewing in case only single type of document is available.

1. Create a product and upload either Leaflet or SMPC 
2. Create a batch for this product 
3. Scan the product on the mobile app 

In the mobile wallet, on successful scan, there's no way for user to know if he/she is viewing Leaflet or SMPC for the above batch.

**Comment by salboaie** [comment]
This input  should be sent to the UX team @kpratihast

**Comment by maherpa2** [comment]
This will be managed as part of the UX design work. We need to make it easy and clear to patients what they are looking at.

**Comment by adiganga2002** [comment]
closing as new design focuses on patient leaflet
