### ISSUE TITLE
Add video links also in leaflets & batches.

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#495]
- Select a  video to display in this order:  leaflets , batch, product
- create a separate message (in mapping engine) type for integration of the video links (they could come from a different system of records)

**Comment by salboaie** [comment]
When done, inform Sonja to update the documentation

**Comment by adiganga2002** [comment]
created new message type  "VideoSource" with following structure: 

{
 "messageType" : "VideoSource",
  "messageTypeVersion" : 0.1,
  "senderId" : "NOVARTIS_P75_010",
  "receiverId" : "ePI_DSU_NOVARTIS",
  "messageId" : "00012856374589",
  "messageDateTime" : "2021-04-27T10:12:12CET",
  "videos": { 
         "productCode": "234534234234 *mandatory",
         "batch":"B123D *optional",
         "source": "*optional base64 encoded",
         "sources":[{documentType:"leaflet | smpc", lang: en, source: "*optional base64 encoded"}]
     }
}
