### ISSUE TITLE
Support for embedded code videos

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#497]

**Comment by salboaie** [comment]
Support embedded codes (basically iframes, like for example Kaultura) [ recognize i is an URL or an iframe code]

**Comment by adiganga2002** [comment]
For the moment for kaltura embeded videos just iframes embed option works fine. 
![image](https://user-images.githubusercontent.com/38322305/149311472-f7495726-d833-47fd-bd7e-6b645808f06f.png)
