### ISSUE TITLE
In Enterprise Wallet, the main screen title doesn't match with highlighted side menu options

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#513]
As shown in image below, on selecting Product as main screen, Batch is still highlighted in bold font on side menu bar. Both should be in sync ideally. 

![image](https://user-images.githubusercontent.com/20087001/149140853-c93bbfb9-2b04-40e1-8202-0f76687a4cea.png)

**Comment by denypatrascu** [comment]
Iterations: 
[1] https://github.com/webcardinal/webcardinal-core/commit/8f34f123313e56271ef141a4889cb33244fb61d4
[2] https://github.com/webcardinal/webcardinal-core/commit/a502351fb186f515f75fe12d2b00ab99f0a6a469

Modifcations were mainly made in `webc-app-menu` and `webc-app-router` components of WebCardinal.
