### ISSUE TITLE
Revised title for SMPC and Leaflet is not reflected in the Mobile App

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#515]
Title for SMPC and Leaflet doesn't get reflected in Mobile App when changed from Products page. 

Steps to reproduce error:
1. Go to Product, Edit - change Leaflet title to "Patient Information ePI" and SMPC title to "SMPC test"
2. Go to Mobile Wallet, scan data matrix
3. Title for SMPC still shows as  "SMPC" and for leaflet it is "Leaflet"

**Comment by nhrishi** [comment]
We need to consider different languages apart from English. This should be revisited.

**Comment by nhrishi** [comment]
This is no longer relevant to MVP1
