### ISSUE TITLE
brickMapController is undefined

### ISSUE THREAD

**Issue by skutner** [PharmaLedger-IMI/epi-workspace#519]
iframeBoot.js:10916 Uncaught TypeError: Cannot read properties of undefined (reading 'getBrickEncryptionKeySSI')
    at Object.apply (iframeBoot.js:10916:41)
    at Service.brickDataExtractorCallback (iframeBoot.js:7997:66)
    at iframeBoot.js:13892:22
    at checkBrickDataIntegrity (iframeBoot.js:13884:17)
    at iframeBoot.js:13887:13
    at iframeBoot.js:33152:17
    at IDBTransaction.transaction.oncomplete (iframeBoot.js:33426:21)

**Comment by skutner** [comment]
Appears intermitently

**Comment by vladbalmos** [comment]
Most probably related to https://github.com/PrivateSky/bar/pull/8
I might have missed a case where the DSU must wait for any pending operations to finish before refreshing the DSU. 
@skutner Can you provide a set of steps for getting "multiple pending messages in mq"? 
Which app from `fgt-workspace`? MAH Wallet, Wholesaler or Pharmacy?
Thanks

**Comment by skutner** [comment]
steps to replicate

git clone https://github.com/PharmaLedger-IMI/fgt-workspace.git
git checkout refs56_didUpdate
npm run dev-install
npm run server
npm run build-all
npm run environment-trace

open http://localhost:8080

![Screenshot from 2022-01-25 11-06-12](https://user-images.githubusercontent.com/35995331/150946324-855d1872-e0d2-461f-943b-8a5699479ee5.png)

copy the Id for fgt-mah-wallet
open MAH wallet

paste the id in field Registered Marketing Authorization Holder Id: and click LOGIN
![Screenshot from 2022-01-25 11-10-35](https://user-images.githubusercontent.com/35995331/150946777-372da5d4-cd0b-4a1b-9340-bb1e634edb09.png)

in fgt wallet clock on products and select a product from the list 
![Screenshot from 2022-01-25 11-06-55](https://user-images.githubusercontent.com/35995331/150946889-8dd90e1e-d1e4-4331-a699-a043da24fc48.png)

click on Quarantine Batch 
![Screenshot from 2022-01-25 11-07-00](https://user-images.githubusercontent.com/35995331/150947056-8db724e1-078b-42b9-b2fe-d41a73f7863a.png)

click on COMISSION BATCH
![Screenshot from 2022-01-25 11-07-20](https://user-images.githubusercontent.com/35995331/150947160-b7947408-caec-47b4-b86c-fe789d4af7f8.png)

go to http://localhost:8080
Copy the Id for the fgt-wholesaler-wallet
![Screenshot from 2022-01-25 11-15-03](https://user-images.githubusercontent.com/35995331/150947712-cf0671f7-8613-4a88-83fe-76ef1f883e2a.png)

open the Wholesaler wallet and copy the id in the field Registered Wholesaler Id and click login
![Screenshot from 2022-01-25 11-15-13](https://user-images.githubusercontent.com/35995331/150947903-244a4140-f8c8-451e-a6ee-50d22807115b.png)

the error should appear in the browser console once the wholesaler wallet opens
