### ISSUE TITLE
Expiry data does not work as expected in the iOS mobile app

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#563]
Bug reported by kshitij

**Comment by salboaie** [comment]
We are observing strange behaviour with native iOS app as shown below. On scanning a code with Blockchain network is ‘epiqa’. The output of web app in iOS browser is expected output. Please look into this.

![image](https://user-images.githubusercontent.com/1595518/153009556-3edc445c-7dcb-46f6-8aca-0fb7d99db8e9.png) 

With native iOS app:                                                                        

![image](https://user-images.githubusercontent.com/1595518/153009575-977002cc-76ef-4de1-a007-b847941d45df.png)
With web app in iOS browser:
![image](https://user-images.githubusercontent.com/1595518/153009585-7a6b9404-7fd1-4602-b5bd-d899bace5785.png)

**Comment by adiganga2002** [comment]
Hi, 
I can't reproduce this issue. Bellow are the screenshots from iphone and browser.
![image](https://user-images.githubusercontent.com/38322305/153198023-03cc8741-0c4c-4e9d-bd79-6e8679884852.png)
![IMG_0D897BC3DBBA-1](https://user-images.githubusercontent.com/38322305/153198421-2c7255c0-0e34-4891-b916-66ded6e915b5.jpeg)
