### ISSUE TITLE
Clarification on the features flags

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#567]
We require a classification of the features
- MOBILE_SWITCH  : hidden feature flags  for mobile apps (enabling/disabling feature configuration at the build for mobile apps)
- BACKEND_SWITCH  : backend feature flags configured during of the backend installation (hidden feature for integration and dsu-fabric)
- BATCH_FEATURE  , PORDUCT_FEATURE feature flags from DSU-Fabric UI (mostly existing)
- MOBILE_DEV_SWITCH  behavior flags in the mobile apps (for development builds mostly, enabling new/changed behaviors compared with the standard behavior)
- MOBILE_ADVACED  feature flags from options in the mobile app (feature disabled by default -but possible to be enabled by the power users)
- MARKET_SPECIFIC_SWITCH feature flags that are per market: configuration at the level of DSU-Fabric that disable some features in the mobile app when a leaflet is associated with a specific market
- MOBILE_FEATURES_COMPANY_ENABLED ?? features configured by the company for all their products... ?
- ABTESTING_FEATURES enabled only for a specific set of users  (A/B testing?)

**Comment by salboaie** [comment]
We have to create asap a list of features flags that can be influence the ePI solution (based on the above classification).

**Comment by nhrishi** [comment]
This is no longer required and relevant.
