### ISSUE TITLE
https://github.com/PrivateSky/tutorial-workspace cd cardinal && npm run build-dossier Failed to retrieve BDNS hosts Error: socket hang up

### ISSUE THREAD

**Issue by jpluis** [PharmaLedger-IMI/epi-workspace#6]
Steps done:

```
jpsl@PDM-00781:~/tmp8$ git clone https://github.com/PrivateSky/tutorial-workspace
jpsl@PDM-00781:~/tmp8$ cd tutorial-workspace/
jpsl@PDM-00781:~/tmp8/tutorial-workspace$ npm install
jpsl@PDM-00781:~/tmp8/tutorial-workspace$ npm run server
```

On another terminal:

```
jpsl@PDM-00781:~/tmp8/tutorial-workspace$ date
qui 10 dez 2020 15:08:55 WET
jpsl@PDM-00781:~/tmp8/tutorial-workspace$ npm run build-all

> tutorial-workspace@1.0.0 build-all /home/jpsl/tmp8/tutorial-workspace
> node ./node_modules/octopus/scripts/setEnv --file=../../../env.json "node ./node_modules/octopus/scripts/run build"

Environment updated accordingly to env file passed as argument.
Preparing to execute cmd node ./node_modules/octopus/scripts/run build
Looking for configuration file at path /home/jpsl/tmp8/tutorial-workspace/octopus.json
[Octopus] Start checking build...
[Octopus] Found 5 build...
[Octopus] Running tasks for: [0] cardinal-wallet-build
Running command: cd cardinal && npm run build-dossier

> cardinal@0.1.2 build-dossier /home/jpsl/tmp8/tutorial-workspace/cardinal
> node ./bin/build_dossier.js

Logger not available, using console
Fix the fixMe to not display on console but put in logs
Redefining require for node
Creating a new Dossier...
Failed to retrieve BDNS hosts Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at Socket.socketOnEnd (_http_client.js:459:23)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}
...
```

**Comment by TiagoVenceslau** [comment]
if we copy the external-volume folder from epi-workspace, this error stops happening but then on build-all we get:

> tutorial-workspace@1.0.0 build-all /home/tvenceslau/workspace/pharmaledger/tutorial-workspace
> node ./node_modules/octopus/scripts/setEnv --file=../../../env.json "node ./node_modules/octopus/scripts/run build"

Environment updated accordingly to env file passed as argument.
Preparing to execute cmd node ./node_modules/octopus/scripts/run build
Looking for configuration file at path /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/octopus.json
[Octopus] Start checking build...
[Octopus] Found 5 build...
[Octopus] Running tasks for: [0] cardinal-wallet-build
Running command: cd cardinal && npm run build-dossier

> cardinal@0.1.2 build-dossier /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/cardinal
> node ./bin/build_dossier.js

Logger not available, using console
Fix the fixMe to not display on console but put in logs
Redefining require for node
Dossier updating...
Build process of <cardinal> finished. Dossier's KeySSI: BBudGH6ySHG6GUHN8ogNrTWbxfjwH8qUX6Av7aaDBRMdF1Sf3WjWpHZxyz4Wr1x7ZCYBneidS8FDBBfXbMqzYEZK5
[Octopus] Running tasks for: [1] blue-fluorite-theme-wallet-build
Running command: cd themes/blue-fluorite-theme && npm run build-dossier

> blue-florite-theme@1.0.0 build-dossier /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/themes/blue-fluorite-theme
> node ./bin/build_dossier.js

Logger not available, using console
Fix the fixMe to not display on console but put in logs
Redefining require for node
Dossier updating...
Build process of <blue-fluorite-theme> finished. Dossier's KeySSI: BBudGH6ySHG6GUHN8ogNrTWc4ayvwiRbTgrodycNvyZa1XGDvtjfXWN3gGpqDcHjkHknYmMd88eXod1dboQLNDevj
[Octopus] Running tasks for: [2] tutorial_bind_to_menu-wallet-prototype
Running command: cd menu-wallet-prototype && npm run build

> menu-wallet@0.0.1 prebuild /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/menu-wallet-prototype
> node ./node_modules/octopus/scripts/run prebuild

Looking for configuration file at path /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/menu-wallet-prototype/octopus.json
[Octopus] Start checking prebuild...
[Octopus] Found 1 prebuild...
[Octopus] Running tasks for: [0] PSK bundles
Running command: node ../privatesky/psknode/bin/scripts/pskbuild.js --projectMap=./build/build.json  --prod=true --output=./code/constitution
Found project map ./build/build.json
Reading targets and their dependencies list...
Cleaning output folder
Starts rebuilding
Building target domain
domain done
Finished rebuilding
Start copying ../privatesky/psknode/bundles/pskruntime.js to folder code/constitution/pskruntime.js
Start copying ../privatesky/psknode/bundles/webshims.js to folder code/constitution/webshims.js
Start copying ../privatesky/psknode/bundles/bindableModel.js to folder code/scripts/bundles/bindableModel.js
Start copying ../privatesky/psknode/bundles/iframeBoot.js to folder code/scripts/bundles/iframeBoot.js
Start copying ../privatesky/psknode/bundles/pskruntime.js to folder code/scripts/bundles/pskruntime.js
Start copying ../privatesky/psknode/bundles/webshims.js to folder code/scripts/bundles/webshims.js
Finishing checking tasks...

> menu-wallet@0.0.1 build /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/menu-wallet-prototype
> node ./bin/build.js

Logger not available, using console
Fix the fixMe to not display on console but put in logs
Redefining require for node
Dossier updating...
Build process of <menu-wallet-prototype> finished. Dossier's KeySSI: BBudGH6ySHG6GUHN8ogNrTWbNH5HnBh3dUGGinc5RBUWG3xVDvo8wb5yRngjdmDPMpB2UC7GEFdg4Fv1hifznwW23
Start copying ./menu-wallet-prototype/seed to folder ./web-server/tutorial/wallet-template/seed
[Octopus] Running tasks for: [3] tutorial_bind_to_profile-ssapp-prototype
Running command: cd profile-ssapp-prototype && npm run build

> profile-app@1.0.0 prebuild /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/profile-ssapp-prototype
> node ./node_modules/octopus/scripts/run prebuild

Looking for configuration file at path /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/profile-ssapp-prototype/octopus.json
[Octopus] Start checking prebuild...
[Octopus] Found 1 prebuild...
[Octopus] Running tasks for: [0] PSK bundles
Running command: node ../privatesky/psknode/bin/scripts/pskbuild.js --projectMap=./build/build.json  --prod=true --output=./code/constitution
Found project map ./build/build.json
Reading targets and their dependencies list...
Cleaning output folder
Starts rebuilding
Building target domain
domain done
Finished rebuilding
Start copying ../privatesky/psknode/bundles/pskruntime.js to folder code/constitution/pskruntime.js
Start copying ../privatesky/psknode/bundles/webshims.js to folder code/constitution/webshims.js
Start copying ../privatesky/psknode/bundles/bindableModel.js to folder code/scripts/bundles/bindableModel.js
Start copying ../privatesky/psknode/bundles/pskruntime.js to folder code/scripts/bundles/pskruntime.js
Start copying ../privatesky/psknode/bundles/webshims.js to folder code/scripts/bundles/webshims.js
Finishing checking tasks...

> profile-app@1.0.0 build /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/profile-ssapp-prototype
> node ./bin/build

Logger not available, using console
Fix the fixMe to not display on console but put in logs
Redefining require for node
This function is obsolete. Doing nothing
Endpoint change detected. Creating a new Dossier...
Build process of <profile-ssapp-prototype> finished. Dossier's KeySSI: 3JstiXPCRm1hcgG352y3gkciQUxeKs6EfHkw469H5BwAC3pgjb6rJeY7vgyJsecDTHbZRyAauiNtH1QKVsw5bvko

> profile-app@1.0.0 postbuild /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/profile-ssapp-prototype
> node ./node_modules/octopus/scripts/run postbuild

Looking for configuration file at path /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/profile-ssapp-prototype/octopus.json
[Octopus] Start checking postbuild...
[Octopus] Found 1 postbuild...
[Octopus] Running tasks for: [0] post build clean up
Finishing checking tasks...
Start copying ./profile-ssapp-prototype/seed to folder ./web-server/tutorial/apps/profile-ssapp/seed
[Octopus] Running tasks for: [4] tutorial_bind_to_ssapp-minimal-app
Running command: cd ssapp-minimal-app && npm run build

> ssapp-template@1.0.0 prebuild /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/ssapp-minimal-app
> node ./node_modules/octopus/scripts/run prebuild

Looking for configuration file at path /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/ssapp-minimal-app/octopus.json
[Octopus] Start checking prebuild...
[Octopus] Found 1 prebuild...
[Octopus] Running tasks for: [0] PSK bundles
Running command: node ../privatesky/psknode/bin/scripts/pskbuild.js --projectMap=./build/build.json  --prod=true --output=./code/constitution
Found project map ./build/build.json
Reading targets and their dependencies list...
Cleaning output folder
Starts rebuilding
Building target domain
domain done
Finished rebuilding
Start copying ../privatesky/psknode/bundles/pskruntime.js to folder code/constitution/pskruntime.js
Start copying ../privatesky/psknode/bundles/webshims.js to folder code/constitution/webshims.js
Start copying ../privatesky/psknode/bundles/pskruntime.js to folder code/scripts/bundles/pskruntime.js
Start copying ../privatesky/psknode/bundles/webshims.js to folder code/scripts/bundles/webshims.js
Finishing checking tasks...

> ssapp-template@1.0.0 build /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/ssapp-minimal-app
> node ./bin/build.js

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module './../../privatesky/psknode/bundles/csbBoot.js'
Require stack:
- /home/tvenceslau/workspace/pharmaledger/tutorial-workspace/ssapp-minimal-app/bin/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/tvenceslau/workspace/pharmaledger/tutorial-workspace/ssapp-minimal-app/bin/build.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/tvenceslau/workspace/pharmaledger/tutorial-workspace/ssapp-minimal-app/bin/build.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssapp-template@1.0.0 build: `node ./bin/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssapp-template@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tvenceslau/.npm/_logs/2020-12-10T15_26_22_892Z-debug.log
Start copying ./ssapp-minimal-app/seed to folder ./web-server/tutorial/apps/ssapp-minimal-app/seed
Finishing checking tasks...

**Comment by alexgheorghiu** [comment]
No longer bugs on tutorial-workspace's [6ab7bf35309ee279dc941dc247915f1348b2edd5](https://github.com/PrivateSky/tutorial-workspace/commit/6ab7bf35309ee279dc941dc247915f1348b2edd5)
