### ISSUE TITLE
Re-Onboarding of Novartis to the DEV network

### ISSUE THREAD

**Issue by lukasosterheider** [PharmaLedger-IMI/epi-workspace#603]
Novartis will rejoin the DEV network with a new IT infrastructure setup. Thereby, only the blockchain node will rejoin the network. The application / API Hub & Brick Storage will be untouched.

What will stay the same?
- everything else besides the blockchain node IP addresses

What will change?
- Novartis blockchain ingress IP address
- Novartis blockchain egress IP address

What is required by the other companies?
- Update the enode with the new IP address
- Update the egress whitelisting (firewall)
- Update the ingress whitelisting (firewall, loadbalancer)

**Date & Time - Participant adding of new IPs: by 16.03.2022**

**Date & Time - Novartis blockchain change: TBD**

Test cases:
- Check the blockchain generated log files - on Novartis and other companies side

**Date & Time - Novartis eth adapter change: TBD**
**Date & Time - Participant removal of old IPs: TBD**

Test cases:
- Re-run the (at least some) test cases as in October 2021 - after full completion of Novartis infrastructure change

**Comment by lukasosterheider** [comment]
Partcipants whitelisted new IPs and changed enode IP:

- [ ] Bayer
- [ ] GSK
- [ ] JnJ
- [ ] MSD
- [ ] Romsoft

**Comment by RakeshL-JnJ** [comment]
I assume validator remains same.

**Comment by RakeshL-JnJ** [comment]
In case you are getting device not having space error while running pod issue then update storage value in '00-00-quorum-persistent-volumes.yaml'  and apply changes and then redeploy. We modified 10x like 40Gi and 10Gi.

**Comment by RakeshL-JnJ** [comment]
Whitelisting and enode update done for J&J.

**Comment by sumanxp** [comment]
enode update done for GSK

**Comment by JanJeker** [comment]
Short Update from NVS side:
confirm GSK and 2 nodes from Romsoft are working.
MSD is not online.
JNJ we need to whitelist new static IP, we lacked the information about the new Network Load Balancer.
Bayer we have seen that our company Loadbalancer transfers the traffic to a different firewall. on that firewall, the rules need to be synchronized.

**Comment by JanJeker** [comment]
quick update. we see Romsoft, GSK and Bayer.
all the whitelisting and mirroring of Firewalls have been completed.
we check, what can be done for JNJ

**Comment by lukasosterheider** [comment]
> quick update. we see Romsoft, GSK and Bayer. all the whitelisting and mirroring of Firewalls have been completed. we check, what can be done for JNJ

Thanks @JanJeker ! Then we will close this issue for now.
