### ISSUE TITLE
Api Hub request logging - Api Server use method - callback being called several times

### ISSUE THREAD

**Issue by TiagoVenceslau** [PharmaLedger-IMI/epi-workspace#61]
With the changes shown in the meeting in this [fork](https://github.com/TiagoVenceslau/apihub/tree/request_logging) and with the following entry in the server's server.json file:
```
  "logging": {
    "enabled": true
  },
```
Example:
```
...
  "port": 8080,
  "storage": "../apihub-root",
  "logging": {
    "enabled": true
  },
  "preventRateLimit": true,
  "enableRequestLogger": true,
...
```
 for a basic request we get the output bellow, where:
* `x/y` means its running the middleware x of y registered middlewares;
* `Request handled in...`  means the callback has been called by the middleware x;
* any other output is cause by the acting middlewares (for instance, the logging middleware is the 3rd)

Should the callback be called so many times? I would expect only once, for the matching middleware (in this case it's 49: the '*' URL pattern)

```
0/52
- Request handled in 0 milliseconds
1/52
2/52
- Request handled in 1 milliseconds
[GET] /assets/images/cube.png
3/52
- Request handled in 3 milliseconds
4/52
5/52
6/52
7/52
8/52
9/52
10/52
11/52
12/52
13/52
14/52
15/52
16/52
17/52
18/52
19/52
20/52
21/52
22/52
23/52
24/52
25/52
26/52
27/52
28/52
29/52
30/52
31/52
32/52
33/52
34/52
35/52
36/52
37/52
38/52
39/52
40/52
41/52
42/52
43/52
44/52
45/52
46/52
47/52
48/52
- Request handled in 49 milliseconds
49/52
- Request handled in 52 milliseconds```

**Comment by joaoluis-pdm** [comment]
Although it does not explain the bug reported by @TiagoV-PDMFC, I've adapted @asaccool 's proposal in

https://github.com/PrivateSky/apihub/issues/2#issuecomment-773327944

Let me know if you want a pull request. (It is not blocking for us. Just to warm-up my JS...)

**Comment by joaoluis-pdm** [comment]
@asaccool  proposed a stop-watch solution in pull request.
In pull request https://github.com/PrivateSky/apihub/pull/3
