### ISSUE TITLE
Enterprise Wallet - Accept & Cancel button visibility issue on small screen resolution

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#628]
Reporter: Stindt, Meike <meike.stindt@takeda.com>

The "Accept" and "Cancel" buttons are not shown on the screen if the zoom is at 100% (probably depends on screen size) or higher and scrolling is not possible. The only options to access the button and get out of the screen is to change the zoom.

**Comment by adiganga2002** [comment]
Hi @kpratihast,
Can you provide screenshots?
