### ISSUE TITLE
Leaflet displayed when product is configured to not show it

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#629]
Reporter: Stindt, Meike <meike.stindt@takeda.com>

When the product is configured to not show the leaflet in case of a wrong expiry date, the leaflet is still displayed, even if the expiry check is executed and notifies the user that it is incorrect.

**Comment by adiganga2002** [comment]
Hi @kpratihast , @MeikeStindt ,
Can you please provide screenshots?
Thank you

**Comment by salboaie** [comment]
It indicates an issue with the current documentations or a wrong interpretation: "enable anti-counterfeiting check for this product" in the current interpretation does not affect serial number checks. @steinso2 please help us with the correct interpretation
