### ISSUE TITLE
Issue with scanning Invalid Serial Number

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#631]
Reporter: Stindt, Meike meike.stindt@takeda.com

When scanning and invalid serial number, the patient sees the message "failed to validate serial number" even if the serial number verification is disabled in the batch data and the authentication is disabled in the product data. 

Steps to reproduce: Scan a code with a wrong serial number while verification check is disabled

**Comment by adiganga2002** [comment]
Hi @MeikeStindt , @kpratihast,
Please provide some screenshots. Thank you.
