### ISSUE TITLE
Leaflet displayed even when display ePI flag is unchecked for SN in decommissioned list

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#632]
Reporter: Irene Wong <irene.wong@bayer.com>; Hartini Binti Abbas <hartinibinti.abbas.ext@bayer.com>

1.  Product setup with "SN is in Decommission list" ticked.  Both Leaflet & SMPC uploaded.
2. Batch is setup with a recall SN (000000000003).  "Enabled Incorrect Expiration Date Verification" & "Enable Expired Expiration Date Verification" are both unticked.
3. Scan Data matrix
4. Patient wallet shows both leaflet and SMPC and there is message "Decommissioned".
Test result expected that we cannot view Leaflet & SMPC.  Please confirm.

**Comment by adiganga2002** [comment]
Hi @kpratihast,  Irene Wong, Hartini Binti Abbas,
If I understand correctly in this case leaflet and smpc should be displayed as Product setup with "SN is in Decommission list" ticked - means show EPI.

**Comment by adiganga2002** [comment]
Closing as it's the right behavior
