### ISSUE TITLE
Patient Wallet - Finalise in-app message preference during combination scenarios

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#642]
In mobile app, the message order preference has to be finalised whenever a batch is scanned with combination scenarios like Recalled + Expired / Recalled + Incorrect Expiry Date / Recalled + SN Decommissioned, etc.

When a batch is configured such that it's both recalled and expired, the output is as shown below:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/20087001/160367728-d222ab41-2f0b-4dc3-bca1-216ffad4eba3.png)

Similarly, when a batch is recalled and a 2d data matrix with incorrect expiry date is scanned, output is as below:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/20087001/160367914-2ddd7426-1fd6-43a9-aacc-d7194a9c43d2.png)

**Comment by salboaie** [comment]
@steinso2 @nhrishi please take a decision on this order

**Comment by steinso2** [comment]
@salboaie @nhrishi 
For me it looks good that the batch recall is prioritized over the other scenarios. So what is the question?

**Comment by maherpa2** [comment]
This is fine. Batch Recall is priority over everything else.
