### ISSUE TITLE
Patient Wallet shows error message at times for a valid configured product-batch combination

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#647]
Intermittently, we get below output in Android emulator and real device on scanning a 2d data matrix. It works when we go back and scan the same image again

![20220329_160700](https://user-images.githubusercontent.com/20087001/160597790-c68e4587-fe97-4e0e-bf8e-47cdefa2c5b1.jpg)

**Comment by adiganga2002** [comment]
Hi @kpratihast,
I am not able to reproduce this, can you please provide device configuration ( android version) ? And if possible a screenshot with devtools console ?
