### ISSUE TITLE
Mobile App - Scan History page displays product name in proper case. However, on leaflet page, it's displayed as entered at time of configuration in enterprise wallet

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#661]
As displayed in leaflet view. Also, the blue shield icon gets shifted to extreme right if product name is long
<img width="365" alt="image" src="https://user-images.githubusercontent.com/20087001/161963384-39bdc45c-160b-4721-8cfe-965013b2f92c.png">

As displayed in Scan History page:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/20087001/161963214-7b08ab0f-ab11-43fe-88d6-436989aa5d0a.png">

**Comment by adiganga2002** [comment]
Removed capitalize form history page, display as it is inserted in enterprise wallet
