### ISSUE TITLE
SSO related observations

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#668]
Release - v1.1.2 & v1.3.1

Please refer to comments section for more details.

**Comment by adiganga2002** [comment]
HI @kpratihast, 
Please add comments.

**Comment by RakeshL-JnJ** [comment]
Few more observations:
1. For Demiurge wallet and Enterprise wallet user is shown as 'undefined'. Refer attached 'Demiurge-homePage-id-is-undefined-1.JPG' and 'Enterprise-wallet-homepage-id-is-undefined1.JPG'
![Demiurge-homePage-id-is-undefined-1](https://user-images.githubusercontent.com/82216409/164443603-8472e887-5b15-4867-98e2-0a00bc68f428.JPG)
![Enterprise-wallet-homepage-id-is-undefined1](https://user-images.githubusercontent.com/82216409/164443609-751638e0-ff00-473a-a40f-9029b73c37cd.JPG)
2. On Product edit getting error like Failed to get inherited cards (refer Enterprise-wallet-Product-edit-Dialogue-Failed-to-get-inherited-cards.JPG) and other bunch of errors(refer Enterprise-wallet-Product-edit-save-error-dialgoue.JPG)
![Enterprise-wallet-Product-edit-save-error-dialgoue](https://user-images.githubusercontent.com/82216409/164444068-d8f49306-e942-4bd0-bf9f-28c3a0553010.JPG)
![Enterprise-wallet-Product-edit-Dialogue-Failed-to-get-inherited-cards](https://user-images.githubusercontent.com/82216409/164444074-e5cc36f2-be53-4588-9200-664a4075b91a.JPG).
3. On deleting enterprise wallet user from ePI write group from Demiurge wallet, user rights are not revoked. User is able to see product or update product. Refer UserMgmt-Demiurge-writeGroup_And_Enterprise-wallet-user-home.JPG showing user in Demiurge and enterprise wallet. And user is deleted refer UserMgmt-Demiurge-writeGroup-User-Deleted_And_Enterprise-wallet-user-able-to-see-add-product.JPG but still user can edit product refer UserMgmt-Demiurge-writeGroup-User-Deleted_And_Enterprise-wallet-user-able-to-see-add-product-error.JPG
![UserMgmt-Demiurge-writeGroup-User-Deleted_And_Enterprise-wallet-user-able-to-see-add-product-error](https://user-images.githubusercontent.com/82216409/164444928-fe4e9783-3c5a-4d6e-8bc6-e81c0af6deb4.JPG)
![UserMgmt-Demiurge-writeGroup-User-Deleted_And_Enterprise-wallet-user-home-visible](https://user-images.githubusercontent.com/82216409/164444937-15e6699e-48ad-402c-b81e-8b4557e3bca8.JPG)
![UserMgmt-Demiurge-writeGroup_And_Enterprise-wallet-user-home](https://user-images.githubusercontent.com/82216409/164444939-e7768549-0452-42cc-b152-0ae1050f1711.JPG)
![UserMgmt-Demiurge-writeGroup-User-Deleted_And_Enterprise-wallet-user-able-to-see-add-product](https://user-images.githubusercontent.com/82216409/164444945-3b47f651-5af7-40ea-9f42-f291cf7869e8.JPG).
4. Product is not displayed in Leaflet wallet app. It shows 'Product code combination could not be resolved'. Refer leaflet-wallet-Valid-2D-Scan-Product-not-found.JPG, leaflet-wallet-recalled-2D-Scan-Product-not-found.JPG and leaflet-wallet-Decomissioned-2D-Scan-Product-not-found.JPG
![leaflet-wallet-Valid-2D-Scan-Product-not-found](https://user-images.githubusercontent.com/82216409/164445303-4612f01c-9305-4fe1-8c30-67f2ce6de139.JPG)
![leaflet-wallet-Decomissioned-2D-Scan-Product-not-found](https://user-images.githubusercontent.com/82216409/164445309-83bdfb3f-cae9-4460-a474-90036e221ad8.JPG)
![leaflet-wallet-recalled-2D-Scan-Product-not-found](https://user-images.githubusercontent.com/82216409/164445311-a9d2cf6e-e038-4667-b6f5-c9f80e15efef.JPG)
.

**Comment by RakeshL-JnJ** [comment]
Audit Requirement in Demiurge:
- User ID | Action (add/remove/update) | Group (Write/Admin) | Timestamp | who took action | Privileges (Assigned / Revoked in case more granularity given in future optional)
Assumption is user management only happens through Demiurge UI and no other way like API.
