### ISSUE TITLE
Divestment functionality - The mobile app still displays the old company owner name on the scanned product

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#68]
Scenario - 
1. Initiated a product transfer to the new company.
2. After a successful product transfer, I created a new batch with a new company. 
3. Scanned the product with a new 2D matrix for the new company and new batch.
4. The mobile app still shows the original  (old) company after scanning the new batch 2D matrix instead of a new one.

**Comment by steinso2** [comment]
we will all divestment scenarios, instead of adding bug tickets
