### ISSUE TITLE
Import JSON feature - in the JSON object, array of valid SNs accepts only string values but array of recalled and decomm. SNs accept both string and numbers

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#680]
Release - v1.1.2
Environment - Test Automation controlled browser
Feature - Import JSON on Batches page

the import feature errors out if numbers are passed instead of string in array of valid Serial Numbers in the batch JSON object.

**Comment by salboaie** [comment]
@adiganga2002 check to be always strings
