### ISSUE TITLE
FS-SEC-004 - System provides report on user access

### ISSUE THREAD

**Issue by nhrishi** [PharmaLedger-IMI/epi-workspace#685]
the report should contain: 
- list of users assigned to each type of roles in the Enterprise Wallet and/or Demiurge Wallet
- when they last accessed
- scope of roles
- when access was granted or disabled for a user

Excludes the access activities to infrastructure resources e.g. access to the Kubernetes cluster hosted in each company's cloud environment

**Comment by salboaie** [comment]
Basel meeting Decision that we dont need any reports just an CSV export of the raw data
