### ISSUE TITLE
after uploading 50k SN, I lost my recently created products/batches or was this due to another user doing same?

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#70]
•	I created product and several batches, different version, different languages – all worked fine. 
•	Next I have uploaded 10’000 SN for a batch – still all fine
•	Next I have uploaded 50’000 SN for a batch – got very short error but even worse: **now my last 3 batches are not shown on screen, neither in the audit log!!!!**
•	But I can still see the batches in my history scans on the mobile screen (to proof that they were really existing)
•	Is this because 50’000 SN was too much (but why are 3 of my batches disappeared?) or is this because same time Hrishikesh also created batches and this caused my batches to disappear?

**Comment by skutner** [comment]
I have not been able to replicate the bug after loading 500k SN.

**Comment by steinso2** [comment]
> I have not been able to replicate the bug after loading 500k SN.
@skutner did you also test the second part of the issue? 
**or** was this due to another user doing same?
