### ISSUE TITLE
Release 1.3.1 (Fixes 1.3.0 for Helm Charts)

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#728]
**New business features**
None
**New technical/security features**
None
**Tasks implementing the new features**
None

**Bug Fixes**
Overview: Changes in paths to accommodate with the read only images for build
[Copy demiurge apihub messages to external-volume at build #719](https://github.com/PharmaLedger-IMI/epi-workspace/issues/719)
[Ignore errors when copying files from trust-loader-config to apihub-root #720](https://github.com/PharmaLedger-IMI/epi-workspace/issues/720)
[Save mq messages in external-volume #717](https://github.com/PharmaLedger-IMI/epi-workspace/issues/717)
[Save epi logs in external-volume #718](https://github.com/PharmaLedger-IMI/epi-workspace/issues/718)
[Make private keys paths configurable in OauthMiddleware #713](https://github.com/PharmaLedger-IMI/epi-workspace/issues/713)
Minor fixes:
[Import JSON feature - in the JSON object, array of valid SNs accepts only string values but array of recalled and decomm. SNs accept both string and numbers #680](https://github.com/PharmaLedger-IMI/epi-workspace/issues/680)
[Adding new group in the Demiurge seems to not working #702](https://github.com/PharmaLedger-IMI/epi-workspace/issues/702)
[Better error when not using https #712](https://github.com/PharmaLedger-IMI/epi-workspace/issues/712)

**Security Fixes**
[Remove vulnerabilities in ethadapter docker image #716](https://github.com/PharmaLedger-IMI/epi-workspace/issues/716)
[Better error when not using https #712](https://github.com/PharmaLedger-IMI/epi-workspace/issues/712)

**Configuration Changes**
Various, will be covered by the helm-charts documentation

**Comment by nhrishi** [comment]
Closing this issue since the release is completed.
