### ISSUE TITLE
Necessary vars renaming

### ISSUE THREAD

**Issue by mppub** [PharmaLedger-IMI/epi-workspace#74]
# Motivation
During the work on related issue it appear that there has been misleading naming in the code, eg. `hash` vs `hashLink`, this has to be fixed for other in order not to be deceived.

# Result
Fix only the necessary things

**Comment by mppub** [comment]
PRs: 
- https://github.com/PrivateSky/apihub/pull/6
- https://github.com/PrivateSky/OpenDSU/pull/12

**Comment by asaccool** [comment]
pull requests accepted
