### ISSUE TITLE
Mismatch in Progressive Web App running on Desktop Browser  and Native iOS content when Data Matrix is scanned.

### ISSUE THREAD

**Issue by RakeshL-JnJ** [PharmaLedger-IMI/epi-workspace#842]
Release Version: 1.5.2
Environment: localhost with SSO Configuration.

Steps:
1. Created Demiurge and Enterprise wallet user.
2. In Enterprise wallet user created Product and Batch.
3.  In desktop browser launched leaflet Wallet and scanned 2D data matrix , which shows below screen:
![image](https://user-images.githubusercontent.com/82216409/179986630-b44dcb79-d31d-49d7-a551-99afd1222a63.png)
4. In iOS native App scanned same 2D datamatix, which shows below screen:
![image](https://user-images.githubusercontent.com/82216409/179987290-cf51f150-6923-47e8-9739-7978eb873c45.png)
if we compare this two images, in first image some information like Serial number, Product code, batch number etc are missing. Do I need to do any settings in Desktop Progressive Web App or it is expected?
5. 2D Data Matrix:
![image](https://user-images.githubusercontent.com/82216409/179988743-22539794-cf99-4602-b6f3-56e07dafd03d.png)

**Comment by adiganga2002** [comment]
Couldn't reproduce.
