### ISSUE TITLE
leaflet information batch specific vs latest: main scenario

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#85]
**PL user story:**  #36 

**Main changes to current ePI MVP in a nutshell:** 
- as-is situation: a specific leaflet version is assigned to a batch, and this version can't be changed.
- now: if no specific leaflet version is assigned to a batch, the latest version of that product will be displayed and this assignment is maintainable. 

**Description**

- It should be possible to assign a leaflet to a product. 
- When leaflet data was updated by pharmaceutical company, a new version of the leaflet will be assigned to that product. 
- Multiple versions of leaflets could be available per product.
(Product means on the level of GTIN/NTIN)
- When a batch is uploaded and no leaflet version was specifically assigned by user (or later by the interface),  the latest leaflet is assigned to that batch automatically. The "latest" leaflet means always the "latest", also after uploading a new version of the leaflet for the product (= latest leaflet). 
- When a batch is uploaded and a specific leaflet version was assigned by user (or later by the interface),  this version of the leaflet is assigned to this batch (=batch specific leaflet)
- Leaflet versions on batch level needs to be changeable by user (or later by interface) e.g. change batch specific leaflet to "latest leaflet", changing "latest" leaflet to leaflet version 4.  

**Acceptance criteria's:**
**positive tests**
- create a product-1 and assign leaflet V1
- update product and assign leaflet V2
- create a batch-A (no leaflet version assigned to that batch) 
- scan barcode batch-A and get leaflet V2 (=latest) displayed
- create a batch-B (assign batch specific leaflet V1)
- scan barcode batch-B and get leaflet V1 (=batch specific) displayed
- update product and assign leaflet V3
- scan barcode batch-A again and get leaflet V3 (=latest) displayed
- scan barcode batch-B again and get leaflet V1 (=batch specific) displayed
- display audit trail and verify that all product and batch creation and update is recorded (who, what, when it was maintained) 

**negative tests / error path testing**
- update a batch to correct a wrongly assigned leaflet version: Change batch-B to the "latest" leaflet version. Do not assign V3, because latest means always latest. 
- update product and assign leaflet V4
- scan barcode batch-B again and get leaflet V4 (=latest) displayed

**Process scenario:**
95% of the leaflets do not need to be batch specific, nevertheless there are reasons such as "peanuts" in earlier batches, which require specific information to be provided to our users. 

**Additional information:**
![image](https://user-images.githubusercontent.com/78138966/108371411-0259bf00-71fe-11eb-905b-2444a2e1da0b.png)

**Comment by steinso2** [comment]
@maherpa2 @nhrishi Please review, feel free to change

**Comment by salboaie** [comment]
Checkbox "batch specific" in the product page: the versions will be marked with "batch specific" and will not be used by the "latest" resolution when the leaflet is displayed

**Comment by maherpa2** [comment]
As I don't understand the checkbox proposal, I just want to restate what the concept is for the latest vs batch specific.

This is the concept for the latest versus Batch Specific leaflet topic:

- in the image below batches A, B and F always point to the "Latest ePI folder". The manufacturer would then load the latest updated leaflet into the "Latest ePI folder" and batches A, B and F would then have the latest version of the ePI.  So whatever is loaded into this "Latest ePI folder" will be displayed when the batches are scanned by the patient.
- Likewise batches C and D point to the "Batch Specific ePI 1 folder" and batch E points to the "Batch Specific ePI 2 folder".

![image](https://user-images.githubusercontent.com/58995303/109113179-1e002080-773c-11eb-8764-6d506551ce12.png)

- The versioning of the leaflet is managed outside the DSU Fabric.

**Comment by rite2bala** [comment]
The applications works as expected.

While creating a new product version, the PI and SmPC  are shown as inherited from the previous version. 
Enterprise wallet also allows user to update the version of product without uploading ePI. 
Enterprise wallet also allows user to upload a version as batch specific.

Thank you. 

Moving to UAT.
