### ISSUE TITLE
Additional message in recognised products

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#859]
Currently, the messages are concatenated with the generic message. 
Those messages should be presented in better form.

**Comment by asaccool** [comment]
For example the batch message is displayed after the translated text based on key "verified_status_message"
![Screenshot from 2022-08-03 17-00-52](https://user-images.githubusercontent.com/2776528/182627442-de426e0b-c3a7-4551-ae6e-92bcc4edea97.png). 
Similar behavior in the case of recalled batch message.
