### ISSUE TITLE
leaflet information batch specific vs latest: display leaflet version info

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#86]
**PL user story:** #36

**Description:**
It should be possible to display all versions assigned to the batches. This to verify which version is assigned to be able to do corrections. Beneficial is also to display the GTIN/NTIN (=product) for that batch.

**Acceptance criteria's:**
**positive tests**
- display versions for all batches or for a selection of batches
(future: this information should be made available for a pull request / via interface)
- display the product for that batch

**negative tests / error path testing**
n/a

**Process scenario:**
To be able to do corrections or evaluate the correct leaflet assignments, we need to have an easy way to display all versions assigned to the batches.

**Comment by steinso2** [comment]
test

**Comment by steinso2** [comment]
@maherpa2 @nhrishi Please review, feel free to change

**Comment by mppub** [comment]
notes:
- `It should be possible to display all versions assigned to the batches` can a batch have more version than one?
- `this information should be made available for a pull request ` does not make sense imo - or you want a feature(with a toggle) or not

**Comment by salboaie** [comment]
Checkbox "batch specific" in the product page: the versions will be marked with "batch specific" and will not be used by the "latest" resolution when the leaflet is displayed
