### ISSUE TITLE
Release 1.5.4 (September 2022)

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#864]
**New business features**
Demiurge preparations for qualification (security enhancing using OpenDSU encalves)

**New technical/security features**
Security improvements, cleanings
Terms and Conditions and Data Privacy Statement [#126](https://github.com/PharmaLedger-IMI/epi-workspace/issues/126)
Demiurge Audit Log Enhancements [#639](https://github.com/PharmaLedger-IMI/epi-workspace/issues/639)
Export Audit log as csv file [#873](https://github.com/PharmaLedger-IMI/epi-workspace/issues/873)
Warning on jailbroken devices [#622](https://github.com/PharmaLedger-IMI/epi-workspace/issues/622)
Native apps user info updates [#886](https://github.com/PharmaLedger-IMI/epi-workspace/issues/886)
FS-SEC-004 - System provides report on user access [#685](https://github.com/PharmaLedger-IMI/epi-workspace/issues/685)
[Backup process for demo network #778](https://github.com/PharmaLedger-IMI/epi-workspace/issues/778)
[Jailbreak on iOS detection and warning #835](https://github.com/PharmaLedger-IMI/epi-workspace/issues/835)
[Jailbreak on Android detection and warning #836](https://github.com/PharmaLedger-IMI/epi-workspace/issues/836)
[Generic Middleware for ACDC #867](https://github.com/PharmaLedger-IMI/epi-workspace/issues/867)
Optimizations (eg. loading)
Performance improvements: optimize OpenDSU SDK and bundling process
Improve the Verifiable Credentials support
/// Added by Lukas
Add more ApiHub/Application metrics to be available for logging tools (e.g. prometheus)
(tbd) Develop a blockchain network visualization dashboard
///

**Tasks implementing the new features**
[Acodis lealfet xml updated. #929](https://github.com/PharmaLedger-IMI/epi-workspace/issues/929)
[LWA - camera not accessible in Firefox browser in mobile device #916](https://github.com/PharmaLedger-IMI/epi-workspace/issues/916)
[Batch messages should get a separate modal dialog #861](https://github.com/PharmaLedger-IMI/epi-workspace/issues/861)
[Product Master issues in enterprise wallet - MVP1 #876](https://github.com/PharmaLedger-IMI/epi-workspace/issues/876)
[Native apps - Search feature enhancements #890](https://github.com/PharmaLedger-IMI/epi-workspace/issues/890)
[Expire check depends on batch settings in LPWA #925](https://github.com/PharmaLedger-IMI/epi-workspace/issues/925)
[Timestamp from Demiurge auditlog should be displayed to local format #904](https://github.com/PharmaLedger-IMI/epi-workspace/issues/904)
[FS-SEC-004 - System provides report on user access #685](https://github.com/PharmaLedger-IMI/epi-workspace/issues/685)
[Remove "display leaflet if" flags from code #913](https://github.com/PharmaLedger-IMI/epi-workspace/issues/913)
[Remove guide button form native app scanning #923](https://github.com/PharmaLedger-IMI/epi-workspace/issues/923)
[Accesss Management - Authorization-Role-based access control] Forced logout from wallets if users are removed from Demiurge groups [#872](https://github.com/PharmaLedger-IMI/epi-workspace/issues/872) - test case to be created
Add a next/previous arrows in the leaflet search functionality [#870](https://github.com/PharmaLedger-IMI/epi-workspace/issues/870) - test case to be created
Invented Name can be changed via Update API for product [#736](https://github.com/PharmaLedger-IMI/epi-workspace/issues/736) - test case to be created
[Blue loader in the trust-loader #869](https://github.com/PharmaLedger-IMI/epi-workspace/issues/869)
Lightweight PWA enhancements [#884](https://github.com/PharmaLedger-IMI/epi-workspace/issues/884) - test cases to be created
Native App User Info. Enhancements [#886](https://github.com/PharmaLedger-IMI/epi-workspace/issues/886) - test cases to be created

**Bug Fixes**
Investigate ePI - Demo Network - Experiencing lag & error [#789](https://github.com/PharmaLedger-IMI/epi-workspace/issues/789)
Mobile App performance issues [#688](https://github.com/PharmaLedger-IMI/epi-workspace/issues/688)
Audit timestamps were displayed in the wrong format [#904](https://github.com/PharmaLedger-IMI/epi-workspace/issues/904)
[Add ePI option at product/batch level should support only "leaflet" type #911](https://github.com/PharmaLedger-IMI/epi-workspace/issues/911)
[No error message while saving a batch without batch ID #912](https://github.com/PharmaLedger-IMI/epi-workspace/issues/912)
[Typo in "Patient Wallet" on landing page #885](https://github.com/PharmaLedger-IMI/epi-workspace/issues/885)
[In MVP1 we do not display warnings if the batch doesn't exist #917](https://github.com/PharmaLedger-IMI/epi-workspace/issues/917)
[SSO enabled Demiurge Wallet is failing to load screen after entering correct PIN #814](https://github.com/PharmaLedger-IMI/epi-workspace/issues/814)
[A spinner on PIN submission screen can provide better user experience while keeping the user on wait to login to Demiurge Wallet #819](https://github.com/PharmaLedger-IMI/epi-workspace/issues/819)
[commitBatch method fails in apihub mapping engine #860](https://github.com/PharmaLedger-IMI/epi-workspace/issues/860)
[Whitelist mq requests in OauthMiddleware to allow session timeout #844](https://github.com/PharmaLedger-IMI/epi-workspace/issues/844)
[Invalid date getting accepted via Import JSON and APIs during batch update #892](https://github.com/PharmaLedger-IMI/epi-workspace/issues/892)
[Lightweight PWA - Wrong output for unknown batch #883](https://github.com/PharmaLedger-IMI/epi-workspace/issues/883)
[Remove DIDs from groups (disable wallets) #751](https://github.com/PharmaLedger-IMI/epi-workspace/issues/751)
[Update "Pharmaledger" to "PharmaLedger" on LWA #839](https://github.com/PharmaLedger-IMI/epi-workspace/issues/839)
[If setup network is wrong on mobile app scan there is no error (app freezes). Add proper error. #878](https://github.com/PharmaLedger-IMI/epi-workspace/issues/878)
[Mixed up fileds #880](https://github.com/PharmaLedger-IMI/epi-workspace/issues/880)
[Different output in LWA and native app when a 2D code with invalid date is scanned #889](https://github.com/PharmaLedger-IMI/epi-workspace/issues/889)
[For unknown message type (mapping engine) there are no logs in audit and failed to digest message list. #743](https://github.com/PharmaLedger-IMI/epi-workspace/issues/743)
[Replace “Scan 2D code” with “Scan Datamatrix” in the LWA #827](https://github.com/PharmaLedger-IMI/epi-workspace/issues/827)
[Native app language - App is not considering device's language while displaying leaflet #896](https://github.com/PharmaLedger-IMI/epi-workspace/issues/896)
[Mismatch in Progressive Web App running on Desktop Browser and Native iOS content when Data Matrix is scanned. #842](https://github.com/PharmaLedger-IMI/epi-workspace/issues/842)
[LPWA wrong "product is expired" #915](https://github.com/PharmaLedger-IMI/epi-workspace/issues/915)
**Security Fixes**
/// Added by Lukas
Update to the latest version for Linux distributions and of the node (minor versions) [#882](https://github.com/PharmaLedger-IMI/epi-workspace/issues/882)
Resend failed transactions to blockchain [#919](https://github.com/PharmaLedger-IMI/epi-workspace/issues/919)
Fix critical and mandatory items form the security report (in private repo) [#887](https://github.com/PharmaLedger-IMI/epi-workspace/issues/887)
Security Cleanings for 1.5.4 [#875](https://github.com/PharmaLedger-IMI/epi-workspace/issues/875)
Quorum Blockchain Version Upgrade [#760](https://github.com/PharmaLedger-IMI/epi-workspace/issues/760)
Error handling in apihub [#918](https://github.com/PharmaLedger-IMI/epi-workspace/issues/918)
SeedSSIs were removed from apihub logs [#921](https://github.com/PharmaLedger-IMI/epi-workspace/issues/921)
///

**Configuration Changes**
[FeatureFlag for easter egg in mobile apps #905](https://github.com/PharmaLedger-IMI/epi-workspace/issues/905)
**Other - eg Optimisation, documentation**

**Postponed**

**Comment by lukasosterheider** [comment]
Check if "Fix for the "Lost SeedSSIs Corner Case" #888" will be part of this release or not.
