### ISSUE TITLE
leaflet information batch specific vs latest: interface to update product/batch/leaflet

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#87]
**PL user story:** #36

In current MVP we focus on updating the DSU manually, for productive pilot we need to ensure that we can do the product and batch creation, as well the leaflet assignments via interfaces. 

**Acceptance criteria's:**
**positive tests**
tbd

**negative tests / error path testing**
tbd

**Process scenario:**
tbd

**Additional information:**
![image](https://user-images.githubusercontent.com/78138966/108369754-3633e500-71fc-11eb-84b1-cec4e6e563bf.png)

**Comment by steinso2** [comment]
@maherpa2 @nhrishi Please review, feel free to change

**Comment by maherpa2** [comment]
@steinso2 @nhrishi we need to give the developers the bigger picture as to what we are trying to achieve, if this is understood then it would be much easier for them to manage each of these user stories.
