### ISSUE TITLE
Lightweight PWA enhancements

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#884]
As of latest release (v1.5.3) and based on updated URS - FS document, following features have to be added to LWA:

- [ ] Privacy Policy 
- [ ] Terms & Conditions
- [ ] App Version
- [ ] Online Help
- [ ] About / App owner
- [ ] Prompt to download native app

**Comment by nhrishi** [comment]
langauge translation would need to done once english text is finalized.
