### ISSUE TITLE
DSU Fabric - Batch Creation add Product Description

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#89]
**PL user story:** refer to #93 for additional information.

**Description:** 
Changes to the user Interface for DSU fabric:
Batch screen: 
     - when selecting the product, add description of the product (besides just the GTIN)
     - when no serial number is entered, create data matrix barcode without serial number (means without application identifier 21) refer to #100 
     - allow batch data can be changed (e.g. expiry date wrong, serial numbers need to be updated) or completely inactivated. refer to #99 

**Acceptance criteria's:**
**positive tests**
- create a new batch and verify if you see product description besides the GTIN or NTIN 
- create a batch without entering serial numbers, scan the data matrix and verify that no AI 21 is included 
- scan the batch with the PharmaLedger app and verify that serial number check is greyed out (inactive), because no SN check can be done if no SN were maintained. 
- try to change the batch. Change expiry date for that batch, add serial numbers for that batch 
- inactivate that batch

**negative tests / error path testing**
n/a

**Process scenario:**
n/a

**Additional information:**
- Manufacturers produce serial and non-serialized products so the DSU Fabric needs to be able to support this, refer to #100.
- The ability to update the batches once they have been created is necessary in order to rectify issues, refer to #99

**Comment by mppub** [comment]
notes:
- what is the relation between product description and batch description, do they complement each other or are they in a conflict(duplicates)?

**Comment by nhrishi** [comment]
@steinso2 @maherpa2 - in the positive tests, it says "inactivate that batch". We don't have this feature proposed yet. should we cover this in story #99.

**Comment by UnHynek** [comment]
inactivate products should be still be displayed - with "tag" inactive

**Comment by rite2bala** [comment]
@rite2bala - Make wireframe for this user story.

**Comment by rite2bala** [comment]
[ePI Wireframes - Product and Batch_v0.4.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6100225/ePI.Wireframes.-.Product.and.Batch_v0.4.pdf)


The Wireframes with for the product and batch screens are uploaded here.

The add product and edit product  screens follow similar layouts. 
Similarly - the edit batch and add batch screens have a similar layout

**Comment by rite2bala** [comment]
Quoting a comment from the initial description:
- when no serial number is entered, create data matrix barcode without serial number (means without application identifier 21) refer to #100

the above functionality doesnt work properly yet. It is being tracked on issue #111 
Hence , we are not moving this overall story to UAT at the moment.
