### ISSUE TITLE
Flags behavior in MVP1

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#893]
In MVP1 all "display leaflet flags" in product should e checked by default  and disabled (cant be unchecked)
The batch expiration verification should be unchecked and disabled

**Comment by adiganga2002** [comment]
![WhatsApp Image 2022-08-31 at 2 04 56 PM](https://user-images.githubusercontent.com/38322305/187922517-649ecb02-58f7-4412-a5bc-345370267eda.jpeg)
![WhatsApp Image 2022-08-31 at 2 04 29 PM](https://user-images.githubusercontent.com/38322305/187922522-1d38348b-31a5-4c68-84b5-af77f36f87a5.jpeg)
