### ISSUE TITLE
Product is getting created without Name of Medicinal product field

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#898]
Product is getting created without Name of Medicinal product field with following pop-up. Ideally, it should error with appropriate missing field name.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/20087001/187415728-927aba6f-92ee-4cd6-8098-18b7f21f68e2.png">

**Comment by adiganga2002** [comment]
FIxed in an other ticket
