### ISSUE TITLE
DSU Fabric Serial Number & Exp Date Checks Enable/ Disable

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#90]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the user Interface for DSU fabric:
- Add the following check marks to the screen (new functionality):
![image](https://user-images.githubusercontent.com/78138966/108510655-15809380-72bf-11eb-91d8-c6a97385ae0d.png)

**Acceptance criteria's:**
**positive tests**
- create a batch with SN, but mark no serial number check. Verify if the barcode with the wrong serial number creates no error message, because system should deactivate the SN check
- repeat for the other check marks

**negative tests / error path testing**
n/a

**Process scenario:**
In order to aid adoption it will be necessary to have the ability to do a soft launch of ePI hence the need to be able to enable / disable features.

**Additional information:**
![image](https://user-images.githubusercontent.com/78138966/108512142-15819300-72c1-11eb-84a6-31554617ba81.png)

If these checks are not enabled then the App would not show these features.
![image](https://user-images.githubusercontent.com/58995303/109102635-97424800-7729-11eb-8937-c0985afec29c.png)

**Comment by maherpa2** [comment]
@steinso2 this references step 5 but step 5 is not described. Suggest to include the complete set of screen shots/ descriptions so that the developers see the bigger picture.

**Comment by nhrishi** [comment]
@maherpa2 -
1. Should we keep all the 7 & 8 options checked by default. These checks are pretty much mandatory?
2. Should differentiate 7 & 8 on the product status file with below error messages. The message can be shown when the user clicks on the product status.
for 7 - "The expiry date on the scanned drug pack is not invalid and not as per the expiry date set by the Manufacturer."
for 8 - "The scanned drug pack is expired".

**Comment by rite2bala** [comment]
The enabling and disabling Serial number and expiration date checks works fine. 
We have tested all the attached scenarios. 

The serial numbers and expiration date checks are interdependent. 

Since the tests are passed, we are moving it to UAT stack.
[Tested_Product_DisplayEPI_Flags and Scenarios.xlsx](https://github.com/PharmaLedger-IMI/epi-workspace/files/6442190/Tested_Product_DisplayEPI_Flags.and.Scenarios.xlsx)
