### ISSUE TITLE
Add ePI option at product/batch level should support only "leaflet" type

### ISSUE THREAD

**Issue by kpratihast** [PharmaLedger-IMI/epi-workspace#911]
Add ePI option at product/batch level should support only "leaflet" type. For MVP1, SMPC is not supported

<img width="490" alt="image" src="https://user-images.githubusercontent.com/20087001/189611607-cb6abe82-85bd-4c96-8132-61b4b101f79d.png">

**Comment by salboaie** [comment]
What feature flag should be extended to gray out the "select a type"  and put by default "Leaflet" ? A new feature flag is required?
@kpratihast @steinso2  ?
