### ISSUE TITLE
Full Overview

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#93]
The purpose of this document is to try and give an overview to the development team of what is required from a business perspective and to try and give the rationale behind the requests. Each of these would need to be grouped and broken down into User Stories for the development team.
The topics covered are:

**DSU Manage Product Screen**
- This covers updates to existing functionality (ability to have the Material Number, GTIN and Product Description). We would have thousands and thousands of products so being able to search and sort the products is important.
- The ability to enable/ disable Adverse Event Reporting and Authentication. For Adverse reporting consider that for multi-markets packs (packs that are supplied to more than one country) that there may need to be more than 1 endpoint for reporting.
- Included are some setting on allowing the Manufacturer to decide under which unhappy path conditions that an ePI would be provided
- The App should only show certain features depending on what is enabled at the product level. This may become somewhat redundant if/ when the App is reworked but the ability to enable/ disable features will still be required.

**DSU Add Batch Screen**
- Capability to upload Commissioned Serial Numbers (already exists) and also Decommissioned Serial Numbers and Serial Numbers marked as part of a Batch Recall. It maybe beneficial to have the ability to recall based on the serial number level.
- Capability to enable/  disable the Serial Number Check, Expiration Date Check and the Expired Batch Check. The reason for this is to allow easy adoption and essentially a soft launch of ePI.
- Capability to have the complete batch marked for Recall. In this instance every time the batch is scanned then a message stating that the batch is subject to a recall is displayed. 
- Capability to have a batch specific message shown to the end user.
- The App should only show certain things if enabled/ disabled.

**Flow Chart**
- The purpose of the flow chart is to give an overview on what kind of checks should be performed and what the expected output would be from these checks, the attached excel sheet tries to indicate when an ePI should be displayed or not.

**Current State vs Future State**
- In the current state the ePI is assigned on the batch level and it is not possible (currently) to change anything to do with the batch. This was done in order to address the Batch Specific ePI.
- In probably over 95% of cases the latest leaflet is the correct leaflet to give to the patient. The idea therefore is to take the ePI/ SmPC from the product level. For the remaining batches there should be the ability to assign batch specific ePI's.
- As end users we need to be able to see what batches are assigned to what ePI's.

**Backend Integration**
- Consideration needs to be given to how the backend integration would work. There is a conceptual proposal put forward in the attached document.

[Serial Number Exp Date Check Proposal v0.3.xlsx](https://github.com/PharmaLedger-IMI/epi-workspace/files/6028655/Serial.Number.Exp.Date.Check.Proposal.v0.3.xlsx)

[App and DSU Fabric Feedback v0.2.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6028518/App.and.DSU.Fabric.Feedback.v0.2.pdf)

**Adoption**
In order for the solution to be adopted we need to have the ability to manage different barcodes that are on the market. The attached has some codes, there are most likely other codes as well on the market.
[Barcodes and Resolver v0.4.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6048321/Barcodes.and.Resolver.v0.4.pdf)

Additionally companies and countries need to have the ability to be able to configure the solution to suit their needs, hence flexibility in the solution is going to be key. 

@steinso2 @nhrishi : please review

**Comment by rite2bala** [comment]
[ePI Wireframes - Product and Batch_v0.4.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6100225/ePI.Wireframes.-.Product.and.Batch_v0.4.pdf)


The Wireframes for the product and batch screens are uploaded here.

The add product and edit product  screens follow similar layouts. 
Similarly - the edit batch and add batch screens have a similar layout
