### ISSUE TITLE
Chore: improve the opendsu.db to and create an api for resolving the concurrency issues while saving the history of products and batches

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#94]
# Motivation
While solving future conflicts, developers should have an api for storing and retrieving dsu changes

# Result
update opendsu/db to handle:
- storing updates from multiple users on their local fork of dsu in conflict-free manner
- create an api for mapping the conflict branching
- create test cases

**Comment by mppub** [comment]
first part:
- prepare the db for nested inserts/updates in order to track multiple related dsu changes simultaneously
- add timestamp,uid properties to the record in order to map the branching for conflict resolving
- update tests
- documentation

https://github.com/PrivateSky/OpenDSU/pull/13/files
