### ISSUE TITLE
[Lightweight PWA] check that all types of xmls are parsed accordingly

### ISSUE THREAD

**Issue by asaccool** [PharmaLedger-IMI/epi-workspace#944]
```
Only the DE german language is with <document> tag - the others leaflets in FR, NL are still with root. 
```

**Comment by steinso2** [comment]
[export.txt](https://github.com/PharmaLedger-IMI/epi-workspace/files/9713819/export.txt)
just adding info: 
Attached XML worked in the native app 1.5.4, but not in Lightweight. As long the document tag does not work on Leightweight PWA, we need to continue with root tag.
