### ISSUE TITLE
No settings icon available for Lightweight PWA, iOS

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#955]
No setting icon on top right of the screen available for Lightweight PWA. I am testing with iOS, Safari

Therefore I cannot test requirement to see in the settings: 

 - show background info who owns the app in about
 - show privacy information
 - show terms and conditions, re-ask in case condition changes
 - displays online help
 - version of the app (release version of epi-workspace code repository)
The language of e.g. help/terms & conditions etc needs to be displayed in the default mobile device language, if not available in that language show it in english

**Comment by adiganga2002** [comment]
fixed with #931
