### ISSUE TITLE
Lightweight PWA asking each time "allow access the camera"

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#958]
Each time when pressing the scan button in Lightweight PWA, the camera requests access to my camera 
(iOS, Safari)
In my general settings for safari is "asking when camera is to be used", maybe thats why I am always asked. But I do not want to change that for entire safari. 

Can we not ask once in Lightweight PWA and keep this in the "settings". In case I pressed by mistake "no", I could change this in my ePI Lightweight PWA settings?!?

**Comment by adiganga2002** [comment]
https://lightrun.com/answers/mebjas-html5-qrcode-safari-the-library-doesnt-seem-to-remember-the-camera-permission-

**Comment by steinso2** [comment]
This works! I just wonder how this will be explained to the patients :-))
