### ISSUE TITLE
Server single env file configuration

### ISSUE THREAD

**Issue by mppub** [PharmaLedger-IMI/epi-workspace#96]
# Motivation
We need to put all env files into root in order to manage ops better and manage other subtask from #63  as well as have better overview which workspace has what configuration (going to the nested folder is confusing for new people and chore for people who knows where to look)

# Result
files:
- epi-workspace/apihub-root/external-volume/config/server.json
- epi-workspace/apihub-root/external-volume/config/bdns.hosts
are in the root
all the imports in the modules are updated accordingly

**Comment by andrejstas** [comment]
We will not work on this task: these files should stay in this folder since they are mounted together as "external-volume" in docker.
