### ISSUE TITLE
DSU Fabric Serial Number Upload

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#97]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
This new functionality would be required on the Batch level.
Changes to the user Interface for DSU fabric in order to be able to upload Commissioned (= Good) serial numbers (This already exists, so 5 in the image below) and also Decommissioned (= Bad) serial numbers (5a in the image below) and also serial numbers marked for a Recall (5b in the image below) :
- Add the following new functionality to allow the upload of Good, Bad and Recalled serial numbers.
- There is a need to have a reason code associated to the Decommissioned serial numbers.
![image](https://user-images.githubusercontent.com/58995303/109103128-8ba35100-772a-11eb-902a-6906a3b51c2f.png)

**Acceptance criteria's:**
**positive tests**
- create a batch with serial numbers and have it loaded in the Commissioned serial number table (5). Scan the serial number and it should be verified.
- Update the batch and have a serial numbers in the Decommissioned serial number table (5a). Scan the serial number and a message should be displayed on the App telling the end user that the serial number is decommissioned and the reason why the serial number has been decommissioned.
- Update the batch and have a serial numbers in the Recall serial number table (5b). Scan the serial number and a message should be displayed on the App telling the end user that the serial number is part of a Recall.

**negative tests / error path testing**
refer to #90 and the enabling of the serial number check. This needs to be taken into consideration when developing the functionality in this user story.

**Process scenario:**
- Due to manufacturing issues we may need to recall certain portions of a batch instead of recalling the complete batch

**Additional information:**
- It maybe the case that serial number are Lost/ Stolen/ Damaged etc. In this situation the manufacturer would mark these as decommissioned and assign a Reason Code i.e. why the serial number(s) were decommissioned. It would be important to inform the end user as to the reason, hence the need to have a reason code associated to the serial numbers.

**Comment by nhrishi** [comment]
@maherpa2   - Have below points for clarification -
1. Since the user will have hundred/thousands of serial numbers to manage, should allow the user to upload in CSV/excel file or any other format instead of just copy/paste in the text box (may be considered for future release).  It's very much likely, the user will make mistake in updating these serial numbers.
2. Should we make 5b (recalled serial numbers) mandatory when the batch recall flag is updated. basically, when the user is updating the recall flag, the screen will also ask the user to input serial numbers along with it.
3. Extending point 2- Also, should we give an option "all" to mark all serial numbers recalled or enter specific serial numbers (assuming we have too many of them to manage).
4. For decommissioned serial numbers, should we show the associated reason code to the user on the app as a message. (Just to explicitly understand)

**Comment by UnHynek** [comment]
Are we recalling batch or serial numbers?

**Comment by UnHynek** [comment]
@rite2bala to to a UI wireframe

**Comment by maherpa2** [comment]
@UnHynek we can recall at the batch level or at the serial number level. Hence why both these features are requested. Imagine a scenario (it has happened) where 1000 serial numbers (packs) are produced but somewhere in the batch there were 50 serial numbers (packs) where there was an issue. we can simply mark these are recalled (or if we wished put them in the decommissioned table with an associated reason code). The idea is to give business the options to manage it in the best way that suits their needs. 
@nhrishi your points.
1. we would not manually upload 500K serial numbers, this would be more when we have the backend integration in place. The idea to upload serial numbers from an excel file or similar is fine. Consider this also for creating a product or batch - it might assist with the ultimate goal of the backend integration.
2. No, if the batch is marked as a recall then all serial numbers will be subject to the batch recall message. Perhaps in a future enhancement we can look at doing what you are suggesting. 
3. If all serial numbers were to be recalled then we would mark the batch as recalled. remember that it would be the backend integration that will supply the serial numbers to be Recalled and not the operator manually copying and pasting them in.
4. Yes, display the reason code.

**Comment by rite2bala** [comment]
[ePI Wireframes - Product and Batch_v0.4.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6100225/ePI.Wireframes.-.Product.and.Batch_v0.4.pdf)


The Wireframes for the product and batch screens are uploaded here.

The add product and edit product  screens follow similar layouts. 
Similarly - the edit batch and add batch screens have a similar layout

**Comment by adiganga2002** [comment]
![image](https://user-images.githubusercontent.com/38322305/110757831-7ebb4d00-8254-11eb-8982-aa34fec9e873.png)

**Comment by rite2bala** [comment]
Hi @adiganga2002  can we talk about the above comments?
slack: balakrishna.chandrasekaran@novartis.com
skype: bala.krishna@hotmail.co.uk

**Comment by rite2bala** [comment]
Hello @adiganga2002  

On the: https://github.com/PharmaLedger-IMI/epi-workspace/issues/93

There is an excel sheet called: "Serial Number Exp Date Check Proposal v0.3.xlsx"  with all the list of possibilities.

There is also a file:   "App and DSU Fabric Feedback v0.2.pdf" and field number 9 refers to the "Settings to display product information"

Could you please check if we could get the answers to our questions from there?

Please feel free to ping me if you have more queries apart from the cases covered there.
Thank you.

**Comment by maherpa2** [comment]
@rite2bala @adiganga2002 if there are any questions then please setup a call and we can go through these.
