### ISSUE TITLE
Remove not needed fields from Product overview screen

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#977]
On product overview screen following fields needs to be removed to avoid confusion:

- AE Report Enabled
- AC Check Enabled

**Comment by salboaie** [comment]
@steinso2  Should be removed or being disabled is enough?

**Comment by steinso2** [comment]
@salboaie - the fields are disabled in the product detail screen. This is fine. 
In the product OVERVIEW screen they should be removed.
