### ISSUE TITLE
DSU Fabric Batch Recall

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#98]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
This new functionality would be required on the Batch level.
Changes to the user Interface for DSU fabric in order to be able to Recall the batch. There are 2 components to this:
1. The Recall Flag (9 in the image below)
2. Batch Message (10 in the image below)

![image](https://user-images.githubusercontent.com/58995303/109104819-02d9e480-772d-11eb-8114-933322f27004.png)

- The functionality to Set/ Reset the Batch Recall Flag is required
- The functionality to change the Batch Message is required

**Acceptance criteria's:**
**positive tests**
- create a batch and set the Recall Flag (9) to True (On). When a code is scanned then a message should be shown to the end user stating that the Batch is subject to a recall. Whether or not an ePI is displayed is determined by **ADD REFERENCE TO APPROPRIATE USER STORY**
- If the Batch Message field (10) is not empty then the message that this in this field should be shown to the end user.

**negative tests / error path testing**
- Put the Batch Recall Flag to False (Off), then when a code is scanned then no batch recall message is shown to the end user.
- If the Batch Message field (10) is empty then nothing is shown to the end user.

**Process scenario:**
- It is the case that there may be an issue with a complete batch so it needs to be recalled from the market. In this instance by setting the Batch Recall Flag to True (On) then the end user would be informed when the code is scanned.
- Imagine a situation where a number of batches of a product has an issue and it is all over the media, then it might be useful to be able to tell the patient that this specific batch is not impacted by the recall/ issue.

**Additional information:**
![image](https://user-images.githubusercontent.com/58995303/109106657-8812c880-7730-11eb-8961-c1b07f85a9d1.png)

**Comment by nhrishi** [comment]
@maherpa2 - Would like to clarify few points - 
1. Should we allow batch recall if the batch is already expired (expiry date <= current date).
2. Should we make a batch message update mandatory when the batch recall is being done. So this way, the user can update the existing batch message with recall details and we don't need to show 2 different messages. 
3. Based on point 2,  if a batch message is set before the batch recall, the user will be able to update the existing batch message with more details about the recall during the recall process.
4. Do we need to create a specific format for a batch message. Example - publish date, batch message content, PDF attachment (required?), active/inactive status.

**Comment by UnHynek** [comment]
Push notifications on mobile? (maybe a problem)

**Comment by rite2bala** [comment]
[ePI Wireframes - Product and Batch_v0.4.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6100225/ePI.Wireframes.-.Product.and.Batch_v0.4.pdf)


The Wireframes for the product and batch screens are uploaded here.

The add product and edit product  screens follow similar layouts. 
Similarly - the edit batch and add batch screens have a similar layout

**Comment by rite2bala** [comment]
![image](https://user-images.githubusercontent.com/44022980/111598250-08d75880-87f5-11eb-9620-e68a96692391.png)

Please change the text "QR Code" to "Barcode"

**Comment by rite2bala** [comment]
There is no problem with the functionality. A certain text needs to be changed while displaying the product. 

Please refer to point 2 on the issue  #183  

We can move it to UAT once the point is corrected.
