### ISSUE TITLE
json upload product: mandatory field not considered

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#987]
When uploading json, the mandatory fields are not considered. 
Using json we can create product data without brand name/invented name and Name of Medicinal Product. 

This needs to be corrected

**Comment by steinso2** [comment]
Hi, I need to re-open because for whatever reason the 
 nationalCode - is now a required field. This is optional field. 

Now we cannot upload without national code......

**Comment by adiganga2002** [comment]
@steinso2 this means that a market is mandatory for adding/editing a product ?

**Comment by steinso2** [comment]
no, neither the market nor the national code is mandatory

**Comment by steinso2** [comment]
need to reopen again: market is still shown as mandatory field

**Comment by steinso2** [comment]
if we keep the section for markets included, but empty, we get the error message mandatory field missing for "market". Workaround for MVP1: take out this section
