### ISSUE TITLE
DSU Fabric Batch Screen (General)

### ISSUE THREAD

**Issue by maherpa2** [PharmaLedger-IMI/epi-workspace#99]
**PL user story:** #93 (see full overview for additional information)

**Description:** 
Changes to the User Interface for DSU fabric for the Add Batch Screen:
- The ability to Edit and update the batch after it has been created.
- Editable fields - 
1. Product (existing field)
2. EPI version (existing field)
3. Expiry Date (existing field)
4. Commissioned Serial Numbers (changed existing, story #97)
5. Decommissioned Serial Numbers (story #97 )
6. Recalled Serial Numbers (story #97)
7. Batch Recall Flag (story #98)
8. Batch Message (story #98)
9. Serial Number check flag (story #90)
10. Incorrect expiration date check flag (story #90)
11. Expired expiration date check flag (story #90)

**Acceptance criteria's:**
**positive tests**
- create a batch and afterward edit the batch to add additional serial numbers (refer to #97), update Batch Recall Flag/ Batch Message (refer #98), enable/ disable Serial number and Expiry Date checks (refer #93), assign/ correct the ePI Version etc.

**negative tests / error path testing**
n/a

**Process scenario:**
We need the ability to edit and update the Batch details in case of an error.

**Additional information:**
N/A

**Comment by nhrishi** [comment]
@maherpa2 - Should we also allow product change in case the user assigns the wrong product to a batch.

**Comment by maherpa2** [comment]
@nhrishi 

- I updated the list of editable fields explicitly in the story. Kindly review if anything missing/incorrect. - PJM :This looks ok

- Should we also allow product change in case the user assigns the wrong product to a batch. (Check with Sinica) - PJM: If we have written the GTIN+Bath Anchor onto the Blockchain then it will remain there even if it is incorrect. Where would the endpoint (DSU hashlink) go if this incorrect GTIN+Batch was actually scanned?
- Also, should we add inactivate batch feature as well? (Need to discuss with Sonja) - PJM: Need to check with Sonja as I am not sure of the thought process behind this. I could see where we would inactivate a Product so that no more batches could be created against it.

**Comment by rite2bala** [comment]
The Enterprise Wallet works as expected, but @maherpa2  has mentioned points for clarifications. 


cc: @nhrishi  - We can move this story to UAT if there are no further comments/ changes required based on the comment from Patrick on 4th March.
