### ISSUE TITLE
json import: view response button

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#992]
json import: view response button

in "view response" I can see only success messages, but not the errors.

**Comment by adiganga2002** [comment]
we identified this problem as a missing configuration. Will be fixed with next release.

**Comment by steinso2** [comment]
the only response I see in the new release is "error". No logs shown

**Comment by salboaie** [comment]
@steinso2 this functionality exists only for external message (sent with POSTMAN)
I propose to remove  "View Responses" button for MVP1 as it creates confusions. That endpoint was created for demo purposes only anyway. In production that endpoint it should go on an external system and should not be an APIHub functionality

**Comment by steinso2** [comment]
I agree to remove the button.
