### ISSUE TITLE
Wrong error message when scanning wrong barcode

### ISSUE THREAD

**Issue by steinso2** [PharmaLedger-IMI/epi-workspace#995]
When scanning a product / **GTIN** which is **not created in EW,** I get the text

_small text:_ Leaflet unavailable  ---> **correct**
_bold big text:_ Language Missing  ----> **incorrect**, text needs to be changed. Not the language is missing, the leaflet is missing!
_long text:_ We are sorry but there are no leaflets.....  ---> **correct**

When scanning a **barcode which is incorrect** I get the error message: 

_small text:_ Scan error  ---> **incorrect** why is it a scan error?
_bold big text:_ Can't access camera  ----> **incorrect**, the camera was used and t is accessed, so why this message?
_long text:_ something went wrong and selected camera can not be accessed properly, Please check your device camera settings or try to change camera from the menu.....  ---> **incorrect**
I think a wrong error message was assigned

**Comment by salboaie** [comment]
Firefox still not working. Probably we have introduced unsupported APIs in the last changes?

**Comment by steinso2** [comment]
Only Chrome and Safari are part of the scope, so firefox is not priority

**Comment by steinso2** [comment]
Please do not implement error description from this ticket, because we got all error descriptions reviewed by business and I have created a new ticket: 1035. sorry for this.
